### PR TITLE
Add PerformanceAnalyzer plugin to manifest 1.2.0

### PR DESCRIPTION
**Pull request by kjoseph07**
Signed-off-by: Karishma Joseph <karisjos@amazon.com>

### Description
Add PerfromanceAnalyzer plugin to manifest 1.2.0
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Rebase this on top of #876, I think this is an unrelated failure.

**Comment by kjoseph07** [comment]
> Rebase this on top of #876, I think this is an unrelated failure.

Done

**Review by peternied — CHANGES_REQUESTED** [review]
`performance-analyzer.git@main` is unable to resolve a dependency, please take a look at the CI failure and update the source codebase to resolve the issue.

**Review by dblock — APPROVED** [review]

**Comment by kjoseph07** [comment]
> performance-analyzer

:white_check_mark: Updated `performance-analyzer `  to resolve the issue.

**Review by peternied — APPROVED** [review]

**Pull request merged**
