### PR TITLE
Cleanup deb/rpm integTest uninstallation properly

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Cleanup deb/rpm integTest uninstallation properly

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/3815

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Does the user have permission to remove the files using `rm -rf`?

**Comment by peterzhuamazon** [comment]
> Does the user have permission to remove the files using `rm -rf`?

Yes
```
`which rm`, 
```

**Review by gaiksaya — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-build/5074/console
https://build.ci.opensearch.org/job/docker-build/5075/console
https://build.ci.opensearch.org/job/docker-build/5076/console

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-copy/1069/console

**Pull request merged**
