### PR TITLE
Add security plugin to manifest 1.2.0

### PR DESCRIPTION
**Pull request by cliu123**
Signed-off-by: cliu123 <lc12251109@gmail.com>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Review by davidlago — APPROVED** [review]

**Comment by dblock** [comment]
You'll also need to change a failing test that verifies number of components in the 1.2 manifest, test_1_2.

**Review by dblock — CHANGES_REQUESTED** [review]
You'll also need to change a failing test that verifies number of components in the 1.2 manifest, test_1_2 and rebase.

**Comment by cliu123** [comment]
> You'll also need to change a failing test that verifies number of components in the 1.2 manifest, test_1_2 and rebase.

@dblock  Done

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Review by dblock — APPROVED** [review]

**Pull request merged**
