### PR TITLE
Added default CI image.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

The auto-generated manifests need to include CI image.

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by tianleh — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Comment by dblock** [comment]
We probably will need to have a default image, or require the ci.image in the schema to avoid having this problem in the future reliably.

**Review by kavilla — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
`ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211019`
This one does not even exist @dblock.
It is being replaced by `centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028` and will soon be replaced again, as we are planning to add arm64 cypress binary to the picture.

**Comment by gaiksaya** [comment]
> `ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211019` This one does not even exist @dblock. It is being replaced by `centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028` and will soon be replaced again, as we are planning to add arm64 cypress binary to the picture.

Why are we deleting the images? Let it be there, the appropriate ones will be pulled by the consumers. Deleting is dangerous as we don't know all the places where the image is being used.

**Comment by dblock** [comment]
> > `ci-runner:centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211019` This one does not even exist @dblock. It is being replaced by `centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211028` and will soon be replaced again, as we are planning to add arm64 cypress binary to the picture.
> 
> Why are we deleting the images? Let it be there, the appropriate ones will be pulled by the consumers. Deleting is dangerous as we don't know all the places where the image is being used.

We definitely need to keep old images to build old code with old tools and manifests.

**Pull request merged**
