### PR TITLE
Support JDK-21 builds on Jenkins

### PR DESCRIPTION
**Pull request by reta**
### Description
Support JDK-21 builds on Jenkins

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/4071

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
I will rebuild the images with both #4154 and this PR.

**Comment by peterzhuamazon** [comment]
@reta need one more for the windows images here:

https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/config/windows-servercore-setup.ps1#L87

Note that tumarin hasnt have 21 on scoop, so `openjdk21` it is for now.

Thanks.

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-build/4084/console

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-copy/780/console
https://build.ci.opensearch.org/job/docker-copy/781/console
https://build.ci.opensearch.org/job/docker-copy/782/console
https://build.ci.opensearch.org/job/docker-copy/783/console
https://build.ci.opensearch.org/job/docker-copy/784/console

**Comment by reta** [comment]
Tried a few images, all is set:

```
[opensearch@fb75291982da ~]$ export | grep JAVA
declare -x JAVA11_HOME="/opt/java/openjdk-11"
declare -x JAVA17_HOME="/opt/java/openjdk-17"
declare -x JAVA19_HOME="/opt/java/openjdk-19"
declare -x JAVA20_HOME="/opt/java/openjdk-20"
declare -x JAVA21_HOME="/opt/java/openjdk-21"
declare -x JAVA8_HOME="/opt/java/openjdk-8"
declare -x JAVA_HOME="/opt/java/openjdk-21"
[opensearch@fb75291982da ~]$ $JAVA21_HOME/bin/java --version
openjdk 21 2023-09-19 LTS
OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)
[opensearch@fb75291982da ~]$ 

```

**Pull request merged**
