### PR TITLE
Add async search in 2.8 manifest

### PR DESCRIPTION
**Pull request by Arpit-Bandejiya**
### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — APPROVED** [review]

**Review by gaiksaya — CHANGES_REQUESTED** [review]
Checks are missing from this change. https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0/opensearch-2.7.0.yml#L133-L141

Can you also rebase once?
Thanks!

**Comment by Arpit-Bandejiya** [comment]
@gaiksaya  thanks! I have rebased it please review.

**Comment by gaiksaya** [comment]
> @gaiksaya thanks! I have rebased it please review.

Hi @Arpit-Bandejiya Your change is still missing `checks` section. Can you add the same please?
Thanks!

**Comment by Arpit-Bandejiya** [comment]
@gaiksaya  seems like main is failing.

**Comment by gaiksaya** [comment]
Related manifest check passed: https://github.com/opensearch-project/opensearch-build/actions/runs/4944099662/jobs/8854738566?pr=3471
3.0.0 failure is known issue. Merging the PR

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
