### PR TITLE
Update the OSD manifest with commit ID

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Update the just the OSD manifest with commit ID
Will update #2855 for just OS ref change.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by prudhvigodithi — APPROVED** [review]

**Comment by zelinh** [comment]
Block this PR till we have the commit ID for FT Dashboards updated once this [PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/380) merged and backported to 2.4 branch.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by zelinh** [comment]
> Block this PR till we have the commit ID for FT Dashboards updated once this [PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/380) merged and backported to 2.4 branch.

Updated the commit for FT dashboards with latest change.

**Comment by peterzhuamazon** [comment]
The failures are due to opensearch-project/opensearch#5127 not backported to all the branches yet.
Not related now.

Thanks.

**Comment by zelinh** [comment]
Run the CI test locally, it's passing there.
```
☁  ~/workplace/fork/opensearch-build[update-ref-240-osd] ⚡  ./ci.sh manifests/2.4.0/opensearch-dashboards-2.4.0.yml --snapshot
Installing dependencies in . ...
Installing dependencies from Pipfile.lock (b36c9c)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 38/38 — 00:00:25
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_ci.py manifests/2.4.0/opensearch-dashboards-2.4.0.yml --snapshot ...
2022-11-07 22:53:56 INFO     Sanity-testing in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc
2022-11-07 22:53:56 INFO     Sanity testing OpenSearch Dashboards
2022-11-07 22:53:56 INFO     Sanity testing OpenSearch-Dashboards
2022-11-07 22:53:56 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/OpenSearch-Dashboards
2022-11-07 22:53:56 INFO     Executing "git remote add origin https://github.com/opensearch-project/OpenSearch-Dashboards.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/OpenSearch-Dashboards
2022-11-07 22:53:56 INFO     Executing "git fetch --depth 1 origin 78059046c6db139d8e17aa759d6683de61f15548" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/OpenSearch-Dashboards
2022-11-07 22:56:39 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/OpenSearch-Dashboards
2022-11-07 22:56:47 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/OpenSearch-Dashboards
2022-11-07 22:56:47 INFO     Checked out https://github.com/opensearch-project/OpenSearch-Dashboards.git@78059046c6db139d8e17aa759d6683de61f15548 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/OpenSearch-Dashboards at 78059046c6db139d8e17aa759d6683de61f15548
2022-11-07 22:56:47 INFO     Checking https://github.com/opensearch-project/OpenSearch-Dashboards.git at 78059046c6db139d8e17aa759d6683de61f15548.
2022-11-07 22:56:47 INFO     Detect OpenSearch-Dashboards with ref 78059046c6db139d8e17aa759d6683de61f15548 in sha1 format, treat as commit.
2022-11-07 22:56:47 INFO     Found https://github.com/opensearch-project/OpenSearch-Dashboards.git at 78059046c6db139d8e17aa759d6683de61f15548.
2022-11-07 22:56:47 INFO     Done.
2022-11-07 22:56:47 INFO     Sanity testing functionalTestDashboards
2022-11-07 22:56:47 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/functionalTestDashboards
2022-11-07 22:56:47 INFO     Executing "git remote add origin https://github.com/opensearch-project/opensearch-dashboards-functional-test.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/functionalTestDashboards
2022-11-07 22:56:47 INFO     Executing "git fetch --depth 1 origin f162168afd37b1d4c37b80d28f89845509b679f6" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/functionalTestDashboards
2022-11-07 22:56:52 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/functionalTestDashboards
2022-11-07 22:56:53 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/functionalTestDashboards
2022-11-07 22:56:53 INFO     Checked out https://github.com/opensearch-project/opensearch-dashboards-functional-test.git@f162168afd37b1d4c37b80d28f89845509b679f6 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/functionalTestDashboards at f162168afd37b1d4c37b80d28f89845509b679f6
2022-11-07 22:56:53 INFO     Checking https://github.com/opensearch-project/opensearch-dashboards-functional-test.git at f162168afd37b1d4c37b80d28f89845509b679f6.
2022-11-07 22:56:53 INFO     Detect functionalTestDashboards with ref f162168afd37b1d4c37b80d28f89845509b679f6 in sha1 format, treat as commit.
2022-11-07 22:56:53 INFO     Found https://github.com/opensearch-project/opensearch-dashboards-functional-test.git at f162168afd37b1d4c37b80d28f89845509b679f6.
2022-11-07 22:56:53 INFO     Done.
2022-11-07 22:56:53 INFO     Sanity testing notificationsDashboards
2022-11-07 22:56:53 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/notificationsDashboards
2022-11-07 22:56:53 INFO     Executing "git remote add origin https://github.com/opensearch-project/notifications.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/notificationsDashboards
2022-11-07 22:56:53 INFO     Executing "git fetch --depth 1 origin 3e96daed51a64b57a2bc78c368f0a34b2d4852c0" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/notificationsDashboards
2022-11-07 22:56:54 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/notificationsDashboards
2022-11-07 22:56:54 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/notificationsDashboards
2022-11-07 22:56:54 INFO     Checked out https://github.com/opensearch-project/notifications.git@3e96daed51a64b57a2bc78c368f0a34b2d4852c0 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/notificationsDashboards at 3e96daed51a64b57a2bc78c368f0a34b2d4852c0
2022-11-07 22:56:54 INFO     Checking https://github.com/opensearch-project/notifications.git at 3e96daed51a64b57a2bc78c368f0a34b2d4852c0.
2022-11-07 22:56:54 INFO     Detect notificationsDashboards with ref 3e96daed51a64b57a2bc78c368f0a34b2d4852c0 in sha1 format, treat as commit.
2022-11-07 22:56:54 INFO     Found https://github.com/opensearch-project/notifications.git at 3e96daed51a64b57a2bc78c368f0a34b2d4852c0.
2022-11-07 22:56:54 INFO     Done.
2022-11-07 22:56:54 INFO     Sanity testing observabilityDashboards
2022-11-07 22:56:54 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/observabilityDashboards
2022-11-07 22:56:54 INFO     Executing "git remote add origin https://github.com/opensearch-project/observability.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/observabilityDashboards
2022-11-07 22:56:54 INFO     Executing "git fetch --depth 1 origin a1527c5fceb6226d1ee4f4e54c1868bfb289bd94" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/observabilityDashboards
2022-11-07 22:56:59 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/observabilityDashboards
2022-11-07 22:56:59 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/observabilityDashboards
2022-11-07 22:56:59 INFO     Checked out https://github.com/opensearch-project/observability.git@a1527c5fceb6226d1ee4f4e54c1868bfb289bd94 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/observabilityDashboards at a1527c5fceb6226d1ee4f4e54c1868bfb289bd94
2022-11-07 22:56:59 INFO     Checking https://github.com/opensearch-project/observability.git at a1527c5fceb6226d1ee4f4e54c1868bfb289bd94.
2022-11-07 22:56:59 INFO     Detect observabilityDashboards with ref a1527c5fceb6226d1ee4f4e54c1868bfb289bd94 in sha1 format, treat as commit.
2022-11-07 22:56:59 INFO     Found https://github.com/opensearch-project/observability.git at a1527c5fceb6226d1ee4f4e54c1868bfb289bd94.
2022-11-07 22:56:59 INFO     Done.
2022-11-07 22:56:59 INFO     Sanity testing reportsDashboards
2022-11-07 22:56:59 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/reportsDashboards
2022-11-07 22:57:00 INFO     Executing "git remote add origin https://github.com/opensearch-project/dashboards-reports.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/reportsDashboards
2022-11-07 22:57:00 INFO     Executing "git fetch --depth 1 origin ad7455c810b3760ab033a981596015a874a9356e" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/reportsDashboards
2022-11-07 22:57:04 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/reportsDashboards
2022-11-07 22:57:04 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/reportsDashboards
2022-11-07 22:57:04 INFO     Checked out https://github.com/opensearch-project/dashboards-reports.git@ad7455c810b3760ab033a981596015a874a9356e into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/reportsDashboards at ad7455c810b3760ab033a981596015a874a9356e
2022-11-07 22:57:04 INFO     Checking https://github.com/opensearch-project/dashboards-reports.git at ad7455c810b3760ab033a981596015a874a9356e.
2022-11-07 22:57:04 INFO     Detect reportsDashboards with ref ad7455c810b3760ab033a981596015a874a9356e in sha1 format, treat as commit.
2022-11-07 22:57:04 INFO     Found https://github.com/opensearch-project/dashboards-reports.git at ad7455c810b3760ab033a981596015a874a9356e.
2022-11-07 22:57:04 INFO     Done.
2022-11-07 22:57:04 INFO     Sanity testing securityDashboards
2022-11-07 22:57:04 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityDashboards
2022-11-07 22:57:04 INFO     Executing "git remote add origin https://github.com/opensearch-project/security-dashboards-plugin.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityDashboards
2022-11-07 22:57:04 INFO     Executing "git fetch --depth 1 origin c1e77f70db1176e78cd1d1b64e17acaaa589cf83" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityDashboards
2022-11-07 22:57:05 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityDashboards
2022-11-07 22:57:05 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityDashboards
2022-11-07 22:57:05 INFO     Checked out https://github.com/opensearch-project/security-dashboards-plugin.git@c1e77f70db1176e78cd1d1b64e17acaaa589cf83 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityDashboards at c1e77f70db1176e78cd1d1b64e17acaaa589cf83
2022-11-07 22:57:05 INFO     Checking https://github.com/opensearch-project/security-dashboards-plugin.git at c1e77f70db1176e78cd1d1b64e17acaaa589cf83.
2022-11-07 22:57:05 INFO     Detect securityDashboards with ref c1e77f70db1176e78cd1d1b64e17acaaa589cf83 in sha1 format, treat as commit.
2022-11-07 22:57:05 INFO     Found https://github.com/opensearch-project/security-dashboards-plugin.git at c1e77f70db1176e78cd1d1b64e17acaaa589cf83.
2022-11-07 22:57:05 INFO     Done.
2022-11-07 22:57:05 INFO     Sanity testing anomalyDetectionDashboards
2022-11-07 22:57:05 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/anomalyDetectionDashboards
2022-11-07 22:57:05 INFO     Executing "git remote add origin https://github.com/opensearch-project/anomaly-detection-dashboards-plugin" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/anomalyDetectionDashboards
2022-11-07 22:57:05 INFO     Executing "git fetch --depth 1 origin 7ec7b41411f78a54897684a109aa0099fb8d9e25" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/anomalyDetectionDashboards
2022-11-07 22:57:07 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/anomalyDetectionDashboards
2022-11-07 22:57:07 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/anomalyDetectionDashboards
2022-11-07 22:57:07 INFO     Checked out https://github.com/opensearch-project/anomaly-detection-dashboards-plugin@7ec7b41411f78a54897684a109aa0099fb8d9e25 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/anomalyDetectionDashboards at 7ec7b41411f78a54897684a109aa0099fb8d9e25
2022-11-07 22:57:07 INFO     Checking https://github.com/opensearch-project/anomaly-detection-dashboards-plugin at 7ec7b41411f78a54897684a109aa0099fb8d9e25.
2022-11-07 22:57:07 INFO     Detect anomalyDetectionDashboards with ref 7ec7b41411f78a54897684a109aa0099fb8d9e25 in sha1 format, treat as commit.
2022-11-07 22:57:07 INFO     Found https://github.com/opensearch-project/anomaly-detection-dashboards-plugin at 7ec7b41411f78a54897684a109aa0099fb8d9e25.
2022-11-07 22:57:07 INFO     Done.
2022-11-07 22:57:07 INFO     Sanity testing alertingDashboards
2022-11-07 22:57:07 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/alertingDashboards
2022-11-07 22:57:07 INFO     Executing "git remote add origin https://github.com/opensearch-project/alerting-dashboards-plugin.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/alertingDashboards
2022-11-07 22:57:07 INFO     Executing "git fetch --depth 1 origin 91868484dc4b22562ab8a56d43840657145acb1b" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/alertingDashboards
2022-11-07 22:57:08 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/alertingDashboards
2022-11-07 22:57:08 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/alertingDashboards
2022-11-07 22:57:08 INFO     Checked out https://github.com/opensearch-project/alerting-dashboards-plugin.git@91868484dc4b22562ab8a56d43840657145acb1b into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/alertingDashboards at 91868484dc4b22562ab8a56d43840657145acb1b
2022-11-07 22:57:08 INFO     Checking https://github.com/opensearch-project/alerting-dashboards-plugin.git at 91868484dc4b22562ab8a56d43840657145acb1b.
2022-11-07 22:57:08 INFO     Detect alertingDashboards with ref 91868484dc4b22562ab8a56d43840657145acb1b in sha1 format, treat as commit.
2022-11-07 22:57:08 INFO     Found https://github.com/opensearch-project/alerting-dashboards-plugin.git at 91868484dc4b22562ab8a56d43840657145acb1b.
2022-11-07 22:57:08 INFO     Done.
2022-11-07 22:57:08 INFO     Sanity testing queryWorkbenchDashboards
2022-11-07 22:57:08 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/queryWorkbenchDashboards
2022-11-07 22:57:08 INFO     Executing "git remote add origin https://github.com/opensearch-project/sql.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/queryWorkbenchDashboards
2022-11-07 22:57:09 INFO     Executing "git fetch --depth 1 origin 9944f2e9a263ee06e7da99d72cc88f7eb267633f" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/queryWorkbenchDashboards
2022-11-07 22:57:15 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/queryWorkbenchDashboards
2022-11-07 22:57:16 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/queryWorkbenchDashboards
2022-11-07 22:57:16 INFO     Checked out https://github.com/opensearch-project/sql.git@9944f2e9a263ee06e7da99d72cc88f7eb267633f into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/queryWorkbenchDashboards at 9944f2e9a263ee06e7da99d72cc88f7eb267633f
2022-11-07 22:57:16 INFO     Checking https://github.com/opensearch-project/sql.git at 9944f2e9a263ee06e7da99d72cc88f7eb267633f.
2022-11-07 22:57:16 INFO     Detect queryWorkbenchDashboards with ref 9944f2e9a263ee06e7da99d72cc88f7eb267633f in sha1 format, treat as commit.
2022-11-07 22:57:16 INFO     Found https://github.com/opensearch-project/sql.git at 9944f2e9a263ee06e7da99d72cc88f7eb267633f.
2022-11-07 22:57:16 INFO     Done.
2022-11-07 22:57:16 INFO     Sanity testing ganttChartDashboards
2022-11-07 22:57:16 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/ganttChartDashboards
2022-11-07 22:57:16 INFO     Executing "git remote add origin https://github.com/opensearch-project/dashboards-visualizations.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/ganttChartDashboards
2022-11-07 22:57:17 INFO     Executing "git fetch --depth 1 origin 48b418c55c4d4fc15ba1685680464469b92fa367" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/ganttChartDashboards
2022-11-07 22:57:17 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/ganttChartDashboards
2022-11-07 22:57:17 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/ganttChartDashboards
2022-11-07 22:57:17 INFO     Checked out https://github.com/opensearch-project/dashboards-visualizations.git@48b418c55c4d4fc15ba1685680464469b92fa367 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/ganttChartDashboards at 48b418c55c4d4fc15ba1685680464469b92fa367
2022-11-07 22:57:17 INFO     Checking https://github.com/opensearch-project/dashboards-visualizations.git at 48b418c55c4d4fc15ba1685680464469b92fa367.
2022-11-07 22:57:17 INFO     Detect ganttChartDashboards with ref 48b418c55c4d4fc15ba1685680464469b92fa367 in sha1 format, treat as commit.
2022-11-07 22:57:17 INFO     Found https://github.com/opensearch-project/dashboards-visualizations.git at 48b418c55c4d4fc15ba1685680464469b92fa367.
2022-11-07 22:57:17 INFO     Done.
2022-11-07 22:57:17 INFO     Sanity testing indexManagementDashboards
2022-11-07 22:57:17 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/indexManagementDashboards
2022-11-07 22:57:17 INFO     Executing "git remote add origin https://github.com/opensearch-project/index-management-dashboards-plugin.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/indexManagementDashboards
2022-11-07 22:57:18 INFO     Executing "git fetch --depth 1 origin 46ee7682ef80ae85258ba03c006ea84d85b1d81b" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/indexManagementDashboards
2022-11-07 22:57:19 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/indexManagementDashboards
2022-11-07 22:57:19 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/indexManagementDashboards
2022-11-07 22:57:19 INFO     Checked out https://github.com/opensearch-project/index-management-dashboards-plugin.git@46ee7682ef80ae85258ba03c006ea84d85b1d81b into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/indexManagementDashboards at 46ee7682ef80ae85258ba03c006ea84d85b1d81b
2022-11-07 22:57:19 INFO     Checking https://github.com/opensearch-project/index-management-dashboards-plugin.git at 46ee7682ef80ae85258ba03c006ea84d85b1d81b.
2022-11-07 22:57:19 INFO     Detect indexManagementDashboards with ref 46ee7682ef80ae85258ba03c006ea84d85b1d81b in sha1 format, treat as commit.
2022-11-07 22:57:19 INFO     Found https://github.com/opensearch-project/index-management-dashboards-plugin.git at 46ee7682ef80ae85258ba03c006ea84d85b1d81b.
2022-11-07 22:57:19 INFO     Done.
2022-11-07 22:57:19 INFO     Sanity testing customImportMapDashboards
2022-11-07 22:57:19 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/customImportMapDashboards
2022-11-07 22:57:19 INFO     Executing "git remote add origin https://github.com/opensearch-project/dashboards-maps.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/customImportMapDashboards
2022-11-07 22:57:19 INFO     Executing "git fetch --depth 1 origin 958ee64feb5c30c8ac801b0a369b7a8f0e5540b9" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/customImportMapDashboards
2022-11-07 22:57:20 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/customImportMapDashboards
2022-11-07 22:57:20 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/customImportMapDashboards
2022-11-07 22:57:20 INFO     Checked out https://github.com/opensearch-project/dashboards-maps.git@958ee64feb5c30c8ac801b0a369b7a8f0e5540b9 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/customImportMapDashboards at 958ee64feb5c30c8ac801b0a369b7a8f0e5540b9
2022-11-07 22:57:20 INFO     Checking https://github.com/opensearch-project/dashboards-maps.git at 958ee64feb5c30c8ac801b0a369b7a8f0e5540b9.
2022-11-07 22:57:20 INFO     Detect customImportMapDashboards with ref 958ee64feb5c30c8ac801b0a369b7a8f0e5540b9 in sha1 format, treat as commit.
2022-11-07 22:57:20 INFO     Found https://github.com/opensearch-project/dashboards-maps.git at 958ee64feb5c30c8ac801b0a369b7a8f0e5540b9.
2022-11-07 22:57:20 INFO     Done.
2022-11-07 22:57:20 INFO     Sanity testing securityAnalyticsDashboards
2022-11-07 22:57:20 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityAnalyticsDashboards
2022-11-07 22:57:20 INFO     Executing "git remote add origin https://github.com/opensearch-project/security-analytics-dashboards-plugin" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityAnalyticsDashboards
2022-11-07 22:57:20 INFO     Executing "git fetch --depth 1 origin 026413a38c0197566cef052a8de6e8333489e82c" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityAnalyticsDashboards
2022-11-07 22:57:21 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityAnalyticsDashboards
2022-11-07 22:57:21 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityAnalyticsDashboards
2022-11-07 22:57:21 INFO     Checked out https://github.com/opensearch-project/security-analytics-dashboards-plugin@026413a38c0197566cef052a8de6e8333489e82c into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/securityAnalyticsDashboards at 026413a38c0197566cef052a8de6e8333489e82c
2022-11-07 22:57:21 INFO     Checking https://github.com/opensearch-project/security-analytics-dashboards-plugin at 026413a38c0197566cef052a8de6e8333489e82c.
2022-11-07 22:57:21 INFO     Detect securityAnalyticsDashboards with ref 026413a38c0197566cef052a8de6e8333489e82c in sha1 format, treat as commit.
2022-11-07 22:57:21 INFO     Found https://github.com/opensearch-project/security-analytics-dashboards-plugin at 026413a38c0197566cef052a8de6e8333489e82c.
2022-11-07 22:57:21 INFO     Done.
2022-11-07 22:57:21 INFO     Sanity testing searchRelevanceDashboards
2022-11-07 22:57:21 INFO     Executing "git init" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/searchRelevanceDashboards
2022-11-07 22:57:21 INFO     Executing "git remote add origin https://github.com/opensearch-project/dashboards-search-relevance.git" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/searchRelevanceDashboards
2022-11-07 22:57:21 INFO     Executing "git fetch --depth 1 origin d9f1afa92b98b49f44521478fb2564de2c1d5905" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/searchRelevanceDashboards
2022-11-07 22:57:22 INFO     Executing "git checkout FETCH_HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/searchRelevanceDashboards
2022-11-07 22:57:22 INFO     Executing "git rev-parse HEAD" in /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/searchRelevanceDashboards
2022-11-07 22:57:22 INFO     Checked out https://github.com/opensearch-project/dashboards-search-relevance.git@d9f1afa92b98b49f44521478fb2564de2c1d5905 into /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc/searchRelevanceDashboards at d9f1afa92b98b49f44521478fb2564de2c1d5905
2022-11-07 22:57:22 INFO     Checking https://github.com/opensearch-project/dashboards-search-relevance.git at d9f1afa92b98b49f44521478fb2564de2c1d5905.
2022-11-07 22:57:22 INFO     Detect searchRelevanceDashboards with ref d9f1afa92b98b49f44521478fb2564de2c1d5905 in sha1 format, treat as commit.
2022-11-07 22:57:22 INFO     Found https://github.com/opensearch-project/dashboards-search-relevance.git at d9f1afa92b98b49f44521478fb2564de2c1d5905.
2022-11-07 22:57:22 INFO     Done.
2022-11-07 22:57:22 INFO     Removing /var/folders/y6/mv1vv0d912b1pgg5v378qsvm0000gs/T/tmpqddezzhc
```

**Pull request merged**
