### PR TITLE
Update opensearch-dashboards-2.0.0.yml

### PR DESCRIPTION
**Pull request by praveensameneni**
Add  ~~index-management-dashboards-plugin and~~ alerting-dashboards-plugin

### Description
Added index-management-dashboards and alerting-dashboards for building against 2.0
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — CHANGES_REQUESTED** [review]
Please fix the indentation for yml.

**Comment by abhinavGupta16** [comment]
ci checks need to pass

**Comment by peterzhuamazon** [comment]
Please fix DCO @praveensameneni thanks very much.

**Comment by peterzhuamazon** [comment]
Hi @praveensameneni please consider rebase the entire branch based on main.
Your 1st commit is not being signed.
The DCO check will check every single commit you pushed to the PR so only signing later commits wont fix it.

Thanks.

**Review by gaiksaya — APPROVED** [review]
The PR description says that PR adds Index Management and Alerting both?
Do you want to add index management too? If not please edit the PR description.
Thanks!

**Comment by bbarani** [comment]
> The PR description says that PR adds Index Management and Alerting both? Do you want to add index management too? If not please edit the PR description. Thanks!

@praveensameneni We will merge this PR but can you please address Sayali's comments?

**Pull request merged**
