### PR TITLE
[RFC] use osd test manifest to run integ test

### PR DESCRIPTION
**Pull request by tianleh**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
RFC draft to see how OSD test cluster can be initiated from integ shell.

**Comment by tianleh** [comment]
Identified a few changes needed through current branch.

#1173 

#1172

**Comment by seraphjiang** [comment]
> RFC draft to see how OSD test cluster can be initiated from integ shell.

Is the rfc committed

**Comment by tianleh** [comment]
This pr is not intended to get committed directly. Instead, it is for helping identify related changes to work as incremental progress.

**Comment by tianleh** [comment]
no longer needed due to https://github.com/opensearch-project/opensearch-build/pull/1192

**Pull request closed without merging**
