### PR TITLE
Onboard query-insights in 2.16

### PR DESCRIPTION
**Pull request by deshsidd**
Completing based on the following PR : https://github.com/opensearch-project/opensearch-build/pull/4856

Description
This PR onboards query insights plugin in 2.16.

It bundles query-insights in 2.16 components so that opensearch 2.16 distribution will have query insights by default.
Add query insights in os-increment-plugin-versions and os-release-issues workflows.
Issues Resolved
related to https://github.com/opensearch-project/opensearch-build/issues/4826

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by deshsidd** [comment]
Made the changes as requested by @gaiksaya. Please review @gaiksaya @peterzhuamazon @prudhvigodithi

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Thanks @deshsidd, from the PR I see the query insights plugin has no dependencies (`depends_on`) on other plugins, is this true?

**Review by gaiksaya — APPROVED** [review]

**Comment by deshsidd** [comment]
Can someone re-trigger the whitesource security check please ?

**Comment by deshsidd** [comment]
> Thanks @deshsidd, from the PR I see the query insights plugin has no dependencies (`depends_on`) on other plugins, is this true?

Yes, we have no dependencies as of now. Thanks

**Pull request merged**
