### PR TITLE
insights repos manifest update to 2.1.0

### PR DESCRIPTION
**Pull request by kavithacm**
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>

### Description
Update Insights team repositories’s manifest for version 2.1.0. This includes the following repositories .
1. Observability 
2. Reports 
3. SQL
4. Visualization 

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Hi @kavithacm Can you fix the merge conflict and linting issue?
Thanks!

**Comment by kavithacm** [comment]
> Hi @kavithacm Can you fix the merge conflict and linting issue? Thanks!

yes, done!

**Comment by gaiksaya** [comment]
> > Hi @kavithacm Can you fix the merge conflict and linting issue? Thanks!
> 
> yes, done!

Looks like yaml linter is still throwing an issue.

**Comment by kavithacm** [comment]
> > > Hi @kavithacm Can you fix the merge conflict and linting issue? Thanks!
> > 
> > 
> > yes, done!
> 
> Looks like yaml linter is still throwing an issue.

yeah i'm working on it

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
