### PR TITLE
Add components to 1.3.4 manifest

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Add more components to 1.3.4 manifest

### Issues Resolved
Part of #2205 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zelinh** [comment]
Seems like atomicwrites 1.4.0 is actually removed from PyPi...
https://github.com/untitaker/python-atomicwrites/issues/61

**Review by peterzhuamazon — APPROVED** [review]

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Actually see python issues and yaml lint issues in checks.

**Review by prudhvigodithi — APPROVED** [review]

**Review by peterzhuamazon — DISMISSED** [review]
I dont see Pipefile update here only the lock file.

**Comment by prudhvigodithi** [comment]
@zelinh missing Pipfile entry, please add.
`Pipfile:23:atomicwrites = "*"`

**Comment by gaiksaya** [comment]
Pipfile is "*" which will pull latest available version from PyPi which changed to 1.4.1 now. In future if it increments it will be autoupdated. I think its fine to keep pipfile as it and just change the piplock

**Comment by zelinh** [comment]
> I dont see Pipefile update here only the lock file.

It's already there. 
https://github.com/opensearch-project/opensearch-build/blob/7ec9fd435ff0b7d34d740d6d6ba071e754dd093b/Pipfile#L23

**Comment by zelinh** [comment]
> @zelinh missing Pipfile entry, please add. `Pipfile:23:atomicwrites = "*"`

It's there i didn't change any of it. https://github.com/opensearch-project/opensearch-build/blob/7ec9fd435ff0b7d34d740d6d6ba071e754dd093b/Pipfile#L23

**Comment by peterzhuamazon** [comment]
If we think we dont want to lock versions but rather use * you can just dismiss my block.

**Comment by prudhvigodithi** [comment]
Hey @gaiksaya and @zelinh we are already locking in piplock to `"version": "==1.4.1"`, am I missing something here?
For the new version we still have to re-generating the Pipfile.lock.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by zelinh** [comment]
> Hey @gaiksaya and @zelinh we are already locking in piplock to `"version": "==1.4.1"`, am I missing something here? For the new version we still have to re-generating the Pipfile.lock.

Yes if there is a new version of this. But seems like this package will be deprecated.

**Pull request merged**
