### PR TITLE
Including DCO with automated manifest updates

### PR DESCRIPTION
**Pull request by peternied**
### Description
Including DCO with automated manifest updates 

### Issues Resolved
- Can be used to avoid a rebase like was done in https://github.com/opensearch-project/opensearch-build/pull/1515
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — COMMENTED** [review]
Do we have to include a actual human user name?
We can include the signature from the bot account.
Thanks.

**Comment by peternied** [comment]
> Do we have to include a actual human user name? We can include the signature from the bot account. Thanks.

@peterzhuamazon / @abhinavGupta16 Could you provide the name and email you want this to?

**Comment by peterzhuamazon** [comment]
> > Do we have to include a actual human user name? We can include the signature from the bot account. Thanks.
> 
> @peterzhuamazon / @abhinavGupta16 Could you provide the name and email you want this changed to?

Can you try to see if this runs?

opensearch-ci-bot <opensearch-infra@amazon.com>

**Review by gaiksaya — APPROVED** [review]

**Review by abhinavGupta16 — APPROVED** [review]
I like this change. Would it also work for commits made via suggestions in a PR?

**Pull request merged**
