### PR TITLE
Add OSD repo to the manifest for the next developer iteration

### PR DESCRIPTION
**Pull request by noCharger**
Signed-off-by: Louis Chu <clingzhi@amazon.com>

### Description
Add OSD repo to the manifest for the next developer iteration

Ref PR: https://github.com/opensearch-project/opensearch-build/pull/2459

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2308

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Looks like DCO check is failing @noCharger

**Comment by gaiksaya** [comment]
Hi @noCharger We have workflow that auto detects the version increment for core repos (OS and OSD). This is where is created the PR: https://github.com/opensearch-project/opensearch-build/pull/2599
Are you okay with going ahead with that one since this one has some checks failing?

**Comment by gaiksaya** [comment]
Closing this in favor of #2599

**Comment by noCharger** [comment]
> Hi @noCharger We have workflow that auto detects the version increment for core repos (OS and OSD). This is where is created the PR: #2599 Are you okay with going ahead with that one since this one has some checks failing?

sure, thanks for the info!

**Pull request closed without merging**
