### PR TITLE
Bump jenkins library to 1.0.3

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Bump jenkins shared library version to 1.0.3 and remove all per JenkinsFile shared library cloning as it is already set up by `super.setup()`

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
The CI passed in my fork https://github.com/gaiksaya/opensearch-build/actions/runs/3268165206

**Comment by gaiksaya** [comment]
Some observations where groovy tests are failing randomly:
Few differences where ubuntu
```
Fail: 2022-10-17T21:07:09.6665844Z Image: ubuntu-20.04
2022-10-17T21:07:09.6666175Z Version: 20221002.2
Pass: 2022-10-17T22:18:59.9189939Z Image: ubuntu-20.04
2022-10-17T22:18:59.9190331Z Version: 20221012.1
```
Git version:
```
Fail: 2022-10-17T21:07:20.5185911Z git version 2.37.3
Pass: 2022-10-17T22:19:08.2971354Z git version 2.38.0
```
Pushed a random commit to see if things are still unstable. It passed in above CI and failed in my fork with same specifications as above.

**Comment by gaiksaya** [comment]
Filed a bug with GHA https://github.com/actions/runner-images/issues/6422

**Comment by prudhvigodithi** [comment]
Hey @gaiksaya just this PR delete entire `var/` folder ?

**Comment by gaiksaya** [comment]
> Hey @gaiksaya just this PR delete entire `var/` folder ?

Yes it just contained readme which is not useful anymore for this repo

**Pull request merged**
