### PR TITLE
Added neural-search to 2.12 manifest

### PR DESCRIPTION
**Pull request by martin-gaievski**
### Description
Added neural-search to 2.12 manifest

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — COMMENTED** [review]
Hey @martin-gaievski
This file you are changing is the template that we used. 
Could you change on this manifest which would be used for build? Thanks. https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.12.0/opensearch-2.12.0.yml

**Comment by martin-gaievski** [comment]
thank you @zelinh I've moved changes to correct file, please check

**Review by zelinh — APPROVED** [review]

**Review by zelinh — CHANGES_REQUESTED** [review]
Checks failed because of incompatible gradle and jdk version.
Since we recently upgraded to JDK21/gradle 8.5,  https://github.com/opensearch-project/OpenSearch/pull/11003, you should also upgrade and test your plugin to see if it supports that. 
Blocking this PR for now. 
Thanks.

**Review by zelinh — APPROVED** [review]
LGTM

**Pull request merged**
