### PR TITLE
Add the alerting release 1.2

### PR DESCRIPTION
**Pull request by rishabhmaurya**
### Description
Adding alerting release 1.2 to manifest for opensearch-build
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
CI fixed in https://github.com/opensearch-project/opensearch-build/pull/890, please rebase when that's merged.

**Review by gaiksaya — APPROVED** [review]
Please fix the DCO and CI
Thanks!

**Comment by kavilla** [comment]
Can you rebase and sign the commit?

**Comment by gaiksaya** [comment]
Hi @rishabhmaurya can we close this if not required anymore?

**Comment by peternied** [comment]
I am closing out this PR, alerting has already moved to `1.2` with https://github.com/opensearch-project/opensearch-build/pull/915

**Pull request closed without merging**
