### PR TITLE
Update the 1.3.0 input manifest to use 1.3.0 tags

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Update to use tags in the 1.3.0 input manifest.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kavilla — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Looks like there are failing tests: https://github.com/opensearch-project/opensearch-build/runs/5593066232?check_suite_focus=true

**Comment by peterzhuamazon** [comment]
> Looks like there are failing tests: https://github.com/opensearch-project/opensearch-build/runs/5593066232?check_suite_focus=true

We recently updated lucene in 2.0.0 to 9.1.0
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.apache.lucene:lucene-core:9.1.0-snapshot-ea989fe8f30.
```

https://github.com/opensearch-project/OpenSearch/commit/05a58192433f6e007ade61b4b4f21d0f068d50e0

Seems like the 2.0.0 workflow cannot find lucene on any of the repos.
Not related to this specific PR.

**Comment by zelinh** [comment]
Going through the CI check, it seems like the failure is 
`Could not find org.apache.lucene:lucene-core:9.1.0-snapshot-ea989fe8f30.`
This might be related to the PR here. https://github.com/opensearch-project/OpenSearch/pull/2487

**Comment by gaiksaya** [comment]
Tests are failing in main branch too: https://github.com/opensearch-project/opensearch-build/commits/main

**Comment by peterzhuamazon** [comment]
We merge this as the error is not due to PR but https://github.com/opensearch-project/OpenSearch/issues/2500

**Pull request merged**
