### PR TITLE
Add query-insights to test manifest

### PR DESCRIPTION
**Pull request by deshsidd**
### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — APPROVED** [review]

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
LGTM, adding @peterzhuamazon @gaiksaya.

**Review by gaiksaya — APPROVED** [review]
@deshsidd No additional cluster configurations are needed for testing right?

**Comment by deshsidd** [comment]
> @deshsidd No additional cluster configurations are needed for testing right?

Should not be needed, only the configs to enable and configure the features

**Comment by peterzhuamazon** [comment]
> > @deshsidd No additional cluster configurations are needed for testing right?
> 
> Should not be needed, only the configs to enable and configure the features

What configs are those and are they enable or disable by default?

Thanks.

**Pull request merged**
