### PR TITLE
Support automatic merging of new manifest files

### PR DESCRIPTION
**Pull request by peternied**
### Description
Will allow for PRs such as https://github.com/opensearch-project/opensearch-build/pull/4134 to be merged without user intervention

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Hi @peternied How is this expected to work? Looks like above linked PR is still sitting in approved state. 
Thanks!

**Comment by peternied** [comment]
@gaiksaya That PR will be merge only if changes are pushed to trigger a fresh workflows runs (workflow triggers aren't affected by retries). If you push a small change it should be able to run this new workflow and merge.

**Comment by peternied** [comment]
Or if you close it will a new one be created? That might be another way to test 'hands-free'

**Comment by gaiksaya** [comment]
> @gaiksaya That PR will be merge only if changes are pushed to trigger a fresh workflows runs (workflow triggers aren't affected by retries). If you push a small change it should be able to run this new workflow and merge.

Triggered a fresh workflow updating the manifest files. Still no change.

**Comment by gaiksaya** [comment]
I see the error:
```
 Error: Merge commits are not allowed on this repository.
```

**Comment by peternied** [comment]
Thanks, I filed [1] and then created a new release [2].  I'll create a PR to update the version where this works properly.

- [1] https://github.com/peternied/discerning-merger/issues/2
- [2] https://github.com/peternied/discerning-merger/releases/tag/v3

**Pull request merged**
