### PR TITLE
Update 2.0.0 manifest to use 2.0 opensearch core branch

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Update 2.0.0 manifest to use 2.0 opensearch core branch
 
### Issues Resolved
Part of #1624
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
yaml lint is not happy :(

**Review by zelinh — COMMENTED** [review]
Please change it to single quote as we required.

**Review by zelinh — APPROVED** [review]
Thanks!

**Comment by zelinh** [comment]
`system.properties_file.UnexpectedKeyValueError: Expected to have version='2.0.0.0-SNAPSHOT', but was '2.0.0.0-alpha1-SNAPSHOT'.` Seems like we need to update our CI check to support qualifier :(

**Comment by peterzhuamazon** [comment]
Same as yesterday merge this as ci does not support qualifier yet.

**Pull request merged**
