### PR TITLE
Add performance test related x64 docker file and images

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add performance test related x64 docker file and images

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/2211

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@kotwanikunal Let me know if any package is missing.
Thanks.

**Comment by kotwanikunal** [comment]
> @kotwanikunal Let me know if any package is missing. Thanks.

The node/nvm/npm instructions are missing.

**Comment by kotwanikunal** [comment]
Thanks for fixing this quickly!

**Review by kotwanikunal — APPROVED** [review]

**Review by bbarani — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Images: https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&name=ci-runner-centos7-performance-test-v1

**Pull request merged**
