### PR TITLE
Add shebang to build.py

### PR DESCRIPTION
**Pull request by camerski**
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Also needed in `test.py`.

**Comment by camerski** [comment]
> Also needed in `test.py`.

Test.py needs some other changes, too, so I was going to roll those together.

**Comment by camerski** [comment]
> I actually have this as part of https://github.com/opensearch-project/opensearch-build/pull/163/files which is the first time we need this, if you just want to close this, or merge, up to you.

Whichever change gets approved first is fine with me :) I've approved #163.

**Comment by dblock** [comment]
Let's do this in #163 to group related changes.

**Pull request closed without merging**
