### PR TITLE
Update `docker-compose.yml`.

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
Signed-off-by: Yury-Fridlyand <yuryf@bitquilltech.com>

### Description
The proposed changes contain updated `docker-compose.yml` which doesn't use obsolete OpenSearch settings (see https://github.com/opensearch-project/OpenSearch/pull/2463).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @Yury-Fridlyand thanks for the PR, this breaks next 1.3.x series, should be have a prefix folders? or a new docker-compose file that distinguishes 1.3.x and above 2.x? @peterzhu1992 @gaiksaya @bbarani @dblock

**Comment by peterzhuamazon** [comment]
> Hey @Yury-Fridlyand thanks for the PR, this breaks next 1.3.x series, should be have a prefix folders? or a new docker-compose file that distinguishes 1.3.x and above 2.x? @peterzhu1992 @gaiksaya @bbarani @dblock

We can definitely separated to different folder.
It wont really broke us as we didnt use this file actively, just reference.
The one on the website and documentation is more of an issue.

I propose rename this as docker-compose-2.x.yml, and restore the old one as docker-compose-1.x.yml.

The reason being the original change by @tlfeng was for 2.0, so assuming this change is already in every 2.x.

Thanks.

**Comment by Yury-Fridlyand** [comment]
Done. I can't find any references to this file. Please, check that no script nor readme require an update.

Thanks!

**Comment by prudhvigodithi** [comment]
LGTM! @dblock @peterzhuamazon @gaiksaya, can you review as well?
Thank you

**Review by prudhvigodithi — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> Done. I can't find any references to this file. Please, check that no script nor readme require an update.
> 
> Thanks!

Hi @Yury-Fridlyand,

My wording might be a bit off.
When I say reference I meant to say that the opensearch.org website/documentation ones are copied from here.
So this is where the file first being created. 

Your change is well and done in this repo now.
Thanks very much.

**Comment by peterzhuamazon** [comment]
> LGTM! @dblock @peterzhuamazon @gaiksaya, can you review as well? Thank you

I will keep this open a bit until documentation team confirm this is confirmed valid, since I have not tested this yet.
If @tlfeng can give his opinion it would be great.

Thanks.

**Comment by tlfeng** [comment]
@peterzhuamazon I confirm that the cluster setting name `cluster.initial_master_nodes` is deprecated in version 2.0, and the alternative name is `cluster.initial_cluster_manager_nodes`, which is introduced in the commit https://github.com/opensearch-project/OpenSearch/commit/19eadb46ba80df1750402a3faad55114823087f2.
The old setting name `cluster.initial_master_nodes` is planned to be removed in version 3.0, and the new setting name `cluster.initial_cluster_manager_nodes` has been available since version 2.0 .

Some of our plugins have been using the new name in their CI for testing (https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/2.1.0.0/.github/configurations/docker-compose.yml), so I think the setting name change in this PR will work.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I confirm that the cluster setting name `cluster.initial_master_nodes` is deprecated in version 2.0, and the alternative name is `cluster.initial_cluster_manager_nodes`, which is introduced in the commit [opensearch-project/OpenSearch@19eadb4](https://github.com/opensearch-project/OpenSearch/commit/19eadb46ba80df1750402a3faad55114823087f2). The old setting name `cluster.initial_master_nodes` is planned to be removed in version 3.0, and the new setting name `cluster.initial_cluster_manager_nodes` is available in version 2.0 and above.
> 
> Some of our plugins have been using the new name in their CI for testing (https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/2.1.0.0/.github/configurations/docker-compose.yml), so I think the setting name change in this PR will work.

Thanks @tlfeng.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @Yury-Fridlyand we will leave this PR unmerged until project website and documentation maintainers merged on their side.

Approved now.

**Pull request merged**
