### PR TITLE
Fixing import order

### PR DESCRIPTION
**Pull request by ankitkala**
Signed-off-by: Ankit Kala <ankikala@amazon.com>

### Description
Fixing import order
 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Lots more style guide violations to fix in CI, how is this passing before? :)

**Comment by gaiksaya** [comment]
Where the tests skipped before? https://github.com/opensearch-project/opensearch-build/pull/1907 How?

**Comment by ankitkala** [comment]
> 

Not sure why these checks didn't run when PR was raised.

**Comment by prudhvigodithi** [comment]
I get the following error
```
ERROR: /Users/pgodithi/git/opensearch-build/tests/tests_test_workflow/test_perf_workflow/perf_test/test_perf_test_runner_opensearch_plugins.py Imports are incorrectly sorted and/or formatted.
ERROR: /Users/pgodithi/git/opensearch-build/src/test_workflow/perf_test/perf_test_cluster.py Imports are incorrectly sorted and/or formatted.
```
After I fetched from main, now looks like other PR's python checks are failing, is this something to do with checks not being run ?

**Comment by gaiksaya** [comment]
> I get the following error
> 
> ```
> ERROR: /Users/pgodithi/git/opensearch-build/tests/tests_test_workflow/test_perf_workflow/perf_test/test_perf_test_runner_opensearch_plugins.py Imports are incorrectly sorted and/or formatted.
> ERROR: /Users/pgodithi/git/opensearch-build/src/test_workflow/perf_test/perf_test_cluster.py Imports are incorrectly sorted and/or formatted.
> ```
> 
> After I have done fetch upstream from main, now looks like other PR's python checks are failing, is this something to do with checks not being run ?

Yes once this PR is merged the errors should be fixed. Looks like some issue with GHA. They were queued up for really long time even now.

**Review by gaiksaya — APPROVED** [review]
Looks like all tests ran and passed too. Thanks!

**Pull request merged**
