### PR TITLE
Support JDK-20 builds on Jenkins

### PR DESCRIPTION
**Pull request by reta**
### Description
Support JDK-20 builds on Jenkins

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-build/issues/3425

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
Tested Docker images, samples below:

```
[opensearch@38cd5558bbb2 ~]$ export                                                            
declare -x GEM_HOME="/usr/share/opensearch/.gem"                                               
declare -x GEM_PATH="/usr/share/opensearch/.gem"                                               
declare -x HISTCONTROL="ignoredups"                                                            
declare -x HISTSIZE="1000"                                                                                                                                                                    
declare -x HOME="/usr/share/opensearch"                                                        
declare -x HOSTNAME="38cd5558bbb2"                                                             
declare -x JAVA11_HOME="/opt/java/openjdk-11"                                                  
declare -x JAVA17_HOME="/opt/java/openjdk-17"                                                  
declare -x JAVA19_HOME="/opt/java/openjdk-19"                                                  
declare -x JAVA20_HOME="/opt/java/openjdk-20"                                                  
declare -x JAVA8_HOME="/opt/java/openjdk-8"                                                    
declare -x JAVA_HOME="/opt/java/openjdk-20
... 
```

```
[opensearch@38cd5558bbb2 ~]$  /opt/java/openjdk-20/bin/java -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode, sharing)
```

**Comment by reta** [comment]
@peterzhuamazon may I ask you to take a look please?

**Comment by peterzhuamazon** [comment]
@reta I add some comment on the issue, this can be hold for a bit and go in the same time as the ci repo changes.

**Comment by peterzhuamazon** [comment]
Please add manifest changes to 3.0.0 OS part with JDK20.

**Comment by peterzhuamazon** [comment]
This needs to go in once 3.0.0 officially switch to JDK20.

**Comment by peterzhuamazon** [comment]
Need rebuild:
./current/test.rockylinux8.systemd-base.x64.arm64.dockerfile
./current/build.centos7.opensearch.x64.arm64.dockerfile
./current/release.centos.clients.x64.arm64.dockerfile
./current/build.ubuntu2004.opensearch.x64.arm64.dockerfile
./current/test.ubuntu2004.systemd-base.x64.arm64.dockerfile
./current/build.rockylinux8.opensearch.x64.arm64.dockerfile

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-build/3394/console
https://build.ci.opensearch.org/job/docker-build/3396/console
https://build.ci.opensearch.org/job/docker-build/3397/console
https://build.ci.opensearch.org/job/docker-build/3398/console
https://build.ci.opensearch.org/job/docker-build/3399/console
https://build.ci.opensearch.org/job/docker-build/3400/console

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-build/3401/console
https://build.ci.opensearch.org/job/docker-build/3402/console
https://build.ci.opensearch.org/job/docker-build/3403/console
https://build.ci.opensearch.org/job/docker-build/3404/console
https://build.ci.opensearch.org/job/docker-build/3405/console
https://build.ci.opensearch.org/job/docker-build/3406/console

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-copy/484/console
https://build.ci.opensearch.org/job/docker-copy/485/console
https://build.ci.opensearch.org/job/docker-copy/486/console
https://build.ci.opensearch.org/job/docker-copy/487/console

**Pull request merged**
