### PR TITLE
Add tests manifests for 1.3.7 and 2.4.1

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Add tests manifests

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
On 1.3.7 I think we should have more test available on OS right now?
https://github.com/opensearch-project/opensearch-build/issues/58

Hopefully I didnt miss anything right now.

Thanks.

**Comment by gaiksaya** [comment]
Yes what about to ask, the missing tests on 1.3.7 are below:
```
cross-cluster-replication
security
```

Should I add these? Not sure if they have backported the tests to 1.3.x series.

**Review by rishabh6788 — APPROVED** [review]

**Comment by peternied** [comment]
> Not sure if they have backported the tests to 1.3.x series.

@DarshitChanpura Could you see about backporting these tests?

**Comment by peterzhuamazon** [comment]
> Yes what about to ask, the missing tests on 1.3.7 are below:
> 
> ```
> cross-cluster-replication
> security
> ```
> 
> notifications, neural-search, geospatial, security-analytics do not exists for 1.3.7 so they are out.
> 
> Should I add these? Not sure if they have backported the tests to 1.3.x series. Would like input from @opensearch-project/security and @ankitkala

Yes please, those tests were added at a later time.
Thanks.

**Comment by DarshitChanpura** [comment]
> > Not sure if they have backported the tests to 1.3.x series.
> 
> @DarshitChanpura Could you see about backporting these tests?

The tests don't exist in 1.3.x branch, but if the need is to backport them I can create a PR, and later create a PR against OS-build 1.3.7 manifest to add security

**Comment by gaiksaya** [comment]
> > > Not sure if they have backported the tests to 1.3.x series.
> > 
> > 
> > @DarshitChanpura Could you see about backporting these tests?
> 
> The tests don't exist in 1.3.x branch, but if the need is to backport them I can create a PR, and later create a PR against OS-build 1.3.7 manifest to add security

I don't think that will work as we will be replacing the branch name in the manifest with commit_ids used for release candidate so your changes won't be accounted for. Code freeze :D

**Comment by ankitkala** [comment]
Hey @gaiksaya we've not backported the tests fro CCR to older branches so its not available on `1.3.x`

**Pull request merged**
