### PR TITLE
Use 1.1 of Asynchronous Search plugin for Release 1.1.0

### PR DESCRIPTION
**Pull request by eirsep**
### Description
Uses 1.1 of Asynchronous Search plugin for Release 1.1.0
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Please update the PR description. Thanks!

**Review by dblock — CHANGES_REQUESTED** [review]
The 1.1 branch doesn't include CI fixes or removal of integtest.sh.

Screen Shot 2021-09-24 at 2 12 05 PM

**Comment by eirsep** [comment]
> The 1.1 branch doesn't include CI fixes or removal of integtest.sh.

https://github.com/opensearch-project/asynchronous-search/pull/44

**Review by dblock — DISMISSED** [review]

**Comment by gaiksaya** [comment]
Still do not see the `--signoff` commits. @eirsep Can you please take care of that?
[More details](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin)
Thanks!

**Review by dblock — APPROVED** [review]

**Pull request merged**
