### PR TITLE
Add more version bump to github workflow SA NS

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add more version bump to github workflow SA NS

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]
This addition of new version maybe can be part of manifest workflow. Can go in same PR.

The workflow that creates manifest https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/manifests.yml we can add one more step to add same branch version to the workflow. Same Pr you created just now but automated way

**Comment by peterzhuamazon** [comment]
> This addition of new version maybe can be part of manifest workflow. Can go in same PR.
> 
> The workflow that creates manifest https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/manifests.yml we can add one more step to add same branch version to the workflow.

Talked offline, will review the code in a new PR and add suggested logic.

Thanks.

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon @gaiksaya the addition of new version logic is already part of the manifest workflow, here is the [sample PR](https://github.com/opensearch-project/opensearch-build/pull/2628/files) that adds the version to the `.github/workflows/increment-plugin-versions.yml` file, we dont need to add it manually again. However at some point just like we move the old manifests to the legacy manifest folder, we need to remove the old versions from the `increment-plugin-versions.yml`.

**Comment by peterzhuamazon** [comment]
> Hey @peterzhuamazon @gaiksaya the addition of new version logic is already part of the manifest workflow, here is the [sample PR](https://github.com/opensearch-project/opensearch-build/pull/2628/files) that adds the version to the `.github/workflows/increment-plugin-versions.yml` file, we dont need to add it manually again. However at some point just like we move the old manifests to the legacy manifest folder, we need to remove the old versions from the `increment-plugin-versions.yml`.

Yeah these are older versions thus they are not showing by the autobump. Expected.

**Pull request merged**
