### PR TITLE
Add default version of jenkins build library

### PR DESCRIPTION
**Pull request by gaiksaya**
### Description
This change imports the default version for jenkins build libraries from a single file. Any one who wishes to use otherwise example a previous version or main from the [upstream library](https://github.com/opensearch-project/opensearch-build-libraries) can specific the same in the respective JenkinsFile.
Also the tests base library `BuildPipelineTest` uses the default library. Hence, removed it from all test files and it is already imported as a part of `super.setUp` in all tests files. If any test wants to use other version of the lib than default, same can be specified in the test file as below
```
        helper.registerSharedLibrary(
            library().name('jenkins')
                .defaultVersion("2.0.0")
                .allowOverride(true)
                .implicit(true)
                .targetPath('vars')
                .retriever(gitSource('https://github.com/opensearch-project/opensearch-build-libraries.git'))
                .build()
            )
```

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
The tests are passing in my local.
However on git, looks like the files says its is expecting this line but its not present for test: 
`TestCCRPerfTest > testCCRPerfTestScript_Pipeline FAILED`
```
Messages.add(test_stage, https://ci.opensearch.org/ci/dbc/test://artifact.url/1.3.0/perf-test/linux/x64/tar/test-results/)
```

**Comment by jordarlu** [comment]
Hi, @gaiksaya , Thank you for the hard work!
It runs well in my local too..  but I still cannot figure out why the "new Messages(this).add("${STAGE_NAME}", "${baseUrl}/test-results/")" in uploadTestResults.groovy is not executed when the CI is running the test..
Is it possible we do the following ?

1. Adding printCallStack() after Line: 75, and we can make sure if the CI does or not run the "new Messages(this).add("${STAGE_NAME}", "${baseUrl}/test-results/")" in uploadTestResults.groovy.

2. Perhaps there is a cache of 'outdated' uploadTestResults.groovy in CI?  can we reset or reboot the CI?

I think I can create a draft PR to try the #1 above...

thanks!

**Comment by jordarlu** [comment]
Hi, @gaiksaya ,, still cannot explain what happened on CI test, but it runs well now after adding printCallStack() somehow ( pls refer to result of draft #2745 which I don't intend to merge but validating purpose only ).. 
In order to move forward, do you want to try the same at here, PR #2741 , and give it another shot? 

Thanks,

**Comment by gaiksaya** [comment]
I ran CI 3-4 times and it passed now. Not sure if the issue is with GitHub runners or GH pulling the right code but yeah this was already passing on my local. 
Please review @opensearch-project/engineering-effectiveness 
Thanks!

**Comment by peterzhuamazon** [comment]
@gaiksaya seems like the groovy on github is passing now?

**Review by jordarlu — APPROVED** [review]
Thank you, @gaiksaya .. upon other's to review, it looks good to me. thanks!

**Comment by gaiksaya** [comment]
> @gaiksaya seems like the groovy on github is passing now?

Yes :) No idea what is happening. Might be issue with Github, had to run the same workflow 3-4 times.

**Comment by gaiksaya** [comment]
Hi @dblock Do you have any idea what might be happening here? These tests pass locally but looks like not on Git.

**Comment by dblock** [comment]
@gaiksaya I am seeing this in the logs:

```
2022-10-17T18:56:52.7126337Z > Task :jacocoTestReport FAILED
2022-10-17T18:56:52.7127074Z :jacocoTestReport (Thread[Execution worker for ':',5,main]) completed. Took 2.596 secs.
```

Did you try to run this locally?

**Comment by gaiksaya** [comment]
Yes See the issue https://github.com/opensearch-project/opensearch-build/issues/2751 for details. Also I am working on another fix. The way libraries are set up for 1.0.3 are not right. PR should be up by EOD.

**Pull request merged**
