### PR TITLE
[Resume] Improve ownership and permissions of files in OpenSearch/Dashboards deb and rpm packages

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
[Resume] Improve ownership and permissions of files in OpenSearch/Dashboards deb and rpm packages
Originally commit by @smortex on #3898 #3952 #4038.

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/3815#issuecomment-1726530106

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Thinking if we need to make some adjustment so that 1.x is not picking this change, but 2.x and higher will take this change.

cc: @smortex @bbarani

**Comment by peterzhuamazon** [comment]
Before:
drwxr-xr-x   9 opensearch opensearch  4096 Mar 13 21:22 opensearch/

After:
drwxr-x---   9 opensearch opensearch  4096 Mar 13 21:23 opensearch/

**Comment by peterzhuamazon** [comment]
Start more testing:
```
PermissionError: [Errno 13] Permission denied: '/etc/opensearch/opensearch.yml'
```

**Comment by peterzhuamazon** [comment]
Will send the changes of the integTest in another PR:
```
2024-03-14 20:39:36 INFO     | geospatial           | with-security        | PASS  |
2024-03-14 20:39:36 INFO     | geospatial           | without-security     | PASS  |
```

**Review by prudhvigodithi — APPROVED** [review]

**Comment by roock** [comment]
Not sure this is the right place to add this, but please note that the ownership change isn't fully reflected when upgrading opensearch package. ownership for files are correctly set to root, but directory are still owned by opensearch.

Our system: Debian 12, installation via apt package.

Upgrade from 2.12:
```
$ ls -la
total 324
drwxr-xr-x  8 opensearch opensearch   4096 16. Apr 16:24 .
drwxr-xr-x 96 root       root         4096 28. Mär 13:46 ..
drwxr-xr-x  3 opensearch opensearch   4096 12. Apr 11:22 bin
lrwxrwxrwx  1 opensearch opensearch     19 14. Okt 2022  data -> /var/lib/opensearch
drwxr-xr-x  9 opensearch opensearch   4096 12. Apr 11:22 jdk
drwxr-xr-x  3 opensearch opensearch  12288 12. Apr 11:22 lib
lrwxrwxrwx  1 opensearch opensearch     19 14. Okt 2022  logs -> /var/log/opensearch
-rw-r--r--  1 root       root         8610 14. Okt 2022  manifest.yml
drwxr-xr-x 22 opensearch opensearch   4096 12. Apr 11:22 modules
-rw-r--r--  1 root       root       273938 14. Okt 2022  NOTICE.txt
drwxr-xr-x  5 opensearch opensearch   4096 28. Mär 13:46 performance-analyzer-rca
drwxr-xr-x 24 opensearch opensearch   4096 12. Apr 14:13 plugins
-rw-r--r--  1 root       root         3699 14. Okt 2022  README.md
```

New installation with 2.13

```
$ ls -al /usr/share/opensearch/
total 316
drwxr-xr-x  8 root root   4096 25. Apr 10:38 .
drwxr-xr-x 94 root root   4096 25. Apr 10:38 ..
drwxr-xr-x  3 root root   4096 25. Apr 10:38 bin
lrwxrwxrwx  1 root root     19 14. Okt 2022  data -> /var/lib/opensearch
drwxr-xr-x  9 root root   4096 25. Apr 10:38 jdk
drwxr-xr-x  3 root root   4096 25. Apr 10:38 lib
lrwxrwxrwx  1 root root     19 14. Okt 2022  logs -> /var/log/opensearch
-rw-r--r--  1 root root   8610 14. Okt 2022  manifest.yml
drwxr-xr-x 22 root root   4096 25. Apr 10:38 modules
-rw-r--r--  1 root root 273938 14. Okt 2022  NOTICE.txt
drwxr-xr-x  5 root root   4096 25. Apr 10:38 performance-analyzer-rca
drwxr-xr-x 23 root root   4096 25. Apr 10:38 plugins
-rw-r--r--  1 root root   3699 14. Okt 2022  README.md
```

**Pull request merged**
