### PR TITLE
Add windows build to 1.3.7 security

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add windows build to 137 security

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/2742

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Just security? What about others?

**Comment by peterzhuamazon** [comment]
> Just security? What about others?

Others are still working to support windows, therefore we only add security and core for now in Windows.

**Review by peternied — APPROVED** [review]
Lets merge this have a build and fast follow with all remaining plugins to flush out those issues - What do you think?

**Comment by CEHENKLE** [comment]
I think I'd rather know who's broken.  We can't fix what we don't know.

**Comment by CEHENKLE** [comment]
What if we add Security in today, and all plugins on Monday?

**Pull request merged**
