### PR TITLE
Resolve securityDashboards not correctly removed on DEB/RPM

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Resolve securityDashboards not correctly removed on DEB/RPM.
If `sudo` is not applied to DEB/RPM plugin removal, the run will still goes to success and return 0, despite the plugin directory is still there.

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/3331

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by prudhvigodithi — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Related issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4053

**Comment by peterzhuamazon** [comment]
After this patch:
```
2023-05-17 00:27:24 INFO     Removing /tmp/tmp801ov6cw
2023-05-17 00:27:24 INFO     | queryWorkbenchDashboards | with-security        | PASS  |
2023-05-17 00:27:24 INFO     | queryWorkbenchDashboards | without-security     | PASS  |
```

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-build/3375/console
https://build.ci.opensearch.org/job/docker-build/3376/console

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-copy/468/console
https://build.ci.opensearch.org/job/docker-copy/469/console

**Comment by gaiksaya** [comment]
Copy to ECR too?

**Pull request merged**
