### PR TITLE
Add rockylinux8 build related image for building rpm

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Add rockylinux8 build related image for building rpm.

### Issues Resolved
Follow up #2120 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — APPROVED** [review]

**Comment by tianleh** [comment]
Non blocking: if including `rpm` in the name, it will be much easier to help users understand.

**Review by tianleh — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> Non blocking: if including `rpm` in the name, it will be much easier to help users understand.

We are not including rpm in the name because later on once k-NN move from native code to java code, this runner will straight away replace the centos7 build runner.

Thanks.

**Comment by peterzhuamazon** [comment]
Waiting for docker build to be completed.

**Comment by peterzhuamazon** [comment]
https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&name=ci-runner-rockylinux8-opensearch-build-v2

**Pull request merged**
