### PR TITLE
Replace alpha1 with rc1.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Replace alpha1 with rc1. We're doing away with alpha.
  
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
This is a big change means a lot of the repos needs to change their ci as well.
Will block this until we clear up the confusion and final decision.

Thanks.

**Comment by bbarani** [comment]
> This is a big change means a lot of the repos needs to change their ci as well. Will block this until we clear up the confusion and final decision.
> 
> Thanks.

We will merge this PR once we have the working build with alpha qualifier.

**Comment by peterzhuamazon** [comment]
This is only for the build repo manifest, as all other plugin repos all need to change their default to rc1.

**Comment by dblock** [comment]
> This is only for the build repo manifest, as all other plugin repos all need to change their default to rc1.

Once this is merged, the `rc1` value will be passed through to plugin builds and used via `-Dopensearch...` options. It will produce a -SNAPSHOT build of OpenSearch-min which then can be used to update the plugin CI. I will take care of it.

**Comment by peterzhuamazon** [comment]
> > This is only for the build repo manifest, as all other plugin repos all need to change their default to rc1.
> 
> Once this is merged, the `rc1` value will be passed through to plugin builds and used via `-Dopensearch...` options. It will produce a -SNAPSHOT build of OpenSearch-min which then can be used to update the plugin CI. I will take care of it.

So just to confirm you will send PR to all the plugin repos to change alpha1 to rc1 after build success, right?
Thanks.

**Comment by dblock** [comment]
> > > This is only for the build repo manifest, as all other plugin repos all need to change their default to rc1.
> > 
> > 
> > Once this is merged, the `rc1` value will be passed through to plugin builds and used via `-Dopensearch...` options. It will produce a -SNAPSHOT build of OpenSearch-min which then can be used to update the plugin CI. I will take care of it.
> 
> So just to confirm you will send PR to all the plugin repos to change alpha1 to rc1 after build success, right? Thanks.

Yes, that's what I am saying.

**Comment by dblock** [comment]
I saw @kavilla also made this change for OSD in https://github.com/opensearch-project/opensearch-build/pull/1949. Do you want me to update this to just do OpenSearch?

**Comment by peterzhuamazon** [comment]
> I saw @kavilla also made this change for OSD in #1949. Do you want me to update this to just do OpenSearch?

We will fix the alpha1 build to be green before switch to rc1.

**Comment by dblock** [comment]
@peterzhuamazon We have to merge this and ensure at least 1 successful RC1 SNAPSHOT build before we go PR changes in all plugins, otherwise their CIs will start failing because there's no opensearch-min-SNAPSHOT.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
@dblock I approve.

**Review by kavilla — APPROVED** [review]
Surprise no conflict but shouldn't be a big deal.

Can we get this merged in otherwise OpenSearch Dashboards sanity tests will fail.

**Review by tianleh — APPROVED** [review]

**Pull request merged**
