### PR TITLE
Update 2.2.0 to run once in 1hr to detect failures early

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Update 2.2.0 to run once in 1hr to detect failures early

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zelinh** [comment]
I think we change to once a day on purpose because of overwhelming build message. Release owner can always trigger the build manually whenever we think it's necessary.

**Review by zelinh — COMMENTED** [review]
I think we change to once a day on purpose because of overwhelming build message. Release owner can always trigger the build manually whenever we think it's necessary.

**Comment by prudhvigodithi** [comment]
> I think we change to once a day on purpose because of overwhelming build message. Release owner can always trigger the build manually whenever we think it's necessary.

Thanks @zelinh, thoughts @peterzhuamazon @bbarani ?

**Comment by prudhvigodithi** [comment]
Closing this PR in the interest of https://github.com/opensearch-project/opensearch-build/pull/2408

**Pull request closed without merging**
