### PR TITLE
Update opensearch-2.8.0.yml for PA

### PR DESCRIPTION
**Pull request by khushbr**
### Description
Update opensearch-2.8.0.yml for PA

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by prudhvigodithi — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Looks like PA has dependencies issues: https://github.com/opensearch-project/opensearch-build/actions/runs/5007635559/jobs/8974506616?pr=3528 with jackson lib.

**Comment by khushbr** [comment]
@prudhvigodithi @gaiksaya 
The 2.8.0 check is failing with following [error](https://github.com/opensearch-project/opensearch-build/actions/runs/5007635559/jobs/8974506616?pr=3528#step:6:1366):

```
 problem occurred configuring root project 'performance-analyzer'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/runner/.gradle/caches/jars-9/d4f478f9ae0cd1ab05d07f6c0298de9b/jackson-core-2.15.1.jar.
```

We have to update the Gradle version to `7.16.1` to work with Jackson Core 2.15 https://github.com/FasterXML/jackson-core/issues/955

**Comment by gaiksaya** [comment]
> @prudhvigodithi @gaiksaya The 2.8.0 check is failing with following [error](https://github.com/opensearch-project/opensearch-build/actions/runs/5007635559/jobs/8974506616?pr=3528#step:6:1366):
> 
> ```
>  problem occurred configuring root project 'performance-analyzer'.
> > java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/runner/.gradle/caches/jars-9/d4f478f9ae0cd1ab05d07f6c0298de9b/jackson-core-2.15.1.jar.
> ```
> 
> We have to update the Gradle version to `7.16.1` to work with Jackson Core 2.15 [FasterXML/jackson-core#955](https://github.com/FasterXML/jackson-core/issues/955)

Yes! I believe that's what other components did as well.

**Comment by khushbr** [comment]
> > @prudhvigodithi @gaiksaya The 2.8.0 check is failing with following [error](https://github.com/opensearch-project/opensearch-build/actions/runs/5007635559/jobs/8974506616?pr=3528#step:6:1366):
> > ```
> >  problem occurred configuring root project 'performance-analyzer'.
> > > java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/runner/.gradle/caches/jars-9/d4f478f9ae0cd1ab05d07f6c0298de9b/jackson-core-2.15.1.jar.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We have to update the Gradle version to `7.16.1` to work with Jackson Core 2.15 [FasterXML/jackson-core#955](https://github.com/FasterXML/jackson-core/issues/955)
> 
> Yes! I believe that's what other components did as well.

Have backported the fix here https://github.com/opensearch-project/performance-analyzer/commit/b159f653fe919b3b2823878f53ceb3282d46a2e7 . Can you retry the Github workflow please.

**Pull request merged**
