### PR TITLE
Add 1.3.10 manifest as 1.3.9 is released

### PR DESCRIPTION
**Pull request by jordarlu**
### Description
Add 1.3.10 manifest as 1.3.9 is released

### Issues Resolved
Preparation for 1.3.10 release 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@gaiksaya @prudhvigodithi I believe it will be automatically added by the workflow?
Plus, this is only opensearch where is opensearch-dashboards?
Thanks.

**Comment by peterzhuamazon** [comment]
@jordarlu please make sure that OS and OSD core have bumped version.
OS will auto bump but OSD you need manual bump 1.3 branch to 1.3.10.

Thanks.

**Comment by zelinh** [comment]
> @gaiksaya @prudhvigodithi I believe it will be automatically added by the workflow? Plus, this is only opensearch where is opensearch-dashboards? Thanks.

I think the workflow is currently failing because of this issue. https://github.com/opensearch-project/opensearch-build/issues/3068

**Review by gaiksaya — APPROVED** [review]

**Comment by jordarlu** [comment]
> @jordarlu please make sure that OS and OSD core have bumped version. OS will auto bump but OSD you need manual bump 1.3 branch to 1.3.10.
> 
> Thanks.

Thanks for the instruction. @peterzhuamazon .. for OSD, I opened a PR (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3632) to bump the version but it was failed on test becasue of missing 1.3.10 snapshot, would you have an instruction how to generate one?

**Comment by jordarlu** [comment]
> > @gaiksaya @prudhvigodithi I believe it will be automatically added by the workflow? Plus, this is only opensearch where is opensearch-dashboards? Thanks.
> 
> I think the workflow is currently failing because of this issue. #3068

Thanks, guys... looks like the GHA does not fail all the time .. I can find some 1.3.10 OS plugin PR had been created , fopr exmple  : 
https://github.com/opensearch-project/alerting/pull/832
https://github.com/opensearch-project/anomaly-detection/pull/841

**Pull request merged**
