### PR TITLE
changes to the manifest file for 1.0.1 release

### PR DESCRIPTION
**Pull request by abhinavGupta16**
### Description
This PR changes the manifest file for the 1.0.1 release. The following new files are created with the updated versions - 

- manifests/1.0.1/manifest.linux.arm64.1.0.1.yml
- manifests/1.0.1/manifest.linux.x64.1.0.1.yml 
- manifests/1.0.1/opensearch-1.0.1.yml

#### Updates are done to the following plugins
- #### opensearch  

1. Index management
2. Security BE
3. Perf analyzer 

- #### opensearch dashboard
1. Security FE
2. Dashboards Reports
3. Notebooks Dashboards
4. Index management Dashboards

 
### Issues Resolved
This PR will be used for the 1.0.1 release, resolving any issues associated with the release.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@abhinavGupta16 please change security to use 1.0 branch in new manifest per security team.

**Comment by peterzhuamazon** [comment]
@abhinavGupta16 please also change PA to use 1.0.1 branch in new manifest per PA team.

**Comment by abhinavGupta16** [comment]
> @abhinavGupta16 please also change PA to use 1.0.1 branch in new manifest per PA team.

Updated the versions in the  new manifest as per updated request.

**Comment by abhinavGupta16** [comment]
> @abhinavGupta16 please change security to use 1.0 branch in new manifest per security team.

Updated the versions in the new manifest as per updated request.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peternied** [comment]
Please update the description of this pull request :)

**Review by peternied — DISMISSED** [review]
Seems like there was a change to include the platform manifests, are those a new requirement that are not captured in the readme for [bundle-workflow](https://github.com/opensearch-project/opensearch-build/tree/main/bundle-workflow)?

**Comment by abhinavGupta16** [comment]
> Please update the description of this pull request :)

Updated.

**Comment by peterzhuamazon** [comment]
@peternied The platform ones are the old methods, the opensearch-1.0.1.yml is new methods. And we ended up using the old methods this time due to new one is not working. Therefore we include both manifests here.

**Comment by peternied** [comment]
> @peternied The platform ones are the old methods, the opensearch-1.0.1.yml is new methods. And we ended up using the old methods this time due to new one is not working. Therefore we include both manifests here.

It sounds like the readme no longer describes the new process, can we do that in this change or a new PR?  I would prefer this pull request so that I could check the readme against what we are doing in this PR

**Review by bbarani — APPROVED** [review]

**Pull request merged**
