### PR TITLE
Bump up cmake version to 3.26.4

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Bump up cmake version to 3.26.4 to fix the failing CI in k-NN plugin

https://github.com/opensearch-project/k-NN/actions/runs/9822873197/job/27120072059?pr=1796
```
CMake Error at external/faiss/CMakeLists.txt:21 (cmake_minimum_required):
CMake 3.24.0 or higher is required.  You are running version 3.23.3
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Have an offline talk with @naveentatikonda and he will double check if there is a higher version of cmake we can move to to avoid constant update of images.

As of now faiss label to be at least 3.24.0
https://github.com/facebookresearch/faiss/pull/3305

for 
https://github.com/facebookresearch/faiss/pull/3501

Let's see if we can bump to 3.24.3 as least as that is the last version available on scoop for windows.

Thanks.

**Comment by naveentatikonda** [comment]
Tested with CMake version 3.26.4 on Linux machine and able to build k-NN libraries, so bumping cmake version to 3.26.4

**Review by peterzhuamazon — COMMENTED** [review]
Hi @naveentatikonda can you remove all the changes for items within `legacy` folder as they should remain the same as old templates.

Thanks.

**Comment by naveentatikonda** [comment]
> Hi @naveentatikonda can you remove all the changes for items within `legacy` folder as they should remain the same as old templates.
@peterzhuamazon reverted those changes in legacy folder. Pls take a look

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> > Hi @naveentatikonda can you remove all the changes for items within `legacy` folder as they should remain the same as old templates.
> 
> @peterzhuamazon reverted those changes in legacy folder. Pls take a look

Thanks @naveentatikonda , I will trigger the image building now.
Will update.

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-build/5537/console
https://build.ci.opensearch.org/job/docker-build/5539/console
https://build.ci.opensearch.org/job/docker-build/5541/console
https://build.ci.opensearch.org/job/docker-build/5542/console
https://build.ci.opensearch.org/job/docker-build/5543/console
https://build.ci.opensearch.org/job/docker-build/5544/console

**Comment by peterzhuamazon** [comment]
https://build.ci.opensearch.org/job/docker-copy/1302/console
https://build.ci.opensearch.org/job/docker-copy/1303/console
https://build.ci.opensearch.org/job/docker-copy/1304/console

**Comment by prudhvigodithi** [comment]
Using `opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1` and `"sha256:e580791eeb37f0c1ebb55729f29bc143296d8f9a03de752f93fe017fcf79eea6",` I get the error as `CMake 3.24.0 or higher is required.  You are running version 3.23.3`. The actual cmake version inside the image is `cmake version 3.23.3`.

**Comment by prudhvigodithi** [comment]
> Using `opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1` and `"sha256:e580791eeb37f0c1ebb55729f29bc143296d8f9a03de752f93fe017fcf79eea6",` I get the error as `CMake 3.24.0 or higher is required. You are running version 3.23.3`. The actual cmake version inside the image is `cmake version 3.23.3`.

Please ignore the latest sha of `opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1` has `cmake version 3.26.4`.
Thanks

**Pull request merged**
