### PR TITLE
Adding rockylinux8 ci runner to run OSD FT IntegTests

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Adding rockylinux ci runner to run OSD FT IntegTests
Cypress default to use electron instead of chrome/chromium, and have crashes after the tests.
CentOS7 is not capable of installing aarch64 version of chromium.
Using Rocky Linux 8 (in active support), which is based on CentOS 8 (no longer support) before the Stream Versions, can successfully complete the tests without issues.

[rockylinux-test-chromium.txt](https://github.com/opensearch-project/opensearch-build/files/8218948/123.txt)

Image uploaded to: https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&ordering=last_updated&name=ci-runner-rockylinux8-opensearch-dashboards-integtest-v1

 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/1708#issuecomment-1063125268
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
Created a container based on the issue. After checking out the build repo and seems python 3.7 missing

```
[opensearch@c61f1c63aa62 opensearch-build]$ ./build.sh manifests/1.3.0/opensearch-dashboards-1.3.0.yml
Installing dependencies in . ...
Warning: Python 3.7 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
[opensearch@c61f1c63aa62 opensearch-build]$ ./test.sh integ-test
Installing dependencies in . ...
Warning: Python 3.7 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
```

@peterzhuamazon

**Comment by peterzhuamazon** [comment]
> Created a container based on the image. After checking out the build repo and seems python 3.7 missing
> 
> ```
> [opensearch@c61f1c63aa62 opensearch-build]$ ./build.sh manifests/1.3.0/opensearch-dashboards-1.3.0.yml
> Installing dependencies in . ...
> Warning: Python 3.7 was not found on your system...
> Neither 'pyenv' nor 'asdf' could be found to install Python.
> You can specify specific versions of Python with:
> $ pipenv --python path/to/python
> [opensearch@c61f1c63aa62 opensearch-build]$ ./test.sh integ-test
> Installing dependencies in . ...
> Warning: Python 3.7 was not found on your system...
> Neither 'pyenv' nor 'asdf' could be found to install Python.
> You can specify specific versions of Python with:
> $ pipenv --python path/to/python
> ```
> 
> @peterzhuamazon

I installed python 3.8 hoping to save sometime without the need to install 3.7, seems like pipfile is locked to 3.7, will fix.

**Comment by peterzhuamazon** [comment]
> Once the image is updated, I can do another round of testing.

Updated, please pull the image again, thanks.

**Comment by tianleh** [comment]
Test on x64

Modify the OSD manifest to use my FTRepo https://github.com/tianleh/opensearch-dashboards-functional-test/tree/add-reports This will add back the reporting test cases and run Cypress against Chromium.

Then rebuild OSD and run the test.sh through 
```
./test.sh integ-test manifests/1.3.0/opensearch-dashboards-1.3.0-test.yml -p opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/latest/linux/x64 opensearch-dashboards=.

```

This is the output.

```
run security disabled tests
yarn run v1.22.17
$ env TZ=America/Los_Angeles NO_COLOR=1 cypress run --browser chromium --headless --env SECURITY_ENABLED=false --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js,cypress/integration/plugins/*/*'

==================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:      5.6.0                                                                            │
  │ Browser:      Chromium 96 (headless)                                                           │
  │ Specs:        40 found (core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test │
  │               _spec.js, plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js, p │
  │               lugins/alerting-dashboards-plugin/alert_spec.js, plugins/alerting-dashboards-plu │
  │               gin/alerts_dashbo...)                                                            │
  │ Searched:     cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js, cypre │
  │               ss/integration/plugins/*/*                                                       │
  │ Experiments:  experimentalNetworkStubbing=true                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


```

Although the eventual result failed, the Chromium part is verified.

```


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  core-opensearch-dashboards/opensear      00:31       34       34        -        -        - │
  │    ch-dashboards/dashboard_sanity_test                                                         │
  │    _spec.js                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/alerting-dashboards-plugin/      02:37        3        1        2        -        - │
  │    acknowledge_alerts_modal_spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      02:15        5        5        -        -        - │
  │    alert_spec.js                                                                               │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      01:19        2        2        -        -        - │
  │    alerts_dashboard_flyout_spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      00:40        4        4        -        -        - │
  │    bucket_level_monitor_spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      00:12        4        4        -        -        - │
  │    destination_spec.js                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/alerting-dashboards-plugin/      00:16        4        4        -        -        - │
  │    query_level_monitor_spec.js                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/anomaly-detection-dashboard      00:14        1        -        1        -        - │
  │    s-plugin/create_detector_spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:09        8        8        -        -        - │
  │    s-plugin/dashboard_spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/anomaly-detection-dashboard      01:07        5        4        1        -        - │
  │    s-plugin/detector_configuration_spe                                                         │
  │    c.js                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:13       11       11        -        -        - │
  │    s-plugin/detector_list_spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      01:04        6        6        -        -        - │
  │    s-plugin/historical_analysis_spec.j                                                         │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/anomaly-detection-dashboard      02:09        6        4        2        -        - │
  │    s-plugin/overview_spec.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:07        3        3        -        -        - │
  │    s-plugin/real_time_results_spec.js                                                          │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/anomaly-detection-dashboard      00:13        3        3        -        -        - │
  │    s-plugin/sample_detector_spec.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/gantt-chart-dashboards/gant      00:26        9        9        -        -        - │
  │    t_ui.spec.js                                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/index-management-dashboards      01:17        3        2        1        -        - │
  │    -plugin/indices_spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/index-management-dashboards      00:59        5        5        -        -        - │
  │    -plugin/managed_indices_spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/index-management-dashboards      00:19        5        5        -        -        - │
  │    -plugin/policies_spec.js                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/index-management-dashboards      00:28        4        4        -        -        - │
  │    -plugin/rollups_spec.js                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/index-management-dashboards      00:19        4        4        -        -        - │
  │    -plugin/transforms_spec.js                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/observability-dashboards/ap      09:06       20        2        8        2        8 │
  │    p_analytics.spec.js                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/ev      01:35       19       17        -        2        - │
  │    ent_analytics.spec.js                                                                       │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/no      04:08       28       26        -        2        - │
  │    tebooks.spec.js                                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/observability-dashboards/pa      07:54       26       25        1        -        - │
  │    nels.spec.js                                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/tr      00:39        8        4        -        4        - │
  │    ace_analytics_dashboard.spec.js                                                             │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/tr      00:29        6        5        -        1        - │
  │    ace_analytics_services.spec.js                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/observability-dashboards/tr      00:29        5        5        -        -        - │
  │    ace_analytics_traces.spec.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/query-workbench-dashboards/      01:23       20       20        -        -        - │
  │    ui.spec.js                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/reports-dashboards/01-creat      04:10       14       14        -        -        - │
  │    e.spec.js                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/reports-dashboards/02-edit.      01:21        3        3        -        -        - │
  │    spec.js                                                                                     │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/reports-dashboards/03-detai      01:57        6        6        -        -        - │
  │    ls.spec.js                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  plugins/reports-dashboards/04-downl      01:16        5        4        1        -        - │
  │    oad.spec.js                                                                                 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/audit_log_spec.js         1ms        -        -        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/auth_spec.js              1ms        -        -        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/get_started_spec.j        1ms        -        -        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/internalusers_spec        1ms        -        -        -        -        - │
  │    .js                                                                                         │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/permissions_spec.j        1ms        -        -        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/roles_spec.js             1ms        -        -        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  plugins/security/tenants_spec.js           1ms        -        -        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  8 of 40 failed (20%)                     51:36      289      253       17       11        8  
```

**Comment by tianleh** [comment]
Test on arm

I tried to rebuild OSD as above test in x64. However, OSD build failed.

```
  │ debg [discover] state = "compiler success" after 43.1 sec
   │ERROR webpack compile errors
       │ERROR [core] build
           │ERROR Optimizations failure.
           │         332 modules
           │          
           │          ERROR in ./public/index.scss?v7dark (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-0-1!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/postcss-loader/src??ref--6-oneOf-0-2!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-0-3!./public/index.scss?v7dark)
           │          Module build failed (from /tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js):
           │          SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │          SassError: SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │              at Object.render [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/index.js:73:16)
           │              at Object.done [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/neo-async/async.js:8067:18)
           │              at options.error (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/node-sass/lib/index.js:293:32)
           │           @ ./public/index.scss?v7dark 2:26-253
           │           @ ./public/index.scss
           │           @ ./public/index.ts
           │           @ /tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js
           │          
           │          ERROR in ./public/index.scss?v8dark (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-2-1!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/postcss-loader/src??ref--6-oneOf-2-2!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-2-3!./public/index.scss?v8dark)
           │          Module build failed (from /tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js):
           │          SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │          SassError: SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │              at Object.render [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/index.js:73:16)
           │              at Object.done [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/neo-async/async.js:8067:18)
           │              at options.error (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/node-sass/lib/index.js:293:32)
           │           @ ./public/index.scss?v8dark 2:26-253
           │           @ ./public/index.scss
           │           @ ./public/index.ts
           │           @ /tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js
           │          
           │          ERROR in ./public/index.scss?v7light (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/postcss-loader/src??ref--6-oneOf-1-2!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./public/index.scss?v7light)
           │          Module build failed (from /tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js):
           │          SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │          SassError: SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │              at Object.render [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/index.js:73:16)
           │              at Object.done [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/neo-async/async.js:8067:18)
           │              at options.error (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/node-sass/lib/index.js:293:32)
           │           @ ./public/index.scss?v7light 2:26-254
           │           @ ./public/index.scss
           │           @ ./public/index.ts
           │           @ /tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js
           │          
           │          ERROR in ./public/index.scss?v8light (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/postcss-loader/src??ref--6-oneOf-3-2!/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-3-3!./public/index.scss?v8light)
           │          Module build failed (from /tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js):
           │          SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │          SassError: SassError: Top-level selectors may not contain the parent selector "&".
           │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
           │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
           │                  from line 1:9 of src/core/public/chrome/_index.scss
           │                  from line 5:9 of /tmp/tmp74vzrlxd/OpenSearch-Dashboards/src/core/public/index.scss
           │          >>   &.euiBody--headerIsFixed {
           │          
           │             --^
           │          
           │              at Object.render [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/sass-loader/dist/index.js:73:16)
           │              at Object.done [as callback] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/neo-async/async.js:8067:18)
           │              at options.error (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/node-sass/lib/index.js:293:32)
           │           @ ./public/index.scss?v8light 2:26-254
           │           @ ./public/index.scss
           │           @ ./public/index.ts
           │           @ /tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js
   │ERROR failure 45 sec
   │ERROR Error: webpack issue
   │          at createFailError (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-dev-utils/target/run/fail.js:37:26)
   │          at Object.complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-optimizer/src/optimizer/handle_optimizer_completion.ts:61:19)
   │          at TapSubscriber._complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/operators/tap.ts:140:25)
   │          at TapSubscriber.Subscriber.complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:126:12)
   │          at MergeMapSubscriber.notifyComplete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/operators/mergeMap.ts:171:24)
   │          at SimpleInnerSubscriber._complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/innerSubscribe.ts:39:17)
   │          at SimpleInnerSubscriber.complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:126:12)
   │          at SafeSubscriber.subscriber.add.event$.subscribe [as _complete] (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/packages/osd-optimizer/src/common/event_stream_helpers.ts:115:24)
   │          at SafeSubscriber.wrappedComplete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:248:54)
   │          at SafeSubscriber.__tryOrUnsub (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
   │          at SafeSubscriber.complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:251:16)
   │          at Subscriber._complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:148:22)
   │          at Subscriber.complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:126:12)
   │          at MergeMapSubscriber.notifyComplete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/operators/mergeMap.ts:171:24)
   │          at SimpleInnerSubscriber._complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/innerSubscribe.ts:39:17)
   │          at SimpleInnerSubscriber.Subscriber.complete (/tmp/tmp74vzrlxd/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Subscriber.ts:126:12)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-03-10 06:55:59 ERROR    Error building OpenSearch-Dashboards, retry with: ./build.sh manifests/1.3.0/opensearch-dashboards-1.3.0.yml --component OpenSearch-Dashboards
Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 68, in main
    builder.build(build_recorder)
  File "/usr/share/opensearch/opensearch-build/src/build_workflow/builder_from_source.py", line 55, in build
    self.git_repo.execute(build_command)
  File "/usr/share/opensearch/opensearch-build/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /usr/share/opensearch/opensearch-build/scripts/components/OpenSearch-Dashboards/build.sh -v 1.3.0 -p linux -a arm64 -s false -o builds' returned non-zero exit status 1.

```

We can track this separately. To continue the testing of the Chromium part, I manually downloaded the OSD and OS arm artifact and run them. Then checkout my FTRepo repo and run `yarn cypress:run-plugin-tests-with-security`

Below is the output. We can see that tests are running against Chromium.

```

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    5.6.0                                                                              │
  │ Browser:    Chromium 96 (headless)                                                             │
  │ Specs:      39 found (plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js, plu │
  │             gins/alerting-dashboards-plugin/alert_spec.js, plugins/alerting-dashboards-plugin/ │
  │             alerts_dashboard_flyout_spec.js, plugins/alerting-dashboards-plugin/bucket_level_m │
  │             onitor_spec...)                                                                    │
  │ Searched:   cypress/integration/plugins/*/*.js                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Review by tianleh — APPROVED** [review]

**Comment by tianleh** [comment]
@peterzhuamazon

**Comment by gaiksaya** [comment]
All the docker files under ci are ci runners. Maybe rename the file only to `rockylinux8.dockerfile`

**Comment by abhinavGupta16** [comment]
> All the docker files under ci are ci-runners. Maybe rename the file only to `rockylinux8.dockerfile`

+1

**Review by gaiksaya — APPROVED** [review]
Looks like we have named of them similarly before https://github.com/opensearch-project/opensearch-build/tree/main/docker/ci/dockerfiles

**Pull request merged**
