### PR TITLE
Adds security plugin to 2.2.0 manifest

### PR DESCRIPTION
**Pull request by DarshitChanpura**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DarshitChanpura** [comment]
A CI check failed but it is not related to changes that I made. @opensearch-project/engineering-effectiveness Can you please re-run failed CI checks?

**Comment by dblock** [comment]
This is https://github.com/opensearch-project/opensearch-build/issues/2378

**Comment by peterzhuamazon** [comment]
@DarshitChanpura Please rebase on main we have fixed this issue.
Thanks.

**Comment by cwperks** [comment]
@peterzhuamazon This has been rebased. Looks like CI is passing now.

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
