### PR TITLE
Remove job-scheduler build.sh script to favor original repo build

### PR DESCRIPTION
**Pull request by amitgalitz**
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>

### Description
This PR syncs up the build.sh script with what is currently present in job-scheduler based of this recent PR (https://github.com/opensearch-project/job-scheduler/pull/117) in job scheduler plugin. This allows for job-scheduler to be published to maven now along with job-scheduler-spi. Before only spi was historically published.
 
### Issues Resolved
https://github.com/opensearch-project/job-scheduler/issues/114
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amitgalitz** [comment]
> Do we need this script here? If all building branches of job-scheduler have it, delete it altogether from here.

I think the idea is to have it both here and the job-scheduler script will act as a backup. Having them in opensearch-build I assume is an easy way to consistently make sure job-scheduler always gets built. Additionally we haven't yet backported changes to other branches in job-scheduler. @mch2 do you have anything else to add to this.

**Comment by dblock** [comment]
> > Do we need this script here? If all building branches of job-scheduler have it, delete it altogether from here.
> 
> I think the idea is to have it both here and the job-scheduler script will act as a backup. Having them in opensearch-build I assume is an easy way to consistently make sure job-scheduler always gets built. Additionally we haven't yet backported changes to other branches in job-scheduler. @mch2 do you have anything else to add to this.

We only did this because it was faster to make changes that applied to multiple versions, the plan has always been to delete these scripts from this repo.

**Comment by mch2** [comment]
> > > Do we need this script here? If all building branches of job-scheduler have it, delete it altogether from here.
> > 
> > 
> > I think the idea is to have it both here and the job-scheduler script will act as a backup. Having them in opensearch-build I assume is an easy way to consistently make sure job-scheduler always gets built. Additionally we haven't yet backported changes to other branches in job-scheduler. @mch2 do you have anything else to add to this.
> 
> We only did this because it was faster to make changes that applied to multiple versions, the plan has always been to delete these scripts from this repo.

Yeah this was so we could move quickly when setting this up.  @amitgalitz Lets take this opportunity to get this backported in supported branches of job-scheduler and then remove it here.

**Comment by amitgalitz** [comment]
> > > > Do we need this script here? If all building branches of job-scheduler have it, delete it altogether from here.
> > > 
> > > 
> > > I think the idea is to have it both here and the job-scheduler script will act as a backup. Having them in opensearch-build I assume is an easy way to consistently make sure job-scheduler always gets built. Additionally we haven't yet backported changes to other branches in job-scheduler. @mch2 do you have anything else to add to this.
> > 
> > 
> > We only did this because it was faster to make changes that applied to multiple versions, the plan has always been to delete these scripts from this repo.
> 
> Yeah this was so we could move quickly when setting this up. @amitgalitz Lets take this opportunity to get this backported in supported branches of job-scheduler and then remove it here.

Sounds good, I'll change this PR to remove the job-scheduler folder from components after it gets back-ported in job-scheduler to the necessary branches.

**Comment by abhinavGupta16** [comment]
Issue this PR resolved is closed - opensearch-project/job-scheduler#114

Should we reopen the issue or create a new one for this?

**Comment by amitgalitz** [comment]
> Issue this PR resolved is closed - [opensearch-project/job-scheduler#114](https://github.com/opensearch-project/job-scheduler/issues/114)
> 
> Should we reopen the issue or create a new one for this?

Currently the issue should be reopened until we backport the build.sh changes from that PR into all supported branches in  job-scheduler. After those are backported. I will make this PR non-draft so we can remove the build.sh script from this repo for job-scheduler.

**Comment by dblock** [comment]
@amitgalitz What are we doing with this?

**Comment by amitgalitz** [comment]
> @amitgalitz What are we doing with this?

This change should go through once build.sh has been updated on all supported job-scheduler branches. I have this PR out that I have put on hold for a few days. I am currently trying to figure out the CI issue. https://github.com/opensearch-project/job-scheduler/pull/120

**Comment by peternied** [comment]
@amitgalitz I've restarted the failed CI workflow, that looks like an unrelated issue that has since been resolved.

**Review by dblock — APPROVED** [review]
I believe that if you rebase the error will get fixed.

**Review by dblock — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
