### PR TITLE
Update build cron for 2.5.0 to every hour

### PR DESCRIPTION
**Pull request by bowenlan-amzn**
Signed-off-by: bowenlan-amzn <bowenlan23@gmail.com>

### Description
Update the cron schedule of build workflow for 2.5.0 to every hour

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @gaiksaya @prudhvigodithi I have discussed with @bowenlan-amzn offline that they want to start building 2.5.0 right now in a more frequent fashion.

Please add you thoughts on whether this is fine for now.

Thanks.

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon and @bowenlan-amzn LGTM.

**Review by prudhvigodithi — APPROVED** [review]

**Review by zelinh — COMMENTED** [review]
I'm good with increasing the frequency for the builds on 2.5.0 but just notice we only have core and CU plugin right now. Prob would need to add those plugins that are being actively developed to the manifest as well.

**Review by gaiksaya — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> I'm good with increasing the frequency for the builds on 2.5.0 but just notice we only have core and CU plugin right now. Prob would need to add those plugins that are being actively developed to the manifest as well.

Yeah, right now @bowenlan-amzn is waiting for the new CU maven to work on their plugins.
I would suggest Bowen add this line as well for a more frequent Core+CU deployment that does not impact the artifacts.

```
            H/60 * * * %INPUT_MANIFEST=2.5.0/opensearch-2.5.0.yml;TARGET_JOB_NAME=distribution-build-opensearch;BUILD_PLATFORM=linux;COMPONENTS=OpenSearch common-utils;UPDATE_LATEST_URL=false
```

This probably need to make changes here so maven can be constantly updated without interrupting actual artifacts creation.
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/check-for-build.jenkinsfile#L89-L93

Thanks.

**Comment by gaiksaya** [comment]
I would keep keep default to `true` and work on https://github.com/opensearch-project/opensearch-build/issues/2749

Posting some suggestions for anyone to pick up:
Currently, the snapshots are published only after the build is successful https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L152-L171
I believe if we want to unblock dependency on entire build, the publishing to snapshot should be a part of this stage https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L178-L218

**Comment by peterzhuamazon** [comment]
> I would keep keep default to `true` and work on #2749
> 
> Posting some suggestions for anyone to pick up: Currently, the snapshots are published only after the build is successful https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L152-L171 I believe if we want to unblock dependency on entire build, the publishing to snapshot should be a part of this stage https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L178-L218

That is also fine I just want to unblock @bowenlan-amzn right now just in case other failures block core/CU maven updates.

Thanks.

**Pull request merged**
