### PR TITLE
Hyperlink of CloudFront url rewriter has been changed

### PR DESCRIPTION
**Pull request by Divyaasm**
Signed-off-by: Divya Madala <divyaasm@amazon.com>
### Description
Hyperlink of CloudFront url rewriter has been changed .

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
@Divyaasm please sign your dco with -s parameter.

**Comment by prudhvigodithi** [comment]
Hey @Divyaasm thanks for the PR, make sure you have your DCO setup in place.

**Comment by Divyaasm** [comment]
> @Divyaasm please sign your dco with -s parameter.

I made the changes. Thank you.

**Comment by peterzhuamazon** [comment]
IDK what changes you made but github didnt show you made such change.

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Looks like DCO was manually approved. @Divyaasm Can you append the commit and push again. I believe this will fail on merge. Try `git commit --amend --no-edit -s`

**Pull request merged**
