### PR TITLE
Avoid checking outdated branches during manifest update

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Avoid checking outdated branches during manifest update

### Issues Resolved
https://github.com/avast/gradle-docker-compose-plugin/issues/446

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — COMMENTED** [review]
This looks good to me. Do we want to add some test cases for these changes?

**Comment by peterzhuamazon** [comment]
> This looks good to me. Do we want to add some test cases for these changes?

Not very easy to test as majority of the 

> This looks good to me. Do we want to add some test cases for these changes?

Added now, thanks.

**Comment by peterzhuamazon** [comment]
Test locally:
```
2024-07-19 20:10:17 INFO     Known versions: ['1.0.0', '1.0.1', '1.1.0', '1.1.1', '1.2.0', '1.2.1', '1.2.2', '1.2.3', '1.2.4', '1.2.5', '1.3.0', '1.3.1', '1.3.2', '1.3.3', '1.3.4', '1.3.5', '1.3.6', '1.3.7', '1.3.8', '1.3.9', '1.3.10', '1.3.11', '1.3.12', '1.3.13', '1.3.14', '1.3.15', '1.3.16', '1.3.17', '1.3.18', '1.4.0', '2.0.0', '2.0.1', '2.0.2', '2.1.0', '2.1.1', '2.2.0', '2.2.1', '2.2.2', '2.3.0', '2.3.1', '2.4.0', '2.4.1', '2.4.2', '2.5.0', '2.5.1', '2.6.0', '2.6.1', '2.7.0', '2.7.1', '2.8.0', '2.8.1', '2.9.0', '2.9.1', '2.10.0', '2.10.1', '2.11.0', '2.11.1', '2.11.2', '2.12.0', '2.12.1', '2.13.0', '2.13.1', '2.14.0', '2.14.1', '2.15.0', '2.15.1', '2.16.0', '3.0.0']
2024-07-19 20:10:17 INFO     Checking out components into /tmp/tmpjyhg7jik
2024-07-19 20:10:18 INFO     Checking OpenSearch ['1.3', '1.x', '2.0', '2.1', '2.10', '2.11', '2.12', '2.13', '2.14', '2.15', '2.2', '2.3', '2.4', '2.5', '2.5-transfer', '2.6', '2.7', '2.8', '2.9', '2.x', 'main'] branches
2024-07-19 20:10:18 INFO     Ignoring OpenSearch ['1.0', '1.1', '1.2'] branches as they are outdated
2024-07-19 20:10:18 INFO     Executing "git init" in /tmp/tmpjyhg7jik/OpenSearch/1.3
2024-07-19 20:10:18 INFO     Executing "git remote add origin https://github.com/opensearch-project/OpenSearch.git" in /tmp/tmpjyhg7jik/OpenSearch/1.3
2024-07-19 20:10:18 INFO     Executing "git fetch --depth 1 origin 1.3" in /tmp/tmpjyhg7jik/OpenSearch/1.3
2024-07-19 20:10:22 INFO     Executing "git checkout FETCH_HEAD" in /tmp/tmpjyhg7jik/OpenSearch/1.3
2024-07-19 20:10:23 INFO     Executing "git rev-parse HEAD" in /tmp/tmpjyhg7jik/OpenSearch/1.3
2024-07-19 20:10:23 INFO     Checked out https://github.com/opensearch-project/OpenSearch.git@1.3 into /tmp/tmpjyhg7jik/OpenSearch/1.3 at 338255f1217356766b459cadf6b0aec25267eefc
2024-07-19 20:10:23 INFO     Executing "./gradlew properties -Dbuild.snapshot=false" in /tmp/tmpjyhg7jik/OpenSearch/1.3
```

**Review by zelinh — APPROVED** [review]
Thanks!

**Pull request merged**
