### PR TITLE
1.0.0 changelog: mention no breaking changes

### PR DESCRIPTION
**Pull request by aviau**
I know this is a past release but some of us are still migrating from ES and a big BREAKING CHANGES with title 10 thousand things under it is scary until you realize its an empty section. 🙃

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @aviau sorry that this is a miss from our side.
Can you consider completely remove the `Breaking Changes` section?
This is also our standard practice since ODFE.

Thanks.

**Comment by aviau** [comment]
@peterzhuamazon done!

**Review by zelinh — APPROVED** [review]
Thanks!

**Comment by peterzhuamazon** [comment]
@aviau you need to sign off DCO.
Please do `git commit --amend --no-edit -s -S` and push again.
Thanks.

**Review by peternied — CHANGES_REQUESTED** [review]
I don't think that we should remove this section, its important to call out that we did not introduce any breaking changes.

Could you help me understand how when you saw the release notes it looked like there were many breaking changes, maybe a screenshot?

**Comment by aviau** [comment]
I won't put any more efforts here, I think my issue description is self-explainatory. Empty sections aren't obvious in rendered markdown. If you don't agree then please just close my PR.

**Comment by dblock** [comment]
I think it should either say None or be removed. Don’t care either way. 

@aviau thank you!

@peternied ok merging as is or do you want to PR an alternative?

**Comment by peternied** [comment]
@aviau Thanks for the contribution - lets merge this as is and we can make additional PRs in the future.

There is an issue https://github.com/opensearch-project/opensearch-build/issues/438 tracking the codification of the release notes process.

**Review by peternied — APPROVED** [review]

**Pull request merged**
