### PR TITLE
Added common-utils with qualifier support to 2.0 manifest.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@dblock.org>

### Description

Added common-utils with qualifier support to 2.0 manifest.

### Issues Resolved

Following https://github.com/opensearch-project/common-utils/pull/128 and https://github.com/opensearch-project/common-utils/pull/129.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
What would happen if `QUALIFIER=""`, will `-Dbuild.version_qualifier=$QUALIFIER` error out the script?

**Comment by peterzhuamazon** [comment]
And does build workflow support adding `-q` related values already?
Thanks.

**Comment by dblock** [comment]
> What would happen if `QUALIFIER=""`, will `-Dbuild.version_qualifier=$QUALIFIER` error out the script?

Nope, it will just work as if there's no qualifier.

**Comment by dblock** [comment]
> And does build workflow support adding `-q` related values already? Thanks.

I believe I have modified scripts in all the right places, but I could be wrong.

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
