### PR TITLE
Improve the type checking for CI workflow

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
There aren't much else to fix for the type checking on CI-workflw. 

The usage of `Any` is necessary for the rest of the circumstances because of the testing we had; attributes certain types like `Component` or `InputManifest` don't have or the existing checks inside the code block (e.g. `ci_check_lists`). 
 
### Issues Resolved
This continues on the previous #1582 and improve based on that. 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zelinh** [comment]
> Can you add the path here: https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/python-tests.yml#L35?

It has been included there.

**Comment by gaiksaya** [comment]
> > Can you add the path here: https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/python-tests.yml#L35?
> 
> It has been included there.

I see! This PR was the one https://github.com/opensearch-project/opensearch-build/pull/1582
Thanks!

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Hi @zelinh , there is a failing test https://github.com/opensearch-project/opensearch-build/runs/5380201785?check_suite_focus=true
Can you take a look?

**Comment by zelinh** [comment]
> https://github.com/opensearch-project/opensearch-build/runs/5380201785?check_suite_focus=true

Seems like it's good now.

**Pull request merged**
