### PR TITLE
Move parameters out of a stage.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

I am not sure why parameters even work inside a stage, but reading https://www.jenkins.io/doc/book/pipeline/syntax/ parameters can be written in a simpler way at a `pipeline` level. 

```
parameters {
  param1
  param2
  ...
}
```

Looks the same from my test config.

Screen Shot 2021-11-18 at 2 22 03 PM

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Will these parameters then be available for all stages just in case we want to reuse those and be careful with overwriting the param values?

**Comment by dblock** [comment]
> Will these parameters then be available for all stages just in case we want to reuse those and be careful with overwriting the param values?

AFAIK yes and that was the original intent, but I could be wrong, @peterzhuamazon will know best?

**Review by peternied — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]
Hope this does not break anything, @peterzhuamazon if any objections let us know.
Thanks!

**Comment by peterzhuamazon** [comment]
Golden.

**Pull request merged**
