### PR TITLE
Update ref branch to 2.7 for OpenSearch-Spatial plugins

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Update ref branch from 2.x to 2.7 for OpenSearch-Spatial plugins (k-NN, geospatial, neural search, dashboards-maps)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — COMMENTED** [review]
Hey @naveentatikonda Thanks for this updates. Could you use single quote for the ref here as `'2.7'`?

**Comment by naveentatikonda** [comment]
> Hey @naveentatikonda Thanks for this updates. Could you use single quote for the ref here as `'2.7'`?

Updated, Thank you!

**Review by VijayanB — APPROVED** [review]

**Comment by naveentatikonda** [comment]
Some of the checks failed because it can't find asynchronous-search plugin in 2.7 artifact
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'asynchronous-search'.
> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-asynchronous-search-2.7.0.0.zip to /tmp/tmpro65vrvd/asynchronous-search/src/test/resources/org/opensearch/search/asynchronous/bwc/2.7.0.0/opensearch-asynchronous-search-2.7.0.0.zip

**Review by zelinh — APPROVED** [review]

**Comment by zelinh** [comment]
CI check failed on 3.0.0 isn't a blocker for this PR. Merging now.

**Pull request merged**
