### PR TITLE
Enhanced build Error Parser

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
This change will eliminate the bug of adding all ERROR messages upon build failure

- Added Exact match patter
- Changed to `Error Building` from `ERROR`
- Used `java.util.regex.Matcher` for match identifier
- Removes build date timestamp from error parser

 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
1. Please rebase.
2. Sign DCO.
3. Does jenkins groovy test change txt after these changes?

**Comment by prudhvigodithi** [comment]
@peterzhuamazon thanks 
but the DCO is already there and rebased it as well
I can see this weird error for DCO failure.
`Error: An error occurred trying to start process '/home/runner/runners/2.289.2/externals/node12/bin/node' with working directory '/home/runner/work/opensearch-build/opensearch-build'. Argument list too long`

**Comment by peterzhuamazon** [comment]
You have 20+ commit the DCO workflow is attempt to test them all and utterly failed due to you have too many commit.

Hence Argument too long after the check.

That is why I ask you to rebase to main

So you can squash all those commit into one

**Comment by prudhvigodithi** [comment]
Closing this PR, will create a new one with Same fix

**Pull request closed without merging**
