### PR TITLE
Replace wget with curl

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Got error while running this workflow. Instead of adding new package using what we already have on the system
```
line 1: wget: command not found
```
Replacing wget with curl
 
### Issues Resolved
N/A
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — COMMENTED** [review]
You will need to update the regression tests as they will fail

**Comment by gaiksaya** [comment]
> You will need to update the regression tests as they will fail

On it!

**Review by dlvenable — APPROVED** [review]

**Review by zelinh — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Comment by jcgraybill** [comment]
Hey, as a matter of practice, is there a reason this script doesn't specify the full path to binaries it calls? E.g. why `curl` instead of `/usr/bin/curl`? It seems like a best practice to use the latter.

**Comment by dblock** [comment]
> Hey, as a matter of practice, is there a reason this script doesn't specify the full path to binaries it calls? E.g. why `curl` instead of `/usr/bin/curl`? It seems like a best practice to use the latter.

We have lots of places we call shell scripts without hard-coding a path, so maybe better to open a new issue. 
Note that likely the "correct" way to do this is `/usr/bin/env curl` to be properly cross-platform.

**Pull request merged**
