### PR TITLE
Add OSDFT repo to manifest 2.4.0, and 3.0.0

### PR DESCRIPTION
**Pull request by noCharger**
Signed-off-by: Louis Chu <lingzhichu.clz@gmail.com>

### Description
Add OSDFT repo to manifest 2.4.0, and 3.0.0

### Issues Resolved
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/285

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by noCharger** [comment]
> @noCharger please fix your linting issues to yml. Thanks.

Sure, fixed.

**Review by peterzhuamazon — APPROVED** [review]

**Review by zelinh — APPROVED** [review]

**Comment by tianleh** [comment]
Could you also add the test manifest for OSD? See example there https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.0/opensearch-dashboards-2.3.0-test.yml#L13

@noCharger

**Comment by noCharger** [comment]
> https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.0/opensearch-dashboards-2.3.0-test.yml#L13

**Comment by noCharger** [comment]
> Could you also add the test manifest for OSD? See example there https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.0/opensearch-dashboards-2.3.0-test.yml#L13
> 
> @noCharger

Hi @tianleh, the test manifest is auto generated, with OSDFT repo included.

**Comment by peterzhuamazon** [comment]
Retrigger manifests failed, ignore groovy test.

**Comment by tianleh** [comment]
> Hi @tianleh, the test manifest is auto generated, with OSDFT repo included.

I cannot find the test manifest under https://github.com/opensearch-project/opensearch-build/tree/main/manifests/2.3.1 @noCharger

**Comment by peterzhuamazon** [comment]
There are still failures on the manifest files.

**Comment by peterzhuamazon** [comment]
Can you ignore 2.3.1 as we are not building it in any recent time.
Once 2.4.0 is out there is no 2.3.1 anyway.

Thanks.

**Comment by noCharger** [comment]
@peterzhuamazon @gaiksaya  Discarded 2.3.1 and rebased.

**Comment by noCharger** [comment]
> > Hi @tianleh, the test manifest is auto generated, with OSDFT repo included.
> 
> I cannot find the test manifest under https://github.com/opensearch-project/opensearch-build/tree/main/manifests/2.3.1 @noCharger

@tianleh  Yes EE team will trigger the automated process before the release to create the file. From Peter, we will skip 2.3.1.

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
@tianleh @peterzhuamazon Any objections to merge this PR?

**Pull request merged**
