### PR TITLE
Change manifest to point to AD Dashboards 1.3 branch

### PR DESCRIPTION
**Pull request by ohltyler**
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>

### Description
Change manifest to point to AD Dashboards 1.3 branch
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by ohltyler** [comment]
@cliu123 checks are failing since there is no security dashboards 1.3 branch as specified in the manifest, can you create one?

**Comment by cliu123** [comment]
> @cliu123 checks are failing since there is no security dashboards 1.3 branch as specified in the manifest, can you create one?

`1.3` branch has been remove from security-dashboards-plugin. I'll change the branch in manifest.

**Comment by ohltyler** [comment]
> > @cliu123 checks are failing since there is no security dashboards 1.3 branch as specified in the manifest, can you create one?
> 
> `1.3` branch has been remove from security-dashboards-plugin. I'll change the branch in manifest.

just curious, why would it be removed?

**Comment by cliu123** [comment]
> > > @cliu123 checks are failing since there is no security dashboards 1.3 branch as specified in the manifest, can you create one?
> > 
> > 
> > `1.3` branch has been remove from security-dashboards-plugin. I'll change the branch in manifest.
> 
> just curious, why would it be removed?

1.3 branch is not needed at this point in security-dashboards-plugin. In order to avoid unnecessary backport, we will create it when it is needed and all commits for 1.3.0 release are merged to main branch.

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
