### PR TITLE
Add security dashdoards plugin to manifest 1.2.0

### PR DESCRIPTION
**Pull request by hsiang9431-amzn**
### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
Looks like this is impacted by a failure from asynchronous-search, https://github.com/opensearch-project/opensearch-build/issues/864  @zelinh Can you rollback that change so this PR isn't blocked?

**Comment by zelinh** [comment]
> Looks like this is impacted by a failure from asynchronous-search, #864 @zelinh Can you rollback that change so this PR isn't blocked?

I think this one is for the dashboard and #864 was for bundle-build.

**Comment by hsiang9431-amzn** [comment]
This PR is for adding security dashboards to manifest, thanks for investigating

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Rebase this on top of #876, I think this is an unrelated failure.

**Pull request merged**
