### PR TITLE
2.15.0 RC3 Changes

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
2.15.0 RC3 Changes

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/4681

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by prudhvigodithi — APPROVED** [review]

**Comment by gaiksaya** [comment]
@prudhvigodithi Wont our automation do this? Pick up the recent commit for specific component?

**Comment by prudhvigodithi** [comment]
Hey @gaiksaya just had a same discussion with @peterzhuamazon, it should pick up.

**Comment by gaiksaya** [comment]
> Hey @gaiksaya just had a same discussion with @peterzhuamazon, it should pick up.

I just tried. Works as expected https://github.com/opensearch-project/opensearch-build/pull/4776

**Comment by peterzhuamazon** [comment]
In the case where a commit is not head of the branch, the automation does not pick up.
This is easier for me to control the RCs over time.

THanks.

**Pull request merged**
