### PR TITLE
Jenkins job for release notes workflow

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Jenkins job to call the [release_notes_workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/release_notes_workflow).

### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/2345

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
I dont see any reason to create and maintain a separate shared library for this use-case, all it does is calls the release_notes_workflow and add/update the user passed github issue (just a few bash commands). All our existing tests include testing the shared library and not to the actual direct pipeline(jenkinsfile). Let me know if this PR is good or required any additional tests/modifications.
Thank you 
@zelinh @gaiksaya.

**Comment by gaiksaya** [comment]
We should start adding regression tests for all jenkins files that we use for production. Today we don't know how a change in jenkins library affect the workflow overall.
We can start with this or create an enhancement issues to do so. cc: @bbarani 
I believe the test for the actual library is tested in underlying python?

**Comment by prudhvigodithi** [comment]
> I believe the test for the actual library is tested in underlying python?

Yes @gaiksaya the workflow has tests involved https://github.com/opensearch-project/opensearch-build/tree/main/tests/tests_release_notes_workflow
https://github.com/opensearch-project/opensearch-build/blob/main/tests/test_run_releasenotes_check.py
CC: @dblock

**Review by gaiksaya — APPROVED** [review]
Please reopen and update this issue https://github.com/opensearch-project/opensearch-build/issues/1468
Since these are all production workflows, tests should be added for them. I know they are just txt files today but it atleast shows the contributor how their change in a jenkins library is affecting the jenkins workflow(s) overall

Thanks!

**Comment by prudhvigodithi** [comment]
I see there are multiple issues related to jenkins testing, may be its better to open a one META issue, summarizing all the requirements.
https://github.com/opensearch-project/opensearch-build/issues/1468
https://github.com/opensearch-project/opensearch-build/issues/1444
https://github.com/opensearch-project/opensearch-build/issues/1712

**Pull request merged**
