### PR TITLE
Tag promoting image with its major and minor version

### LINKED ISSUE #1621: Docker Labels for Latest of Major (or Minor) Versions
### Is your feature request related to a problem? Please describe

Currently, to pull a Docker image, administrators can either pull the latest or a specific version. In this Issue, I will Data Prepper as an example, but this could be applied for OpenSearch as well.

```
docker pull opensearchproject/data-prepper:latest
```

or

```
docker pull opensearchproject/data-prepper:1.2.1
```

However, pulling the `latest` will begin to pull breaking changes after the next major version (2.0) is released. There is no shorthand way to specify pulling the latest version for either a major version or a minor version. So administrators must either specify specific versions or pull latest and risk pulling breaking changes.

### Describe the solution you'd like

Provide the following Docker tags on images:

* `{major}` - Pulls the latest version for a SemVer major version sequence. This tag will change to be on the latest image for any build within the specified `{major}` version.
* `{major}.{minor}` - Pull the latest patch release for a SemVer major/minor version. This tag will change to be on the latest image for any build within the specified `{major}.{minor}` version.

#### Example Scenario

Data Prepper already has the following tags: `1.0.0`, `1.1.0`, `1.1.1`, `1.2.0`, `1.2.1`.

In this new scheme, releasing Data Prepper 1.3.0 will create a new image. That image will have the following tags: `1.3.0`, `1.3`, `1`, and `latest`.

```
docker pull opensearchproject/data-prepper:1
```

The command above would pull data-prepper 1.3.0.

After releasing Data Prepper 1.3.1, Data Prepper would have a new image with the `1.3.1` tag. Additionally, we would move the `1.3`, `1`, and `latest` tags to the 1.3.1 image.

After releasing Data Prepper 2.0.0, Data Prepper would have a new image with the following new tags: `2.0.0`, `2.0`, and `2`. Additionally, we would move the `latest` tag to the 2.0.0 image. However, the `1` and `1.3` tags would remain on Data Prepper 1.3.1. 

If a security fix requires that we create a Data Prepper 1.3.2 image, we would create a new image with the `1.3.2` tag. Additionally, the `1` and `1.3` tags would move to the 1.3.2 image. The `latest` remains on the `2.0.0` image.

Releasing Data Prepper 2.1.0 would create a new image with the following new tags: `2.1.0` and `2.1`. Additionally, we would move the `latest` and `2` tags to point to the 2.1.0 image.

### Handling Build Numbers

There is a different proposal to include build numbers in image tags in #1461 when updating the base image. My proposal and #1461 are compatible.

Say we release Data Prepper 1.3.0 with the label: `1.3.0-1` where `-1` represents the build. (Docker tags do not support `+`). This image would have the following labels: `1.3.0-1`, `1.3.0`, `1.3`, `1`, and `latest`. If we release a new build with a Docker image, we would tag it `1.3.0-2`, `1.3.0`, `1.3`, `1`, and `latest`.

### Describe alternatives you've considered

OpenSearch projects could use a different syntax for the tags. One option is to include a ".x" suffix. It is shown below:

* `{major}.x`
* `{major.minor}.x`

This approach can be advantageous since there is no possibility for conflicts with a fully resolved version. However, OpenSearch projects already use branch names of `{major}.{minor}` and tags of `{major}.{minor}.{patch}` so this probably doesn't matter.

The proposed solution will keep in line with Git branch names. 

One other alternative, is that OpenSearch projects could supply only the major versions. Since OpenSearch projects use semver, the risk when pulling a new minor version is not as great. The major/minor version could be a future add-on if necessary.

### Additional context

OpenJDK provides a similar pattern where you can specify specific Java versions. Examples: `docker pull openjdk:11`, `docker pull openjdk:17`.
https://hub.docker.com/_/openjdk?tab=description

This proposal has some similarities to  https://github.com/opensearch-project/opensearch-build/issues/1492. That issue is specifically for archives, but the conventions used should be similar between both proposals.

### PR DESCRIPTION
**Pull request by zelinh**
### Description
Tag promoting image with its major and minor version. 
Add two additional boolean parameters to enable promoting staging images with its major or minor version tag.
E.g.: for example new 1.3.3 docker image will have options to label with `1` ({major} version), `1.3`  ({major}.{minor} version) and `latest` when promoting from staging.

### Issues Resolved
#1621 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by zelinh** [comment]
We will hold this PR until updates on this PR #2128

**Comment by bbarani** [comment]
@peterzhuamazon @zelinh @prudhvigodithi Whats the next step on this PR?

**Comment by prudhvigodithi** [comment]
The [docker-copy](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/docker/docker-copy.jenkinsfile) code, should be able to copy the images across registries (DockerHub and ECR). This job can be leveraged to push the images with required major, minor versions.
@bbarani @peterzhuamazon @zelinh

**Comment by zelinh** [comment]
> The [docker-copy](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/docker/docker-copy.jenkinsfile) code, should be able to copy the images across registries (DockerHub and ECR). This job can be leveraged to push the images with required major, minor versions. This issue #1621 should not be a blocker moving forward 👍 @bbarani @peterzhuamazon @zelinh

Agree. I would discuss with @peterzhuamazon tomorrow on how we could design for specifically docker promotion with major or latest tag.

**Comment by zelinh** [comment]
After discussing with @peterzhuamazon, I will close this PR for now since we think the issue resolved here could also be executed with the new copy container workflow. 
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/docker/docker-copy.jenkinsfile

**Pull request closed without merging**
