### PR TITLE
Add OpenSearch Project Build System Quick Overview Wiki Page

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Add OpenSearch Project Build System Quick Overview Wiki Page

Example Wiki: https://github.com/peterzhuamazon/opensearch-build/wiki/OpenSearch-Project-Build-System-Quick-Overview

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/4489
https://github.com/opensearch-project/opensearch-build/issues/4267

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @Pallavi-AWS @bbarani could you please review this wiki and let me know if it is ready to be published?

Thanks!

**Comment by peterzhuamazon** [comment]
Hi @bbarani please review as I updated the runners to include m54xlarge.

Thanks.

**Review by bbarani — APPROVED** [review]

**Comment by Pallavi-AWS** [comment]
Happy to see this build wiki @peterzhuamazon - thank you

**Comment by peterzhuamazon** [comment]
> Happy to see this build wiki @peterzhuamazon - thank you

Thanks @Pallavi-AWS !

**Pull request merged**
