### PR TITLE
Remove rpm-validation jenkins job in build repo

### PR DESCRIPTION
**Pull request by Divyaasm**
### Description
rpm-validation is now completely migrated to Validation Workflow.

Cleaning up the job and it's usage in the distribution-build workflows.

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/4968

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peterzhuamazon — COMMENTED** [review]
Instead of removing `jenkins/rpm-validation/rpm-validation.jenkinsfile` just put it into legacy dir like others.

**Comment by gaiksaya** [comment]
> Instead of removing `jenkins/rpm-validation/rpm-validation.jenkinsfile` just put it into legacy dir like others.

I dont believe we have legacy for jenksinfile, We can retrieve it anytime we want from old branches/tags.

**Review by gaiksaya — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> > Instead of removing `jenkins/rpm-validation/rpm-validation.jenkinsfile` just put it into legacy dir like others.
> 
> I dont believe we have legacy for jenksinfiles, We can retrieve it anytime we want from old branches/tags.



> > Instead of removing `jenkins/rpm-validation/rpm-validation.jenkinsfile` just put it into legacy dir like others.
> 
> I dont believe we have legacy for jenksinfiles, We can retrieve it anytime we want from old branches/tags.

We have legacy for docker files and others tho.

**Comment by gaiksaya** [comment]
Looks like we do have https://github.com/opensearch-project/opensearch-build/tree/main/jenkins/legacy
I feel its irrelevant but upon you if you want to keep it. Same goes for legacy files. They wont ever be used and we can get if we want from tags or branches.

**Comment by peterzhuamazon** [comment]
> Looks like we do have https://github.com/opensearch-project/opensearch-build/tree/main/jenkins/legacy I feel its irrelevant but upon you if you want to keep it. Same goes for other legacy files. They wont ever be used and we can get if we want from tags or branches.

I would say keep it and it is easier for users to check.

Hi @Divyaasm would you mind move it to legacy dir?

Thanks.

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
