### PR TITLE
Use common-utils 1.1 branch for OpenSearch 1.1

### PR DESCRIPTION
**Pull request by aditjind**
### Description
Change to use the 1.1 branch of Common Utils in the 1.1 manifest file.
 
### Issues Resolved
https://github.com/opensearch-project/common-utils/issues/64

PR (https://github.com/opensearch-project/common-utils/pull/65) with all the commits cherry picked from the main branch. We can keep this PR as an artifact. 

 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by skkosuri-amzn — APPROVED** [review]

**Comment by aditjind** [comment]
PR Merged: https://github.com/opensearch-project/common-utils/pull/67

**Review by VachaShah — APPROVED** [review]

**Comment by aditjind** [comment]
@VachaShah Can you also provide me with more context on the failure so that I can double check if the failure is addressed by this https://github.com/opensearch-project/common-utils/pull/67 PR.

**Comment by VachaShah** [comment]
@aditjind I think #410 was the issue. May be @peternied can elaborate?

**Comment by peternied** [comment]
I've updated the repro steps on https://github.com/opensearch-project/opensearch-build/issues/410, copied the reproduction steps into this PR for validation

> **To Reproduce**
> 1.  Flush maven local with `rm -rf ~/.m2/` 
> 2. `./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component common-utils --snapshot`
> 3. `ls .m2/repository/org/opensearch/common-utils/`
> 4. Verify that the directory that is created is named `X.X.X.X-SNAPSHOT` and not `X.X.X.X`

**Review by peternied — CHANGES_REQUESTED** [review]
This needs to wait on https://github.com/opensearch-project/common-utils/pull/65 to be before it can be merged

**Comment by dblock** [comment]
I'd like to wait for #386 to get merged too so we can verify that this properly fails rn.

**Comment by dblock** [comment]
@aditjind could you please rebase this?

**Comment by dblock** [comment]
@aditjind could you please rebase this?

**Comment by dblock** [comment]
Well, CI did catch a bug!

https://github.com/opensearch-project/common-utils/pull/69 should fix it

**Review by peternied — APPROVED** [review]
CI is managing final approve now, great work @dblock

**Comment by dblock** [comment]
I re-ran the checks after https://github.com/opensearch-project/common-utils/pull/69 and we're good to go.

**Review by dblock — APPROVED** [review]

**Pull request merged**
