### PR TITLE
Add custom import map plugin to 3.0.0 OSD

### PR DESCRIPTION
**Pull request by junqiu-lei**
Signed-off-by: Junqiu Lei <junqiu@amazon.com>

### Description
Add custom import map plugin to OSD 3.0.0 with correct plugin path.

### Issues Resolved
https://github.com/opensearch-project/dashboards-maps/issues/83

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @junqiu-lei would 2.4.0+ versions fail on this?
Thanks.

**Comment by junqiu-lei** [comment]
@peterzhuamazon Since 2.4.0 branch cut out, in my understand, this change will only effect to OSD builds that using main branch(current 3.0.0 and future versions)

**Comment by gaiksaya** [comment]
Hi @junqiu-lei ,

The question here is if we are to release 2.x or 1.x version in future which are based on respective branches, will this affect those builds?
Also @peterzhuamazon What do you think about moving this script to the respective repo rather than maintaining here which uses same scripts for all branches? In that way the right script will be checkout for right version of the component

**Comment by junqiu-lei** [comment]
@gaiksaya Thanks for explanation. Another potential solution I am thinking is that we can add a conditional check for the version in the script to determine use the right path. The custom import map plugin started release from 2.2.0, so except 2.2.x and 2.3.x and 2.4.x use old path, others versions should use the new path.

**Comment by gaiksaya** [comment]
> @gaiksaya Thanks for explanation. Another potential solution I am thinking is that we can add a conditional check for the version in the script to determine use the right path. The custom import map plugin started release from 2.2.0, so except 2.2.x and 2.3.x and 2.4.x use old path, others versions should use the new path.

That sounds kind of hacky to me. Overtime if would become difficult to maintain as versions go on increasing.
@dblock What do you think?

**Comment by dblock** [comment]
> > @gaiksaya Thanks for explanation. Another potential solution I am thinking is that we can add a conditional check for the version in the script to determine use the right path. The custom import map plugin started release from 2.2.0, so except 2.2.x and 2.3.x and 2.4.x use old path, others versions should use the new path.
> 
> That sounds kind of hacky to me. Overtime if would become difficult to maintain as versions go on increasing. @dblock @prudhvigodithi What do you think?

Move the build script into your repo and all its branches under `scripts/`, then delete it here.

**Review by zelinh — COMMENTED** [review]
@junqiu-lei Hi the build workflow will firstly look for the build script from the current location in our build repo and if it can't find it here, it would look for it in the respective component repo (logic from [here](https://github.com/opensearch-project/opensearch-build/blob/4a3914af5219091bda277e370661e8443aa3436c/src/paths/script_finder.py#L59)). 
As our build repo currently only maintains on main branch, it's hard for us to control any specific `build.sh` changes for different major versions. So we would recommend you to have this build script maintained in your repo so that you could update it specifically in different branches. 
Once it's created there in your component repo, make sure to remove it from here in build repo.

**Comment by junqiu-lei** [comment]
Thanks team's suggestions, today I will talk with @peterzhuamazon for the workable solution.

**Pull request closed without merging**
