### PR TITLE
fix failed jest by unifying cdk versions

### PR DESCRIPTION
**Pull request by tianleh**
Signed-off-by: Tianle Huang <tianleh@amazon.com>

### Description
Fix https://github.com/opensearch-project/opensearch-build/runs/5341305055?check_suite_focus=true
 
Follow up of https://github.com/opensearch-project/opensearch-build/pull/1660

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/runs/5341305055?check_suite_focus=true
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
```
opensearch@5981838b19ee deployment]$   yarn test -- --coverage
yarn run v1.22.15
warning package.json: No license field
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ jest --coverage
 PASS  test/lambdas/cf-url-rewriter/cf-url-rewriter.test.ts
Bundling asset MyTestStack/CfUrlRewriter/Code/Stage...

  ...3b9112600de776682be4ae92d21963b9c98337c2b5288dd26146d5230/index.js  747b 

Bundling asset MyTestStack/CfUrlRewriter/Code/Stage...

  ...a86d968b7b18508cac611d93ece96bb545c09a638b7f0519d5f12454b/index.js  747b 

 PASS  test/build-artifact-stack.test.ts
-----------------------------|---------|----------|---------|---------|-------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------|---------|----------|---------|---------|-------------------
All files                    |   94.91 |      100 |   85.71 |   94.91 |                   
 lambdas/cf-url-rewriter     |      50 |      100 |      50 |      50 |                   
  cf-url-rewriter.ts         |      50 |      100 |      50 |      50 | 9-13              
 lib                         |     100 |      100 |     100 |     100 |                   
  artifacts-public-access.ts |     100 |      100 |     100 |     100 |                   
  buckets.ts                 |     100 |      100 |     100 |     100 |                   
  build-artifact-stack.ts    |     100 |      100 |     100 |     100 |                   
  identities.ts              |     100 |      100 |     100 |     100 |                   
-----------------------------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        4.876 s
Ran all test suites.
Done in 5.59s.
```

**Comment by tianleh** [comment]
Local is working but Github action is failing.

**Review by zelinh — COMMENTED** [review]
Thanks for the fix here! Have you tried if the latest version of aws-cdk v1.146.0 works for this?

**Comment by tianleh** [comment]
@zelinh please help take a look when available.

**Review by gaiksaya — APPROVED** [review]

**Review by zelinh — APPROVED** [review]
Thanks!

**Comment by tianleh** [comment]
Link to main issue https://github.com/opensearch-project/opensearch-build/issues/1492

**Pull request merged**
