### PR TITLE
Add notification to 3.0.0 manifest

### PR DESCRIPTION
**Pull request by bowenlan-amzn**
Signed-off-by: bowenlan-amzn <bowenlan23@gmail.com>

### Description
Notification main branch has been bumped to 3.0.0. https://github.com/opensearch-project/notifications/pull/556

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
I have noticed 2.4.1 manifest check fail https://github.com/opensearch-project/opensearch-build/actions/runs/3785280517/jobs/6435218730

Error
```ci_workflow.ci_check_list_source_ref.MissingRefError: Missing https://github.com/opensearch-project/dashboards-observability.git@tags/2.4.1.0.
```
This is because [dashboards-observability](https://github.com/opensearch-project/dashboards-observability) repo did not create tag 2.4.1.0.

**Comment by prudhvigodithi** [comment]
I have noticed 2.4.1 manifest check fail https://github.com/opensearch-project/opensearch-build/actions/runs/3785280517/jobs/6435218730

Error
```ci_workflow.ci_check_list_source_ref.MissingRefError: Missing https://github.com/opensearch-project/dashboards-observability.git@tags/2.4.1.0.
```
This is because [dashboards-observability](https://github.com/opensearch-project/dashboards-observability) repo did not create tag 2.4.1.0.

**Review by zelinh — COMMENTED** [review]
I think the reason for the test failure is the recent separations for these repos. More details to track. https://github.com/opensearch-project/opensearch-build/issues/3005
We only created tag for the previous `observability` repo and just flip `dashboards-observability` public recently.

**Comment by peterzhuamazon** [comment]
> I think the reason for the test failure is the recent separations for these repos. More details to track. #3005 We only created tag for the previous `observability` repo and just flip `dashboards-observability` public recently.

As @zelinh mentioned this is due to the renaming of the repos.
I am ok to merge this PR as the error is not related.
But we do need to resolve the 2.4.1 manifest errors / issues soon. Thanks.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Merging this PR to unblock notifications for 3.0.0.
Thank you

**Pull request merged**
