### PR TITLE
Update configs and entrypoint for logging.ignoreEnospcError in 2.15.0

### PR DESCRIPTION
**Pull request by Flyingliuhub**
### Description
Update configs and entrypoint for logging.ignoreEnospcError in 2.15.0

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6733

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Should this be on hold until [2.14.0 ](https://github.com/opensearch-project/opensearch-build/issues/4562 )is out or until the RC is finalized ?
@peterzhuamazon @rishabh6788.

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Thanks @Flyingliuhub ,

Block this until 2.14.0 version is out.

Thanks.

**Comment by Flyingliuhub** [comment]
@peterzhuamazon as 

> Thanks @Flyingliuhub ,
> 
> Block this until 2.14.0 version is out.
> 
> Thanks.

@peterzhuamazon 2.14.0 is already out. Can you please help review? Thanks

**Comment by peterzhuamazon** [comment]
Hi @Flyingliuhub , could you add the corresponding config change PR from OSD?

Thanks.

**Comment by Flyingliuhub** [comment]
> Hi @Flyingliuhub , could you add the corresponding config change PR from OSD in PR comments?
> 
> Thanks.

I already mentioned the in the PR comments above for `Issues Resolved` section. did you have a chance to click the link?

**Comment by peterzhuamazon** [comment]
> > Hi @Flyingliuhub , could you add the corresponding config change PR from OSD in PR comments?
> > Thanks.
> 
> I already mentioned the in the PR comments above for `Issues Resolved` section. did you have a chance to click the link?

Missed that, thanks for pointing out.
We will hold this PR for a bit longer in case 2.14.1 is on the way.
Thanks.

**Comment by peterzhuamazon** [comment]
We are ready to merge for #4681 .

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
