### PR TITLE
Make tools scripts of security plugin executable

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Make tools scripts of security plugin executable
 
### Issues Resolved
Closing #120 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Shouldn't this be taken care by the component owner? We might need to make changes for all distributions if not changed in the core plugin.

**Comment by peterzhuamazon** [comment]
> Shouldn't this be taken care by the component owner? We might need to make changes for all distributions if not changed in the core plugin.

I will send another issue to component owner, but we from ourside need to ensure these scripts are still having execution permission. These two things are not duplicate of each other.

**Comment by peterzhuamazon** [comment]
@gaiksaya confirms that the plugin is having 750 for all scripts.
https://github.com/opensearch-project/security/blob/4c182a216954b441cb698fe3f4d07f34a88b6d2f/src/main/assemblies/securityadmin-standalone.xml#L12-L16

The reason it didnt preserve because we didnt use `-p, --preserve-permissions` during untar.
I will change this PR for now.

**Comment by peterzhuamazon** [comment]
After some checking, and talk to Sarat, seems like the perms are being set by the plugin cli during installation:
https://github.com/opensearch-project/OpenSearch/blob/19e54d662488a183c1388e66cfe7463a24c6aa7c/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L188-L193

**Comment by gaiksaya** [comment]
> After some checking, and talk to Sarat, seems like the perms are being set by the plugin cli during installation:
> https://github.com/opensearch-project/OpenSearch/blob/19e54d662488a183c1388e66cfe7463a24c6aa7c/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L188-L193

Can you create a GH issue for this?

**Comment by peterzhuamazon** [comment]
> > After some checking, and talk to Sarat, seems like the perms are being set by the plugin cli during installation:
> > https://github.com/opensearch-project/OpenSearch/blob/19e54d662488a183c1388e66cfe7463a24c6aa7c/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L188-L193
> 
> Can you create a GH issue for this?

https://github.com/opensearch-project/OpenSearch/issues/1220

**Review by gaiksaya — APPROVED** [review]

**Review by bbarani — APPROVED** [review]

**Pull request merged**
