### PR TITLE
Added components to 1.3.8 manifest

### PR DESCRIPTION
**Pull request by Divyaasm**
Signed-off-by: Divya Madala <divyaasm@amazon.com>

### Description
Added components to opensearch and dashboards in 1.3.8 manifest

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by prudhvigodithi — APPROVED** [review]

**Review by zelinh — CHANGES_REQUESTED** [review]
Hey @Divyaasm I think you may need to make sure these component repos have all bumped to 1.3.8 version first. Also for repo like `observability` it looks like they have removed front end code from their original repo so you would also need to remove the `working_directory`

**Comment by Divyaasm** [comment]
> Hey @Divyaasm I think you may need to make sure these component repos have all bumped to 1.3.8 version first. Also for repo like `observability` it looks like they have removed front end code from their original repo so you would also need to remove the `working_directory`

Sure, Thanks Zelin

**Comment by peterzhuamazon** [comment]
> Hey @Divyaasm I think you may need to make sure these component repos have all bumped to 1.3.8 version first. Also for repo like `observability` it looks like they have removed front end code from their original repo so you would also need to remove the `working_directory`

Make sure to discuss with component owner on which exact repo they are using for upcoming 1.x release.
Ex: `reporting` as `dashboards-reports` for the report scheduler OpenSearch Plugin.

Thanks.

**Comment by cwperks** [comment]
Hi @Divyaasm , `security-dashboards-plugin` cannot be bumped to 1.3.8 until `opensearch-security` plugin has been previously been built for 1.3.8 as our integration tests download the zip of the security plugin to run opensearch with security installed. 

PR with failing CI check for `security-dashboards-repo`: https://github.com/opensearch-project/security-dashboards-plugin/pull/1309

**Comment by zelinh** [comment]
I will close this PR for now as I believe we have done these changes in other PRs.

**Pull request closed without merging**
