### PR TITLE
allow find build script by repo component

### PR DESCRIPTION
**Pull request by junqiu-lei**
Signed-off-by: Junqiu Lei <junqiu@amazon.com>

### Description
At [dashboards-maps](https://github.com/opensearch-project/dashboards-maps) repo, it has two OSD plugins, raising this PR in order to allow find correct plugin  build script.

### Issues Resolved
https://github.com/opensearch-project/dashboards-maps/issues/83

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — COMMENTED** [review]
I don't think this is actually needed. We could specify the working directory in the input manifest so the build workflow would know where to find each plugin directory even for a single repo. 
e.g. https://github.com/opensearch-project/opensearch-build/blob/d5b79bc4fd63a1e6cd6f7f29587916eb7493c827/manifests/2.4.0/opensearch-dashboards-2.4.0.yml#L26

**Comment by junqiu-lei** [comment]
Thanks @zelinh's help, I know the working_directory is work for plugin directory, but not sure for the build script directory, can I know what directory we need put build scripts to for the plugin in the plugin repo? Currently we have [custom_import_map](https://github.com/opensearch-project/dashboards-maps/tree/main/custom_import_map), and will release another [maps_dashboards](https://github.com/opensearch-project/dashboards-maps/tree/feature/new-maps/maps_dashboards) plugin at 2.5.0 also under this repo root path.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> I don't think this is actually needed. We could specify the working directory in the input manifest so the build workflow would know where to find each plugin directory even for a single repo. e.g.
> 
> https://github.com/opensearch-project/opensearch-build/blob/d5b79bc4fd63a1e6cd6f7f29587916eb7493c827/manifests/2.4.0/opensearch-dashboards-2.4.0.yml#L26

We need this, the build script calling is not controlled by working directory as the working directory is just a param to the build script.

**Comment by dblock** [comment]
This was merged too fast.

In 2.5 we agreed to https://github.com/opensearch-project/opensearch-plugins/issues/142 whereas all projects that ship multiple plugins from a monorepo are splitting them to avoid this and a series of other problems. Please don't create more nonorepos and revert this change @junqiu-lei.

**Comment by peterzhuamazon** [comment]
> This was merged too fast.
> 
> In 2.5 we agreed to #2188 whereas all projects that ship multiple plugins from a monorepo are splitting them to avoid this and a series of other problems. Please don't create more nonorepos and revert this change @junqiu-lei.

Hi @dblock.

The reason I merged this change is due to 3.0/2.4.1 would get blocked in maps, and this change does not seems to alter the initial behavior while adding a new way to allow repo owners to customize their scripts.

If there is much concern on the approach, I am happy to approve the revert once @junqiu-lei raise it.
Thanks.

**Comment by junqiu-lei** [comment]
Hi @dblock , I just raised the PR to add tests and docs to it, thanks! https://github.com/opensearch-project/opensearch-build/pull/2952

**Pull request merged**
