### PR TITLE
rename stdout_data and stderr_data

### PR DESCRIPTION
**Pull request by tianleh**
Signed-off-by: Tianle Huang <tianleh@amazon.com>

### Description
This is a follow up to address one comment from https://github.com/opensearch-project/opensearch-build/pull/978/files about variable name. 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seraphjiang — APPROVED** [review]

**Comment by dblock** [comment]
Wasn’t this in the context of also renaming output and error to stdout_data and stderr_data?

**Comment by tianleh** [comment]
> Wasn’t this in the context of also renaming output and error to stdout_data and stderr_data? So to distinguish partial and complete results?

Use output as example, do you mean renaming `output` to `stdout` or `stdout_data`? There is a difference here. 

Option 1: `stdout` means that it is a file handler which callers can call `read` function and also check its `mode` (used in unit test).

Option 2: `stdout_data` means it is string data. This will require the `read` call to be inside Process class. On one hand, it simplifies the callers to not make the `read` call. The downside is that the caller cannot easily get its `mode`. Well, I could add two new properties to the Process class. (`stdout_mode`, `stderr_mode`)

Let me know which option you mean. (or Option 3: leave it as it is)

**Comment by dblock** [comment]
> > Wasn’t this in the context of also renaming output and error to stdout_data and stderr_data? So to distinguish partial and complete results?
> 
> Use output as example, do you mean renaming `output` to `stdout` or `stdout_data`? There is a difference here.
> 
> Option 1: `stdout` means that it is a file handler which callers can call `read` function and also check its `mode` (used in unit test).
> 
> Option 2: `stdout_data` means it is string data. This will require the `read` call to be inside Process class. On one hand, it simplifies the callers to not make the `read` call. The downside is that the caller cannot easily get its `mode`. Well, I could add two new properties to the Process class. (`stdout_mode`, `stderr_mode`)
> 
> Let me know which option you mean. (or Option 3: leave it as it is)

I think neither actually. Thinking from the caller point of view, you want the live data while the process is running and complete data after the process ended. Would that simplify the interface?

1. Remove `output` and `error`, never return the handle.
2. Read if process is running and return termination data otherwise.

```python
def stdout_data(self):
   return self.stdout.read() if self.stdout else self.stdout_data
```

WDYT?

**Comment by tianleh** [comment]
> > > Wasn’t this in the context of also renaming output and error to stdout_data and stderr_data? So to distinguish partial and complete results?
> > 
> > 
> > Use output as example, do you mean renaming `output` to `stdout` or `stdout_data`? There is a difference here.
> > Option 1: `stdout` means that it is a file handler which callers can call `read` function and also check its `mode` (used in unit test).
> > Option 2: `stdout_data` means it is string data. This will require the `read` call to be inside Process class. On one hand, it simplifies the callers to not make the `read` call. The downside is that the caller cannot easily get its `mode`. Well, I could add two new properties to the Process class. (`stdout_mode`, `stderr_mode`)
> > Let me know which option you mean. (or Option 3: leave it as it is)
> 
> I think neither actually. Thinking from the caller point of view, you want the live data while the process is running and complete data after the process ended. Would that simplify the interface?
> 
>     1. Remove `output` and `error`, never return the handle.
> 
>     2. Read if process is running and return termination data otherwise.
> 
> 
> ```python
> def Process(self):
>     self.__stdout_data__ = null
> 
> @property
> def stdout_data(self):
>    return self.stdout.read() if self.stdout else self.__stdout_data__
> ```
> 
> WDYT?

Thanks for the detailed explanation. Now I get what you mean. 

Just one additional question, my unit test https://github.com/opensearch-project/opensearch-build/blob/main/tests/tests_system/test_process.py#L22 relies on the file handler to get its open mode. If we do not expose the handler, then I will need to add two more class properties, `stdout_mode` and `stderr_mode`

**Comment by dblock** [comment]
> Just one additional question, my unit test https://github.com/opensearch-project/opensearch-build/blob/main/tests/tests_system/test_process.py#L22 relies on the file handler to get its open mode. If we do not expose the handler, then I will need to add two more class properties, `stdout_mode` and `stderr_mode`

Instead, write another test that mocks `NamedTemporaryFile` and expects a call to it with `mode="r+"`,

**Comment by tianleh** [comment]
Encountered mocking issues for `stdout_data` since it is a property of class instead of a regular method call. Still researching how to properly mock a property.

**Comment by tianleh** [comment]
> Encountered mocking issues for `stdout_data` since it is a property of class instead of a regular method call. Still researching how to properly mock a property.

Fixed with `PropertyMock`

**Review by dblock — APPROVED** [review]

**Pull request merged**
