### PR TITLE
Opensearch data prepper ci docker images

### LINKED ISSUE #1673: [RELEASE] Data Prepper 1.3.0
### Is your feature request related to a problem? Please describe

The Data Prepper team plans to release Data Prepper 1.3.0.

Planned release date: Mar 21, 2022

### Describe the solution you'd like

Release Data Prepper according to the solution described in: https://github.com/opensearch-project/data-prepper/issues/977.

The Jenkins job needs to be created per #1594.

### Describe alternatives you've considered

Manual release as done for Data Prepper 1.2.0 and 1.2.1.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Opensearch data prepper ci docker images
 
### Issues Resolved
#1673
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]

**Comment by gaiksaya** [comment]
I do not see anything specific configuration to data-prepper in this image. Can we make it generalized that can be used by data prepper and/or by any other component?
Per component docker image will increase the maintenance cost. (Same thing why we avoid building/testing of stand-alone components because we do not want to maintain environments in multiple places)

**Comment by peterzhuamazon** [comment]
> I do not see anything specific configuration to data-prepper in this image. Can we make it generalized that can be used by data prepper and/or by any other component? Per component docker image will increase the maintenance cost. (Same thing why we avoid building/testing of stand-alone components because we do not want to maintain environments in multiple places)

I disagree with that sentiment as we already have 6G huge image for opensearch centos7 build image. Each component would have different requirements and it is better if we use smaller images.

Imagine data prepper ask for jdk11, but another component want 14, and one more ask for 17, you are back to the original track of huge image 1 fit all.

The maintenance cost is not huge as we can ask component owner to maintain the image going on. Plus, these images are not being changed very often due to the nature of their release compares to us building opensearch.

You either choose 1 huge image, or choose many smaller images and I think the trade off is expected.

Thanks.

**Review by dlvenable — APPROVED** [review]

**Comment by rishabh6788** [comment]
@peterzhuamazon Can you please combine multiple RUN commands into one as each run command adds a new intermediate layer, hence, increasing the size, see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers. 

Also, please use recommended formatting mentioned here https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

**Comment by prudhvigodithi** [comment]
Having separate docker images per component is the best practice and it will be loosely coupled for next upgrades and releases. This way we can build images specific to component use-case and purpose. Can also be modified/upgraded per image and per component bases in accordingly.

**Comment by dblock** [comment]
There are many good points in the comments, but the truth is that we don't have a strategy for base images. I had opened https://github.com/opensearch-project/opensearch-build/issues/1207 to address that, at the very least I suggest commenting there and deciding what is a must have for this PR and what can be deferred to solving the general problem.

**Review by gaiksaya — APPROVED** [review]
Let's move the discussion to https://github.com/opensearch-project/opensearch-build/issues/1207

**Pull request merged**
