### PR TITLE
Moved source code from python to src.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

It's strange to call a source code folder by the language in which the code is written. I propose `src`.
  
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
> We have source code written in at least two languages: Python and Shell. Where do you propose putting the shell code? Will it also go in `src`?

If there was such a thing, yes, but I think we actually don't.

The way I see it is that today we have "scripts you can invoke", such as `build.sh` and `assemble.sh` in the root of `bundle-workflow` because they can be invoked (not because they are bash scripts), and "scripts that override some behavior that otherwise belongs in projects", which is in `scripts` (not called `bash`).

**Comment by camerski** [comment]
> > We have source code written in at least two languages: Python and Shell. Where do you propose putting the shell code? Will it also go in `src`?
> 
> If there was such a thing as scripts written in shell, yes, but I think we actually don't have any other than scripts that can be invoked.
> 
> The way I see it is that today we have "scripts you can invoke", such as `build.sh` and `assemble.sh` in the root of `bundle-workflow` because they can be invoked (not because they are bash scripts), and "scripts that override some behavior that otherwise belongs in projects", which is in `scripts` (not called `bash`).

The meta-question here is "why is `scripts` not a subdirectory of `src`?" It's all source code.

In any case, I would ask that you defer this change while the codebase is under heavy development. This is a disruptive change that impacts multiple developers with changes in flight, and the cost of rebasing and fixing the inevitable merge conflicts is pretty high. In a week or two we'll be finished with the bulk of those changes and it would make sense to do a big rename at that point.

**Comment by dblock** [comment]
> The meta-question here is "why is `scripts` not a subdirectory of `src`?" It's all source code.

Because it's "data", as in overrides/configures some behavior like a manifest, and not part of the source code of the tool.

> In any case, I would ask that you defer this change while the codebase is under heavy development. This is a disruptive change that impacts multiple developers with changes in flight, and the cost of rebasing and fixing the inevitable merge conflicts is pretty high. In a week or two we'll be finished with the bulk of those changes and it would make sense to do a big rename at that point.

No problem. I'll leave this open.

**Comment by dblock** [comment]
Closing for now, it's just adding noise.

**Pull request closed without merging**
