### PR TITLE
Build security 1.3 branch for 1.3.0 release

### PR DESCRIPTION
**Pull request by cliu123**
Signed-off-by: cliu123 <lc12251109@gmail.com>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]

**Review by bbarani — APPROVED** [review]

**Comment by cliu123** [comment]
CI failed on tests unrelated to this change. @gaiksaya / @bbarani Would you please trigger re-run the CI? I don't have the permission to do that.
```
2022-03-01T18:26:35.0020100Z =========================== short test summary info ============================
2022-03-01T18:26:35.0020630Z FAILED tests/test_run_manifests.py::TestRunManifests::test_main_list - ValueE...
2022-03-01T18:26:35.0021090Z FAILED tests/tests_manifests/test_input_manifests.py::TestInputManifests::test_1_1_0
2022-03-01T18:26:35.0021490Z FAILED tests/tests_manifests/test_input_manifests.py::TestInputManifests::test_latest
2022-03-01T18:26:35.0022130Z FAILED tests/tests_manifests/test_input_manifests.py::TestInputManifests::tests_configs
2022-03-01T18:26:35.0022680Z FAILED tests/tests_manifests_workflow/test_input_manifests_opensearch.py::TestInputManifestsOpenSearch::test_update_with_latest_manifest
```
```
2022-03-01T18:27:34.3850085Z Traceback (most recent call last):
2022-03-01T18:27:34.3866073Z   File "./src/run_ci.py", line 25, in <module>
2022-03-01T18:27:34.3866663Z     sys.exit(main())
2022-03-01T18:27:34.3867086Z   File "./src/run_ci.py", line 21, in main
2022-03-01T18:27:34.3867700Z     CiManifests.from_file(args.manifest, args).check()
2022-03-01T18:27:34.3868665Z   File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_manifests.py", line 27, in from_file
2022-03-01T18:27:34.3869223Z     return cls.__klass(file.name)(file, args)
2022-03-01T18:27:34.3869947Z   File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_input_manifest.py", line 20, in __init__
2022-03-01T18:27:34.3870432Z     super().__init__(InputManifest.from_file(file), args)
2022-03-01T18:27:34.3871183Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/manifest.py", line 35, in from_file
2022-03-01T18:27:34.3871648Z     return loader(yml)
2022-03-01T18:27:34.3872267Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/input_manifest.py", line 104, in __init__
2022-03-01T18:27:34.3872741Z     super().__init__(data)
2022-03-01T18:27:34.3873438Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/component_manifest.py", line 30, in __init__
2022-03-01T18:27:34.3873874Z     super().__init__(data)
2022-03-01T18:27:34.3874564Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/manifest.py", line 111, in __init__
2022-03-01T18:27:34.3875032Z     self.validate(data)
2022-03-01T18:27:34.3876057Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/manifest.py", line 121, in validate
2022-03-01T18:27:34.3876672Z     raise ValueError(f"Invalid manifest schema: {v.errors}")
2022-03-01T18:27:34.3877653Z ValueError: Invalid manifest schema: {'components': [{7: ['no definitions validate', {'anyof definition 0': [{'ref': ['must be of string type']}], 'anyof definition 1': [{'dist': ['required field'], 'ref': ['unknown field'], 'repository': ['unknown field']}]}]}]
```

**Comment by cliu123** [comment]
> CI failed on tests unrelated to this change. @gaiksaya / @bbarani Would you please trigger re-run the CI? I don't have the permission to do that.
> 
> ```
> 2022-03-01T18:26:35.0020100Z =========================== short test summary info ============================
> 2022-03-01T18:26:35.0020630Z FAILED tests/test_run_manifests.py::TestRunManifests::test_main_list - ValueE...
> 2022-03-01T18:26:35.0021090Z FAILED tests/tests_manifests/test_input_manifests.py::TestInputManifests::test_1_1_0
> 2022-03-01T18:26:35.0021490Z FAILED tests/tests_manifests/test_input_manifests.py::TestInputManifests::test_latest
> 2022-03-01T18:26:35.0022130Z FAILED tests/tests_manifests/test_input_manifests.py::TestInputManifests::tests_configs
> 2022-03-01T18:26:35.0022680Z FAILED tests/tests_manifests_workflow/test_input_manifests_opensearch.py::TestInputManifestsOpenSearch::test_update_with_latest_manifest
> ```
> 
> ```
> 2022-03-01T18:27:34.3850085Z Traceback (most recent call last):
> 2022-03-01T18:27:34.3866073Z   File "./src/run_ci.py", line 25, in <module>
> 2022-03-01T18:27:34.3866663Z     sys.exit(main())
> 2022-03-01T18:27:34.3867086Z   File "./src/run_ci.py", line 21, in main
> 2022-03-01T18:27:34.3867700Z     CiManifests.from_file(args.manifest, args).check()
> 2022-03-01T18:27:34.3868665Z   File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_manifests.py", line 27, in from_file
> 2022-03-01T18:27:34.3869223Z     return cls.__klass(file.name)(file, args)
> 2022-03-01T18:27:34.3869947Z   File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_input_manifest.py", line 20, in __init__
> 2022-03-01T18:27:34.3870432Z     super().__init__(InputManifest.from_file(file), args)
> 2022-03-01T18:27:34.3871183Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/manifest.py", line 35, in from_file
> 2022-03-01T18:27:34.3871648Z     return loader(yml)
> 2022-03-01T18:27:34.3872267Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/input_manifest.py", line 104, in __init__
> 2022-03-01T18:27:34.3872741Z     super().__init__(data)
> 2022-03-01T18:27:34.3873438Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/component_manifest.py", line 30, in __init__
> 2022-03-01T18:27:34.3873874Z     super().__init__(data)
> 2022-03-01T18:27:34.3874564Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/manifest.py", line 111, in __init__
> 2022-03-01T18:27:34.3875032Z     self.validate(data)
> 2022-03-01T18:27:34.3876057Z   File "/home/runner/work/opensearch-build/opensearch-build/src/manifests/manifest.py", line 121, in validate
> 2022-03-01T18:27:34.3876672Z     raise ValueError(f"Invalid manifest schema: {v.errors}")
> 2022-03-01T18:27:34.3877653Z ValueError: Invalid manifest schema: {'components': [{7: ['no definitions validate', {'anyof definition 0': [{'ref': ['must be of string type']}], 'anyof definition 1': [{'dist': ['required field'], 'ref': ['unknown field'], 'repository': ['unknown field']}]}]}]
> ```

@gaiksaya Do you have the permission to re-run CI?

**Comment by gaiksaya** [comment]
> @gaiksaya Do you have the permission to re-run CI?

I did rerun, it failed with same error

**Review by zelinh — COMMENTED** [review]
I think you should quote it like `1.3`?

**Review by zelinh — APPROVED** [review]
Thanks!

**Pull request merged**
