### PR TITLE
Data Prepper Unit Test & Test Refactoring

### LINKED ISSUE #1450: Jenkins Jobs should be able to be unit tested
### Is your feature request related to a problem? Please describe

This project's current Jenkins unit tests are testing Jenkins libraries. These tests create fake Jenkinsfile jobs which exercise library code. The goal is to ensure the behavior of the library code is consistent.

I would like to add a unit test for the Data Prepper artifacts build. I believe this test shouldn't need to know the details of the library code which it uses. For example, the test should just know that `signArtifacts` was called. It should not care that `signArtifacts`  calls `sh` or uses `withCredentials`. Those are implementation details of `signArtifacts`.

The current problem is that a test cannot successfully `registerAllowedMethod` on library code. This is because `BuildPipelineTest` [registers the library](https://github.com/opensearch-project/opensearch-build/blob/main/tests/jenkins/BuildPipelineTest.groovy#L26-L34).

### Describe the solution you'd like

I propose a simple refactoring to solve this issue:

1. Create a new base class `CommonPipelineTest`. It would not perform any setup. But, it will have the `testPipeline` method.
2. Make `BaseJobPipelineTest` a sub-class of `CommonPipelineTest`
3. (Optional) Create a new base class `BaseJobPipelineTest` which performs the bare minimal setup for testing an actual job. This minimum is mocking the call to load the library.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

This PR has two significant changes. I considered making two PRs, but I believe combining them will convey the idea best.

The first change is a possible solution to #1450. Please read that issue to understand this PR.

The second change is the Data Prepper unit test itself. This unit test has no detailed information on what `signArtifacts` or `uploadToS3` do.
 
### Issues Resolved

#1450 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Do other tests need to be refactored to use this?

**Comment by dlvenable** [comment]
> Do other tests need to be refactored to use this?

@dblock , All the other tests were already inheriting from `BuildPipelineTest`. I retained all the functionality from that test. So the other tests do not need to be refactored.

**Review by peternied — COMMENTED** [review]
I like how this type of test is focused only on the data prepper job and asserts `are you sure the change you added to DP workflow does what you expect?`  You've set a new bar for the new regression tests that I'm going to add in future.

**Review by gaiksaya — APPROVED** [review]
Great enhancement 🙌  Thanks!

**Comment by abhinavGupta16** [comment]
This definitely simplifies the jenkins job test. The only issue I see with this approach is that, if a breaking change occurs in any library from vars, none of the job regression test files will change or fail. We would never know the blast radius of the changes we make to the libraries with is dangerous. Even more so since the only time we'll realize something went wrong is when the job is run on jenkins, which is mostly during a release.

Not abstracting the library would force us developer to change all the test cases associated to all the existing job ensuring that the the developer is well aware of the blast radius and has tested the jobs affected. 

This therefore brings the question - should we be abstracting all the libraries in a job?

@peternied @gaiksaya @dblock thoughts?

**Comment by abhinavGupta16** [comment]
> This definitely simplifies the jenkins job test. The only issue I see with this approach is that, if a breaking change occurs in any library from vars or any other change that may affect a job, none of the job regression test files will change or fail. We would never know the blast radius of the changes we make to the libraries with is dangerous. Even more so since the only time we'll realize something went wrong is when the job is run on jenkins, which is mostly during a release.
> 
> Not abstracting the library would force us developer to change all the test cases associated to all the existing job ensuring that the the developer is well aware of the blast radius and has tested the jobs affected.
> 
> This therefore brings the question - should we be abstracting all the libraries in a job and follow this model? If not, the prev approach tests by not abstracting our libraries.
> 
> @peternied @gaiksaya @dblock thoughts?

Posting this comment on the issue and reopening it.

**Pull request merged**
