### PR TITLE
Update ci image to newer version

### PR DESCRIPTION
**Pull request by tianleh**
### Description
During research this bug https://github.com/opensearch-project/opensearch-build/issues/1713 , realize that the current images are quite old. After syncing up with @peterzhuamazon , we shall use the newer one https://hub.docker.com/layers/opensearchstaging/ci-runner/ci-runner-centos7-v1/images/sha256-b75fbe7441982791cbc7b7b96cfefbbcabb2b8e4fc9c4f22d64c3bc0f0d6e572?context=explore
 
### Issues Resolved
Resolves https://github.com/opensearch-project/opensearch-build/issues/1713
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
will rerun the checks once https://github.com/opensearch-project/job-scheduler/pull/134 is merged

**Comment by tianleh** [comment]
https://github.com/opensearch-project/opensearch-build/runs/5458140249?check_suite_focus=true failed due to job scheduler

**Review by dblock — APPROVED** [review]

**Comment by kavilla** [comment]
I believe this will fail OSD 2.0.0 builds since the NODE ENV version is 10.24.1 but OSD 2.0.0 requires Node 14.18.2

**Comment by tianleh** [comment]
> I believe this will fail OSD 2.0.0 builds since the NODE ENV version is 10.24.1 but OSD 2.0.0 requires Node 14.18.2

Good call out! Let me revert OSD 2.0.0

**Comment by tianleh** [comment]
> I believe this will fail OSD 2.0.0 builds since the NODE ENV version is 10.24.1 but OSD 2.0.0 requires Node 14.18.2

cc @peterzhuamazon

**Pull request merged**
