### PR TITLE
Add dashboards-flow-framework to build repo

### PR DESCRIPTION
**Pull request by saimedhi**
### Description
Add dashboards-flow-framework to build repo

### Issues Resolved
Related to #4851 

#### dashboards-flow-framework plugin is expected to release with OpenSearch 2.17. 
In the manifests, 2.17 is not yet added. So, after that gets added need to add below code to it.
```
 - name: flowFrameworkDashboards
    repository: https://github.com/opensearch-project/dashboards-flow-framework.git
    ref: 2.x

```
#### Plugin is not yet stable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ohltyler** [comment]
LGTM - @prudhvigodithi regarding this plugin, it is not in a fully stable state or have integ tests configured yet; is there any concern in onboarding to the main/3.0 builds? Additionally, is there anything we need to track to automatically onboard to 2.17 release when that is kickstarted and the manifests are available? We do not plan to include this in 2.16.

**Comment by saimedhi** [comment]
> LGTM - @prudhvigodithi regarding this plugin, it is not in a fully stable state or have integ tests configured yet; is there any concern in onboarding to the main/3.0 builds? Additionally, is there anything we need to track to automatically onboard to 2.17 release when that is kickstarted and the manifests are available? We do not plan to include this in 2.16.

@prudhvigodithi, 
- Added plugin to the opensearch-plugins meta https://github.com/opensearch-project/opensearch-plugins/pull/237
- Updated manifest 3.0.0 to include plugin https://github.com/opensearch-project/opensearch-build/pull/4852
- Need to update manifest 2.17.0 to include plugin 
- Please let me know if any further action is needed to onboard the dashboards-flow-framework to the build repo. Thank you.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
LGTM, please onboard to `manifests/3.0.0/opensearch-dashboards-3.0.0-test.yml` as well.
Thanks
Adding @peterzhuamazon @gaiksaya

**Comment by peterzhuamazon** [comment]
Would need to open a new PR to add to 2.17 once 2.16 is release.

Thanks.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Also note if your plugin has a new feature flag, experimental flag, or similar you need to add them to docker entrypoint.
But that is another story entirely.

Will check then.

**Comment by gaiksaya** [comment]
Hi @saimedhi 

Can you please resolve the merge conflict?

**Comment by Divyaasm** [comment]
> Hi @saimedhi
> 
> Can you please resolve the merge conflict?

Done! We can merge once the checks pass @gaiksaya

**Comment by gaiksaya** [comment]
@peterzhuamazon Looks like there is a bug with manifest-ci-check. It won't run the runs for updated commits. Just the initial ones.

**Pull request merged**
