### PR TITLE
Adds async search plugin ref '1.2' to manifest 1.2.0

### PR DESCRIPTION
**Pull request by eirsep**
Signed-off-by: Surya Nistala <snistala@amazon.com>

### Description
Adds async search plugin ref '1.2' to manifest 1.2.0

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]

**Review by gaiksaya — CHANGES_REQUESTED** [review]
There is no 1.2 branch on the async repo. Hence CI is failing.

**Comment by peternied** [comment]
Hmm, something is going very wrong here

```
2021-11-09 22:08:37 INFO     Executing "git fetch --depth 1 origin 1.2" in /tmp/tmpqwl5t_5j/asynchronous-search
2021-11-09 22:08:37 ERROR    Error building asynchronous-search, retry with: ./build.sh manifests/1.2.0/opensearch-1.2.0.yml --component asynchronous-search
Traceback (most recent call last):
  File "./src/run_build.py", line 65, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 52, in main
    builder.checkout(work_dir.name)
  File "/local/home/petern/git/opensearch-build/src/build_workflow/builder_from_source.py", line 26, in checkout
    self.component.working_directory,
  File "/local/home/petern/git/opensearch-build/src/git/git_repository.py", line 33, in __init__
    self.__checkout__()
  File "/local/home/petern/git/opensearch-build/src/git/git_repository.py", line 46, in __checkout__
    self.execute_silent(f"git fetch --depth 1 origin {self.ref}", self.dir)
  File "/local/home/petern/git/opensearch-build/src/git/git_repository.py", line 66, in execute_silent
    stderr=subprocess.DEVNULL,
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git fetch --depth 1 origin 1.2' returned non-zero exit status 128.
```

**Comment by peternied** [comment]
Root cause was that the `1.2` branch was deleted in the remote repo, its been recreated and I've retriggered the checks.

**Comment by peternied** [comment]
> There is no 1.2 branch on the async repo. Hence CI is failing.

@gaiksaya Good catch, should be created now

**Review by gaiksaya — APPROVED** [review]

**Review by peternied — APPROVED** [review]

**Pull request merged**
