### PR TITLE
feat: add experimental feature flag for dashboards-assistant plugin

### LINKED ISSUE #4361: Add dashboards-assistant experimental config into opensearch-dashboards.yml file.
We are going to onboard a new dashboard plugin: `dashboards-assistant` into our build process and it will be experimental on 2.12.

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
### Description
_Describe what this change achieves._

### Issues Resolved
#4361 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by jordarlu** [comment]
Adding @peterzhuamazon, @gaiksaya and @prudhvigodithi for the comments, thanks !!

**Comment by prudhvigodithi** [comment]
LGTM, are we still using this `opensearch_dashboards-default.x.yml` @peterzhuamazon ?
Thanks

**Comment by peterzhuamazon** [comment]
> LGTM, are we still using this `opensearch_dashboards-default.x.yml` @peterzhuamazon ? Thanks

We are for 3.x right no.

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
Block until this comment is resolved:
https://github.com/opensearch-project/opensearch-build/pull/4362#issuecomment-1906652166

**Comment by SuZhou-Joe** [comment]
@peterzhuamazon Thanks and done.

**Review by peterzhuamazon — APPROVED** [review]
I realize there is changes missed for the default entrypoint as well.

@prudhvigodithi please co-review on this one here. Thanks.

**Review by prudhvigodithi — APPROVED** [review]

**Pull request merged**
