### PR TITLE
remove sub working directory for gantt-chart

### PR DESCRIPTION
**Pull request by joshuali925**
### Description
after https://github.com/opensearch-project/dashboards-visualizations/pull/321, there will be no need to specify build script and working directory.

This is tested on fork using `./build.sh manifests/3.0.0/opensearch-dashboards-3.0.0.yml --component OpenSearch-Dashboards ganttChartDashboards`. tested on 3.0.0, 2.12.0, 1.3.14

Note
---
In all future release versions (>=3.0.0, >=2.12.0, >=1.3.15), the manifest file should not include `working_directory: gantt-chart`. This seems to be done manually (e.g. https://github.com/opensearch-project/opensearch-build/pull/4264). cc. @zelinh 

---
### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by joshuali925** [comment]
converting to draft until https://github.com/opensearch-project/dashboards-visualizations/pull/321 gets merged

**Review by derek-ho — APPROVED** [review]
Nice, do we want to make the change for 2.12?

**Comment by joshuali925** [comment]
> Nice, do we want to make the change for 2.12?

replied in https://github.com/opensearch-project/dashboards-visualizations/pull/321#issuecomment-1911225776

**Comment by vamsi-amazon** [comment]
LGTM

**Review by gaiksaya — APPROVED** [review]
@prudhvigodithi Any objections to merge this?

**Pull request merged**
