### PR TITLE
Remove typed-ast as it is deprecated

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Remove typed-ast as it is deprecated

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-build/issues/5054

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Let's not merge until 2.17.1 is out please?

**Comment by peterzhuamazon** [comment]
> Let's not merge until 2.17.1 is out please?

Yes will wait.

**Comment by peterzhuamazon** [comment]
We can merge it now as 2.17.1 is released.
@gaiksaya 

Thanks.

**Review by gaiksaya — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
The mend failure is unrelated here.

Thanks.

**Pull request merged**
