### PR TITLE
Fix location in bundle manifest and update artifacts upload logic

### PR DESCRIPTION
**Pull request by tianleh**
### Description

We notice that the location field of bundle manifest has wrong url where distribution string is doubled. (after https://github.com/opensearch-project/opensearch-build/pull/1807/files is merged)

E.g download this file https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/2004/linux/arm64/rpm/dist/opensearch/manifest.yml

Screen Shot 2022-04-07 at 9 12 57 PM

Also the artifact promotion logic needs to have a distribution in the path. Per @peterzhuamazon  's suggestion, we rename the file to `promoteTarArtifacts` for clarity.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tianleh** [comment]
Tested in my Jenkins [job](http://jenki-jenki-fpgmrv2ryxko-1366042710.us-east-1.elb.amazonaws.com/job/Playground/job/tianleh-test/job/tianleh-os-4-7/9/flowGraphTable/)

https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianleh-os-4-7/3.0.0/9/linux/x64/tar/dist/opensearch/opensearch-3.0.0-linux-x64.tar.gz

https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianleh-os-4-7/3.0.0/9/linux/x64/tar/dist/opensearch/manifest.yml

Verify that the url no longer has double distribution strings.

Screen Shot 2022-04-07 at 9 12 57 PM

**Comment by gaiksaya** [comment]
Hi @tianleh This will be breaking change for website too right? Do we need to create an issue with website repo to let me know this? Also are we planing to backport other versions in `/tar` folder too?

**Comment by tianleh** [comment]
> Hi @tianleh This will be breaking change for website too right? Do we need to create an issue with website repo to let me know this? Also are we planing to backport other versions in `/tar` folder too?

I think the official announcement will be part of the overall RPM launch. As far as I know, no plan to backfill. cc @bbarani @peterzhuamazon

**Review by bbarani — APPROVED** [review]

**Comment by tianleh** [comment]
> Hi @tianleh This will be breaking change for website too right? Do we need to create an issue with website repo to let me know this? Also are we planing to backport other versions in `/tar` folder too?

For the `website`, we are not changing the logic to production url. We only change the staging CI url.

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
