### PR TITLE
Fix remaining CVEs, remove jcenter and netbeans maven

### PR DESCRIPTION
**Pull request by dblock**
### Description

Fixing remaining Whitesource CVEs by either declaring Jenkins plugin versions or force-resolving dependencies.
  
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Somehow the whitesource base scan is 20+ days old.
https://github.com/opensearch-project/opensearch-build/runs/4498723542

**Comment by dblock** [comment]
I got [a ticket #00084156](https://whitesourcesoftware.force.com/SupportPortal/s/case/5005p00002cd4rMAAQ/whitesource-running-against-an-old-baseline) open with Whitesource on the wrong baseline in this PR.

**Review by tianleh — APPROVED** [review]

**Review by zelinh — APPROVED** [review]
Thanks!

**Comment by zelinh** [comment]
Did you trigger the update on the baseline CVEs?

**Comment by dblock** [comment]
> Did you trigger the update on the baseline CVEs?

Did not do anything about that. Is that something we need to do manually? I thought it's something WhiteSource would do automatically by saying "main = baseline"?

**Comment by zelinh** [comment]
> > Did you trigger the update on the baseline CVEs?
> 
> Did not do anything about that. Is that something we need to do manually? I thought it's something WhiteSource would do automatically by saying "main = baseline"?

No I don't think we should do anything. I'm glad to see WhiteSource updated it on their own automatically.

**Pull request merged**
