### PR TITLE
Organized folder structure for all 3 tests

### PR DESCRIPTION
**Pull request by owaiskazi19**
Signed-off-by: Owais Kazi <owaiskazi19@gmail.com>

### Description
Organized all 3 tests in `test_workflow` for better understanding
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
I saw you opened an issue and then put up a PR for it. Are we following this convention? I think just the PR is perfectly fine!

**Comment by owaiskazi19** [comment]
> I saw you opened an issue and then put up a PR for it. Are we following this convention? I think just the PR is perfectly fine, we can open issues for things that aren't incoming and we don't want to forget.

I opened the issue to keep the track. I'll go ahead and close the issue if it's not required.

**Comment by dblock** [comment]
Did you also want to create a matching tree structure in `tests`? Probably yes.

**Review by dblock — APPROVED** [review]

**Review by setiah — APPROVED** [review]
LGTM. Thanks!

**Review by saratvemulapalli — APPROVED** [review]

**Pull request merged**
