### PR TITLE
Modify yaml linter to enforce double quotes

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
We had inconsistencies in yamls through out the repo with single and double quotes especially the manifests.
Added the config in `.yamllint` that will check during CI now.
 
### Issues Resolved
https://github.com/opensearch-project/opensearch-build/pull/1734#issuecomment-1063460367
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Given the amount of changes, shouldn't we be going with a single quote? 

Another argument for single quote is that the convention in many languages is that you cannot expand anything inside single quotes, it's a final string (e.g. `f"v{version}"` in Python or "#{var}" in Ruby).

**Comment by peterzhuamazon** [comment]
I have no issue with both single and double quotes.
single quotes used for simple string and double quotes for substitution is what I normally do.

Thanks.

**Comment by gaiksaya** [comment]
> Given the amount of changes, shouldn't we be going with a single quote? Would that change be smaller?
> 
> Another argument for single quote is that the convention in many languages is that you cannot expand anything inside single quotes, it's a final string (e.g. `f"v{version}"` in Python or `"#{var}"` in Ruby).

I prefer single quotes as well. Will make the change

**Comment by gaiksaya** [comment]
Made the changes here in new PR: https://github.com/opensearch-project/opensearch-build/pull/1742 was much easy.
closing this PR

**Pull request closed without merging**
