### PR TITLE
[Release 1.3.5] Temp fix bug with `build.sh`

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Temporary fix to add an if condition for `build.sh` to make sure for 1.3.5 `publishPluginZipPublicationToZipStagingRepository` task is not executed.

Long term:
Should remove this `if` condition once the `1.3.x` reaches EOL or once the [branching strategy](https://github.com/opensearch-project/opensearch-build/issues/1975) is in place, this should be resolved

Note: changing the `CREATE_GITHUB_ISSUE` to false until the issue gets fixed
`java.io.FileNotFoundException: /var/jenkins/workspace/distribution-build-opensearch/manifests/1.3.5/opensearch-1.3.5.yml does not `

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/2470

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Test: `./build.sh manifests/1.3.5/opensearch-1.3.5.yml --component performance-analyzer --snapshot`
Result :
```
BUILD SUCCESSFUL in 56s
16 actionable tasks: 16 executed
++ find . -path '*build/distributions/*.zip'
+ zipPath=./build/distributions/opensearch-performance-analyzer-1.3.5.0-SNAPSHOT.zip
++ dirname ./build/distributions/opensearch-performance-analyzer-1.3.5.0-SNAPSHOT.zip
+ distributions=./build/distributions
+ echo 'COPY ./build/distributions/*.zip'
COPY ./build/distributions/*.zip
+ mkdir -p builds/plugins
+ cp ./build/distributions/opensearch-performance-analyzer-1.3.5.0-SNAPSHOT.zip ./builds/plugins
+ MAVEN_ZIP_PUBLISH_TASK=publishPluginZipPublicationToZipStagingRepository
+ ./gradlew tasks --all
+ grep -qw '^publishPluginZipPublicationToZipStagingRepository'
+ echo 'Not running publishPluginZipPublicationToZipStagingRepository'
Not running publishPluginZipPublicationToZipStagingRepository
2022-08-17 12:33:53 INFO     Recording plugins artifact for performance-analyzer: plugins/opensearch-performance-analyzer-1.3.5.0-SNAPSHOT.zip (from /tmp/tmp7pdhgxro/performance-analyzer/builds/plugins/opensearch-performance-analyzer-1.3.5.0-SNAPSHOT.zip)
2022-08-17 12:33:53 INFO     Checked /tmp/tmp7pdhgxro/performance-analyzer/builds/plugins/opensearch-performance-analyzer-1.3.5.0-SNAPSHOT.zip (1.3.5.0-SNAPSHOT)
2022-08-17 12:33:53 INFO     Created build manifest /usr/share/opensearch/git/pg/opensearch-build/tar/builds/opensearch/manifest.yml
2022-08-17 12:33:53 INFO     Done.
```

**Review by rishabh6788 — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Test: `/build.sh manifests/2.2.0/opensearch-2.2.0.yml --component performance-analyzer --snapshot`

Result
```
BUILD SUCCESSFUL in 1m 2s
27 actionable tasks: 27 executed
+ mkdir -p builds/plugins
+ cp ./build/distributions/opensearch-performance-analyzer-2.2.0.0-SNAPSHOT.zip builds/plugins
+ ./gradlew publishPluginZipPublicationToZipStagingRepository -Dopensearch.version=2.2.0-SNAPSHOT -Dbuild.snapshot=true -Dbuild.version_qualifier=
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.1
  OS Info               : Linux 5.4.204-124.362.amzn2int.x86_64 (amd64)
  JDK Version           : 17 (Eclipse Temurin JDK)
  JAVA_HOME             : /opt/java/openjdk-17
  Random Testing Seed   : A5A072C13AC017AB
  In FIPS 140 mode      : false
=======================================
```

**Review by dblock — CHANGES_REQUESTED** [review]
There are 8 unrelated commits in the history in this PR, please rebase.

**Comment by dblock** [comment]
I'm very opposed to this fix, because it will hide errors and long term will leave 1.3 branch unbuildable. It's nowhere near EOL. Can we please commit a working `build.sh` in each component's repo in 1.3 instead?

**Comment by prudhvigodithi** [comment]
> I'm very opposed to this fix, because it will hide errors and long term will leave 1.3 branch unbuildable. It's nowhere near EOL. Can we please commit a working `build.sh` in each component's repo in 1.3 branches instead? That seems like an actual fix, as opposed to a workaround proposed here.

I'm afraid, it could impact the release timeline, as based on the failure per component the script has to be added to the component repo.
CC @bbarani

**Comment by dblock** [comment]
> > I'm very opposed to this fix, because it will hide errors and long term will leave 1.3 branch unbuildable. It's nowhere near EOL. Can we please commit a working `build.sh` in each component's repo in 1.3 branches instead? That seems like an actual fix, as opposed to a workaround proposed here.
> 
> I'm afraid, it could impact the release timeline, as based on the failure per component the script has to be added to the component repo. @dblock CC @bbarani

How so? How many components are in this state? These are trivial additions to the repos. Raise PRs.

**Comment by prudhvigodithi** [comment]
I see for performance-analyzer, performance-analyzer-rca, asynchronous-search, anomaly-detection, index-management, dashboard-reports(reports-scheduler), observability, sql components does have the `build.sh` and uses the default one.

**Comment by prudhvigodithi** [comment]
I have raised the PR's for each missing component to to add `build.sh`
https://github.com/opensearch-project/performance-analyzer/pull/252
https://github.com/opensearch-project/asynchronous-search/pull/170
https://github.com/opensearch-project/index-management/pull/470
https://github.com/opensearch-project/performance-analyzer/pull/252
https://github.com/opensearch-project/anomaly-detection/pull/641
https://github.com/opensearch-project/cross-cluster-replication/pull/481
https://github.com/opensearch-project/dashboards-reports/pull/426
https://github.com/opensearch-project/observability/pull/945
https://github.com/opensearch-project/sql/pull/766

**Pull request closed without merging**
