### PR TITLE
Updating branch for OpenSearch Dashboards 1.2

### PR DESCRIPTION
**Pull request by seanneumann**
Updating the manifest for Dashboards 1.2 release.

Signed-off-by: Neumann <neumanns@amazon.com>
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by tmarkley** [comment]
I think we need to make a change to our [`package.json`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.2/package.json#L15)?

**Comment by dblock** [comment]
Rebase this on top of #876, I think this is an unrelated failure.

**Comment by dblock** [comment]
Rebase this on top of #876, I think this is an unrelated failure.

**Comment by seanneumann** [comment]
✅ rebased

**Review by dblock — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]
Thanks.

**Pull request merged**
