### PR TITLE
Create 2.15.0 test manifest + add async search bwc tests

### PR DESCRIPTION
**Pull request by finnegancarroll**
Signed-off-by: Finn Carroll <carrofin@amazon.com>

### Description
Create a test manifest for 2.15.0
Add async search bwc tests to 2.15.0 manifest

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zelinh — COMMENTED** [review]
Hey @finnegancarroll, we haven't confirmed the BWC tests are running accurately on 3.0 as we don't really expect major version backward compatible. Right now we believe adding bwc tests to 2.x manifest should be the most reasonable.

**Comment by finnegancarroll** [comment]
Thanks @zelinh! I've created a test manifest for 2.15.0 and enabled the async search bwc tests there. Let me know if this is not the appropriate location.

**Comment by peterzhuamazon** [comment]
I will add the osd test manifest later in this PR and merge together.
Thanks.

**Review by zelinh — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Hi @finnegancarroll ,

I added back the mistakenly deleted flow-framework section and also add a new OSD test manifest.
@zelinh could you help with the approval?

Thanks

**Pull request merged**
