### PR TITLE
rename kibanaserver to dashboardserver

### PR DESCRIPTION
**Pull request by saravanan30erd**
Refer: https://github.com/opensearch-project/security/pull/1443

Description: Rename kibanaserver to dashboardserver

### CODE REVIEW

**Comment by saravanan30erd** [comment]
@peterzhuamazon @TheAlgo  Please review it.

**Comment by dblock** [comment]
Should it be dashboardS to match the new name?

**Comment by peterzhuamazon** [comment]
We are still in discussion with Security Team on this @saravanan30erd please hold on for some time before we make a decision on this.

Thanks.

**Comment by peterzhuamazon** [comment]
Will close this PR as security will not rename in 1.1.0.

**Pull request closed without merging**
