### PR TITLE
OpenSearch Release Process: Fix wrong links.

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
OpenSearch Release Process: Fix wrong links. 

### Issues Resolved
Coming from https://github.com/opensearch-project/opensearch-build/pull/3635

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Looks like this workflow is not getting triggerd: https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/link-checker.yml

@prudhvigodithi Can you fix that too? Add `main` under push

**Comment by prudhvigodithi** [comment]
> Looks like this workflow is not getting triggerd: https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/link-checker.yml
> 
> @prudhvigodithi Can you fix that too? Add `main` under push

It already has `on: push:`, let me see why its not getting triggered.

**Comment by prudhvigodithi** [comment]
Works now @gaiksaya, please check.

**Review by gaiksaya — APPROVED** [review]
Thanks for fixing the link checker too.

**Pull request merged**
