### PR TITLE
Added support for custom install scripts.

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@amazon.com>

### Description

Introduces `install.sh` that will run during installation of plugins.

### Issues Resolved

Closes https://github.com/opensearch-project/opensearch-build/issues/251
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I think we should keep custom build.sh and install.sh together under the same folder for components, so maybe as a next step I'll rename `scripts/bundle-build` to just `scripts` and `standard-gradle-build` to `default`. WDYT?

**Comment by mch2** [comment]
I'd been working on a slightly different version here - https://github.com/opensearch-project/opensearch-build/pull/268
It works nicely with k-nn but still working on assembling performance-analyzer properly.

The key difference here is there is no default script, it executes it as an additional bundle step if there is a script at path.

**Review by mch2 — APPROVED** [review]
I prefer this to my draft impl.  Your implementation in install.sh is cleaner, I forgot we already had libs on the artifact path.

**Review by peternied — APPROVED** [review]
> I think we should keep custom build.sh and install.sh together under the same folder for components, so maybe as a next step I'll rename scripts/bundle-build to just scripts and standard-gradle-build to default. WDYT?

I like this approach and the naming convention  - make it so!

**Pull request merged**
