### PR TITLE
Add CCR integ tests to the test manifest

### PR DESCRIPTION
**Pull request by ankitkala**
Signed-off-by: Ankit Kala <ankikala@amazon.com>

### Description
Add CCR integ tests to the test manifest.

### Issues Resolved
[383](https://github.com/opensearch-project/cross-cluster-replication/issues/383)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@ankitkala You've asked offline where to add this, would you please check that it's documented properly in this repo?

**Comment by ankitkala** [comment]
I also need help with verifying the tests end to end once. Currently the integ tests in the Jenkins have been failing consistently.

**Comment by dblock** [comment]
@bbarani help direct this?

**Comment by ankitkala** [comment]
Also the test `check manifests/2.0.0/opensearch-2.0.0.yml` is failing. Doesn't seems to be related to this PR though.

**Comment by peterzhuamazon** [comment]
> Also the test `check manifests/2.0.0/opensearch-2.0.0.yml` is failing. Doesn't seems to be related to this PR though.

2.0.0 failure expected for now as not all plugin owners remove rc1.

**Comment by ankitkala** [comment]
> > Also the test `check manifests/2.0.0/opensearch-2.0.0.yml` is failing. Doesn't seems to be related to this PR though.
> 
> 2.0.0 failure expected for now as not all plugin owners remove rc1.

Thanks for confirming @peterzhuamazon . In that case, can you help me with merging this PR pls?

**Pull request merged**
