### PR TITLE
Add AD manifest for 2.3.1 and 3.0.0

### PR DESCRIPTION
**Pull request by jackiehanyang**
Signed-off-by: Jackie Han <jkhanjob@gmail.com>

### Description
Add AD manifest for 2.3.1 and 3.0.0 for this campaign - https://github.com/opensearch-project/opensearch-plugins/issues/142

### Issues Resolved
https://github.com/opensearch-project/opensearch-plugins/issues/142

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ohltyler — APPROVED** [review]

**Review by ylwu-amzn — APPROVED** [review]
For 3.0, there are some breaking changes in OpenSearch core. Make sure the breaking changes fixed in AD.

**Comment by jackiehanyang** [comment]
> For 3.0, there are some breaking changes in OpenSearch core. Make sure the breaking changes fixed in AD.

breaking changes are all fixed for AD. AD CI all passed

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Looks like common-utils build is failing for 3.0.0
Related issue: https://github.com/opensearch-project/common-utils/issues/296

**Comment by peterzhuamazon** [comment]
Merging now as it is not related to AD.

**Pull request merged**
