### PR TITLE
Retro update 2.12

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
Retroactively update 2.12 release notes for security plugin with JWT library change

### Issues Resolved
Closes: https://github.com/opensearch-project/security/issues/4617

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Hi @derek-ho Can you please rebase with main? The link-checker should be fixed.

**Comment by derek-ho** [comment]
> 1a4b876

Done in: [1a4b876](https://github.com/opensearch-project/opensearch-build/pull/5078/commits/1a4b8765e0b8e5452be851a55788ec61b5097f23)

**Comment by derek-ho** [comment]
> Hi @derek-ho Can you please rebase with main? The link-checker should be fixed.

Done in: [1a4b876](https://github.com/opensearch-project/opensearch-build/pull/5078/commits/1a4b8765e0b8e5452be851a55788ec61b5097f23)

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Unrelated whitesource failure. Merging this PR.

**Pull request merged**
