### PR TITLE
Updated license header checker to Deno License Checker

### PR DESCRIPTION
**Pull request by hitenshKharva**
### Description
- Changed License Header Checker to  [Deno License Checker](https://github.com/kt3k/deno_license_checker)

### Issues Resolved
 - https://github.com/opensearch-project/opensearch-build/issues/3079

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by DarshitChanpura — COMMENTED** [review]
Looks good. Will take another pass once it is ready for review.

**Comment by peterzhuamazon** [comment]
What is the reason to bump the version of this if not needed? @hitenshKharva ?

Thanks.

**Comment by hitenshKharva** [comment]
Updated the workflow call to the [](https://github.com/kt3k/deno_license_checker) and updated config to check all the files except `md yml json`
@peterzhuamazon @Divyaasm We have a lot of files failing the license checker test. Let me know if you wish to exclude any other file extensions from the wokflow check.

**Comment by peterzhuamazon** [comment]
Thanks @hitenshKharva 
Looks great.

cc @bbarani @gaiksaya into this conversation.

I feel like it would be beneficial to add license info to all the files except the ones in the new ignore list.
Let me know what you think.

Thanks.

**Comment by gaiksaya** [comment]
Looking at the [workflow run](https://github.com/opensearch-project/opensearch-build/actions/runs/6515597162/job/17698202164?pr=4118) we can ignore below files: 
* .txt
* .config
* .swp
* Ignore entire folder tests/tests_test_workflow/test_integ_workflow/integ_test/data/artifacts
* tests/tests_sign_workflow/data/signature/
*  tests/tests_assemble_workflow/data/artifacts/
* .png 
* settings.gradle 
* Everything in `.git`

Let's first fix this and then see in the second iteration. 
Also feel free to add license text to missing files.
Thanks!

**Comment by hitenshKharva** [comment]
Updated the workflow run with the list of files to be ignored. Let me know if we need any more changes.
I would recommend creating an issue to add the licenses in all the `missing copyright` files to make sure it is tracked.
Thanks.

**Comment by peterzhuamazon** [comment]
> Updated the workflow run with the list of files to be ignored. Let me know if we need any more changes. I would recommend creating an issue to add the licenses in all the `missing copyright` files to make sure it is tracked. Thanks.

Thanks @hitenshKharva ,

You can go ahead and open an issue then link to this PR as follow up.

Think both the add missing license PR and this PR needs to go in in order. Thanks.

**Comment by gaiksaya** [comment]
Right! The missing files needs to add licenses before we can merge this else the CI will fail for all PRs in this repository. Either make changes in this PR itself or hold on until all licenses are in, in another PR.
Thanks!

**Comment by hitenshKharva** [comment]
I have summarized below the list of extensions that have `missing copyright`. Let me know which ones need to be ignored.

.lychee.excludes
.shellcheckrc
.whitesource
.lock
.gradle
.dockerfile
.sh
.cert
.key
.properties
.jar
.bat
.jenkinsfile
.groovy
.toml
.ini
.spec
.service

Thanks

**Comment by gaiksaya** [comment]
Below files can be ignored:

```
.lychee.excludes
.shellcheckrc
.whitesource
.lock
.gradle
.cert
.key
.jar
.bat
.toml
.ini

**Comment by gaiksaya** [comment]
Please rebase with main branch to reflect updated license files.

**Comment by peterzhuamazon** [comment]
Need rebase to fix the dco here.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Thanks @hitenshKharva for the great contribution here.

**Pull request merged**
