### PR TITLE
Added notifications-core and notifications to 2.0 and add integTest manifest

### PR DESCRIPTION
**Pull request by dblock**
Signed-off-by: dblock <dblock@dblock.org>

### Description

Simpler alternative to https://github.com/opensearch-project/opensearch-build/pull/1956. Requires https://github.com/opensearch-project/notifications/pull/403

### Issues Resolved

Closes https://github.com/opensearch-project/opensearch-build/issues/1950.
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
As discussed in #1956 we will go with #1957 for now.
This allows us to use existing code base and functionalities to resolve the problem without changing too much for this specific use case.

Thanks.

**Comment by dblock** [comment]
CI was failing on checks because it tries to execute `./gradlew` in `notiications/core` which doesn't exist. I just removed the checks for now. Really notifications/core feels like a very weird hack all around.

**Comment by peterzhuamazon** [comment]
I have tweaked the build.sh so it will build correctly now.

**Comment by peterzhuamazon** [comment]
This will go in with another PR: https://github.com/opensearch-project/notifications/pull/404

**Comment by peterzhuamazon** [comment]
Seems like notifications due to `name` field is not matching the repo name of `notifications`.
It is better to save the build scripts in build repo not notifications repo.

**Comment by dblock** [comment]
> Seems like notifications due to `name` field is not matching the repo name of `notifications`. 

I don't think so. The check for `notifications-core` just failed with `gradlew` being not found, because there's none in `notifications/core`. Build works because we have `notifications/core/scripts`.

> It is better to save the build scripts in build repo not notifications repo.

Build scripts change version-to-version, so they need to be different and follow notifications branching. If you leave them in opensearch-build with these changes, 1.3.x will start failing.

**Review by peterzhuamazon — DISMISSED** [review]
Block for a bit as we are still fixing the build scripts.
Due to the double subfolder structure of notifications the builds folder and plugins are not correctly copied to tar/builds/opensearch/plugins.

**Review by tianleh — APPROVED** [review]

**Comment by gaiksaya** [comment]
@peterzhuamazon Can we add the checks back or are they still failing?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon Can we add the checks back or are they still failing?

They will not pass as notifications structure is different from any other repos.

They need to build within `notifications` folder, but working directory is pointing to `notifications/core` and `notifications/notifications` and those two folders does not have gradle wrapper to run the tests.

**Comment by peterzhuamazon** [comment]
@gaiksaya fixed in https://github.com/opensearch-project/opensearch-build/pull/1959

**Pull request merged**
