### PR TITLE
[Dashboards] Bumps Node version to 14.18.2 for Dashboards Node upgrade

### LINKED ISSUE #1320: [Dashboards] Upgrade to Node 14
This is blocked by: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/920

### Is your feature request related to a problem? Please describe

Add Node 14 for OpenSearch Dashboards when is merged. We are working [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/920) to upgrade OpenSearch Dashboards to Node 14.

### Describe the solution you'd like

We will need to update the build process to support the node upgrade. I believe the CI runner docker images will need to be updated: https://github.com/opensearch-project/opensearch-build/tree/4107aaa25714371b63708e08e6b5485231adc312/docker/ci/dockerfiles.

Along with publishing it to Dockerhub to be picked up and used by the pipeline.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by boktorbb-amzn**
Signed-off-by: Bishoy Boktor <boktorbb@amazon.com>

### Description
Bumps Node version to 14.18.2 for Dashboards Node upgrade 
 
### Issues Resolved
#1320 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kavilla** [comment]
After this is merged we will need to publish and then use it in the Jenkinsfiles for example:
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/distribution-build.jenkinsfile#L21

But we will need to keep the other images since we won't be backporting the node upgrade to 1.x version of OpenSearch Dashboards.

**Review by peternied — APPROVED** [review]
@gaiksaya can you work with @boktorbb-amzn & @kavilla to update the CI images after this change is in?

**Comment by gaiksaya** [comment]
> @gaiksaya can you work with @boktorbb-amzn & @kavilla to update the CI images after this change is in?

Yes sounds good.

**Review by gaiksaya — APPROVED** [review]

**Comment by gaiksaya** [comment]
Regarding naming convention for this image on dockerhub, what should that be?
https://hub.docker.com/r/opensearchstaging/ci-runner/tags

**Comment by peterzhuamazon** [comment]
> Regarding naming convention for this image on dockerhub, what should that be? https://hub.docker.com/r/opensearchstaging/ci-runner/tags I believe we do not need to include all kinds of libraries that we have installed on base image in that tag name. How about just naming with major version changes, eg: `al2-node14.18.2`? @dblock @peternied thoughts?

ci-runner-centos7-v2

**Comment by peternied** [comment]
Tossing in my thoughts, `ci-runner-centos7-v2` is a name, but it isn't a very useful name.  I think it would be appropriate to strongly associate this line of docker images with there usage. 

### Proposal
`{THEME}-{OS}-{PROJECT}-{PURPOSE}`

| Theme | OS | Project | Purpose| 
| - | -| -| -|
|ci-runner| centos7|opensearch-dashboards|build

----

I am comfortable with other conventions, so long as they can help articulate one image from another without looking inside

**Review by peternied — APPROVED** [review]

**Pull request merged**
