### PR TITLE
Update commits for 7th RC for 2.10.0

### PR DESCRIPTION
**Pull request by gaiksaya**
### Description
Update commits for 7th RC for 2.10.0

### Issues Resolved
#3743 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jordarlu — APPROVED** [review]

**Review by peterzhuamazon — APPROVED** [review]

**Comment by bbarani** [comment]
Lets wait for https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/881?

**Comment by gaiksaya** [comment]
> Lets wait for [opensearch-project/opensearch-dashboards-functional-test#881](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/881)?

Merged!

**Comment by bbarani** [comment]
> > Lets wait for [opensearch-project/opensearch-dashboards-functional-test#881](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/881)?
> 
> Merged!

Do we need to update the commit for functional test repo as well?

**Comment by gaiksaya** [comment]
> > > Lets wait for [opensearch-project/opensearch-dashboards-functional-test#881](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/881)?
> > 
> > 
> > Merged!
> 
> Do we need to update the commit for functional test repo as well?

No its pointing to 2.10 branch so we are good. It picks up latest

**Pull request merged**
