### PR TITLE
Use 2.6.0 Ruby and tweak jdk tool naming to be consistent with docker images

### LINKED ISSUE #2364: Update the docker images for ruby client release to use a higher Ruby version
Coming from https://github.com/opensearch-project/opensearch-build/issues/2360#issuecomment-1194507743, Faraday requires Ruby version >=2.6. As mentioned in the comment, the Ruby version needs to be updated to 2.6

### PR DESCRIPTION
**Pull request by peterzhuamazon**
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>

### Description
Use 2.6.0 Ruby and tweak jdk tool naming to be consistent with docker images

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/pull/2365, #2364

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon should this new `dockerImages` be part of any jenkinsfile?

**Comment by peterzhuamazon** [comment]
> Hey @peterzhuamazon should this new `dockerImages` be part of any jenkinsfile?

@prudhvigodithi this is not major changes thus we will create v2.x version then map them back to v2.
Therefore we preserve the old image while no need to change tags.

**Review by prudhvigodithi — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Pause on merging will only merge once images are created.

**Comment by peterzhuamazon** [comment]
Images:
* https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&name=ci-runner-centos7-opensearch-dashboards-build-v2
* https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&name=ci-runner-centos7-opensearch-build-v2
* https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&name=ci-runner-rockylinux8-opensearch-build-v2

**Pull request merged**
