### PR TITLE
Add dockerfile for releasing clients

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
This image will be used in standard clients release pipeline. Incremental changes will be made as and when required to add new packges.

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/1606

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
My problem with this file is, it is very similar to the normal opensearch centos7 build image.
What are the additional changes that clients need?
I would even suggest a alpine3 image if they have limited differences or just use the same build image.

**Comment by gaiksaya** [comment]
As stated in the PR description changes will be incremental. Starting with what we have but there are 9 clients and other components that will need different version of nodejs, different java versions, etc that will be added in this file. Also changes in opensearch image should be affected to others and vice versa hence keep if different.

**Comment by peterzhuamazon** [comment]
> As stated in the PR description changes will be incremental. Starting with what we have but there are 9 clients and other components that may need different version of nodejs, different java versions, etc that will be added in this file. Also changes in opensearch image should be affected to others and vice versa hence keep if different. I'll start working on npm client next that will give me some idea what all changes will go in here. Also OpenSearch ci image is more for build and this one is more for release. I'll add / remove things going forward.

Sure, please create an image in staging hub with this naming:
`ci-runner-centos7-clients-v1` and `ci-runner-centos7-clients-v1.1`.
Next time if there is any update just create `ci-runner-centos7-clients-v1.2` and copy v1.2 to v1.

We will merge this PR once the image is online.

Thanks.

**Comment by gaiksaya** [comment]
Thanks will be naming it release-centos7-clients-v1 since ci-runner is already the name of the repository. No need to state that again. The final image with repo will say:
```
opensearchstaging/ci-runner:release-centos7-clients-v1
opensearchstaging/ci-runner:release-centos7-clients-v1.1
```

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
