### PR TITLE
Optimize Docker images size

### LINKED ISSUE #92: Optimize Docker image: reduce half of the size
**Is your feature request related to a problem? Please describe.**
The Docker image `opensearchproject/opensearch` is heavy compare with `elasticsearch`.
`opensearch` v1.0.0 is 915mb in Docker Hub, while `elasticsearch` v7.13.3 is 473mb.

**Describe the solution you'd like**
Optimize Dockerfile build stages. There's a waste of space introduce by a layer which cause the size is duplicated:
image

Layer 10 have `chown` command, whilst we can chown it in layer 6 (Dockerfile `COPY` command has --chown flag).

### PR DESCRIPTION
**Pull request by osddeitf**
### Description
Reduce Docker images size by half.
 
### Issues Resolved
Fix #92, #89
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
Hi @osddeitf thank you for your contribution.
Can you also let us know the difference in the size of the image that you see after you make this change?

Thanks!

**Comment by osddeitf** [comment]
As i said, it's half the size:
```
➜  opensearch git:(main) ✗ docker images | head
REPOSITORY                                TAG           IMAGE ID       CREATED          SIZE
opensearchproject/opensearch              local         9077538f358f   53 seconds ago   831MB
amazonlinux                               2             add9612f9214   26 hours ago     164MB
opensearchproject/opensearch              1.0.0         88b67cc9e81f   7 days ago       1.54GB
opensearchproject/opensearch-dashboards   1.0.0         6a109c3fbebf   7 days ago       1.63GB

**Comment by osddeitf** [comment]
I changed this PR to draft, because I see that after my changes, some files permissions are affected:
```
[opensearch@3a18683a0332 ~]$ ls -l
total 296
-rw-r--r--  1 opensearch opensearch  11358 Jul  2 23:22 LICENSE.txt
-rw-r--r--  1 opensearch opensearch 215360 Jul  2 23:22 NOTICE.txt
-rw-r--r--  1 opensearch opensearch   3780 Jul  2 23:22 README.md
drwxr-xr-x  1 opensearch opensearch   4096 Jul  8 22:32 bin
drwxr-xr-x  1 opensearch opensearch   4096 Jul 17 01:32 config
drwxr-xr-x  2 opensearch opensearch   4096 Jul  8 22:32 data
drwxr-xr-x  9 opensearch opensearch   4096 Jul  2 23:23 jdk
drwxr-xr-x  3 opensearch opensearch   4096 Jul  2 23:23 lib
drwxr-xr-x  2 opensearch opensearch   4096 Jul  2 23:22 logs
drwxr-xr-x 19 opensearch opensearch   4096 Jul  2 23:23 modules
-rwxr-xr-x  1 opensearch opensearch   4283 Jul 16 09:58 opensearch-docker-entrypoint.sh
-rwxr-xr-x  1 opensearch opensearch   1271 Jul 16 09:58 opensearch-onetime-setup.sh
-rwxr-xr-x  1 opensearch opensearch   3132 Jul  8 22:32 opensearch-tar-install.sh
drwxr-xr-x  6 opensearch opensearch   4096 Jul  8 22:32 performance-analyzer-rca
drwxr-xr-x  1 opensearch opensearch   4096 Jul  8 22:32 plugins
-rwxr-xr-x  1 root       root          315 Jul 17 01:32 securityadmin_demo.sh
```
```
[opensearch@3a18683a0332 ~]$ ls -l config/
total 44
-rw-r--r-- 1 root       root       1704 Jul 17 01:32 esnode-key.pem
-rw-r--r-- 1 root       root       1720 Jul 17 01:32 esnode.pem
-rw-r----- 1 opensearch opensearch 2515 Jul 17 01:32 jvm.options
drwxr-x--- 2 opensearch opensearch 4096 Jul  2 23:22 jvm.options.d
-rw-r--r-- 1 root       root       1704 Jul 17 01:32 kirk-key.pem
-rw-r--r-- 1 root       root       1610 Jul 17 01:32 kirk.pem
-rw-r--r-- 1 opensearch opensearch  285 Jul 16 09:58 log4j2.properties
drwxr-x--- 2 opensearch opensearch 4096 Jul  8 22:32 opensearch-notebooks
drwxr-x--- 2 opensearch opensearch 4096 Jul  8 22:32 opensearch-reports-scheduler
-rw-r--r-- 1 opensearch opensearch 2013 Jul 17 01:32 opensearch.yml
-rw-r--r-- 1 root       root       1444 Jul 17 01:32 root-ca.pem
```

For `securityadmin_demo.sh` owner change, as permission is 755, it's fine as long as anyone can execute it, right?
But how do you think about files in `config/` folder? I guess I should add this to Dockerfile:
```
chown -R $UID:$GID $OPENSEARCH_HOME/config

**Comment by peterzhuamazon** [comment]
Hi @osddeitf ,
1. Yes as long as we can run securityadmin_demo.sh so 755 is ok.
2. can you change the line 80 to run as `opensearch` user instead of root and try again?

```
RUN su - opensearch -c "./opensearch-onetime-setup.sh"
```

**Comment by peterzhuamazon** [comment]
This can also resolve the issues in #56

**Comment by osddeitf** [comment]
There's no `su`, `sudo` command in the container for running with different users, should we install it?

**Comment by osddeitf** [comment]
Also, there's a command inside `scripts/opensearch-onetime-setup.sh` that need superuser privilege: `chmod -R 755 /dev/shm`.
I don't know that command is necessary or not, because the default permission of `/dev/shm` is 777.

**Comment by osddeitf** [comment]
I tried to install `su`, then run `./opensearch-onetime-setup.sh` with `opensearch` user. It'll work if we remove or move `chmod -R 755 /dev/shm` command to Dockerfile.

**Comment by osddeitf** [comment]
It seems that `/dev/shm` after build process is back to 777 again, this is in `opensearchproject/opensearch:1.0.0` container:
```
drwxrwxrwt 2 root       root     40 Jul 22 01:57 shm
```
After tries, I managed to achieve this:
```
opensearchproject/opensearch   local     bc316a8b99e0   About a minute ago   893MB
opensearchproject/opensearch   1.0.0     88b67cc9e81f   12 days ago          1.54GB

**Comment by osddeitf** [comment]
I've done with my modifications, please double check for me again that file permissions are the same with `opensearchproject/opensearch:1.0.0`.

**Comment by peterzhuamazon** [comment]
Hi @osddeitf I build the image without removing `chmod 777 /dev/shm` and it succeed.
```
 => [stage-1 6/7] RUN su - opensearch -c "./opensearch-onetime-setup.sh"                                                                                                                                                                                                                                               0.9s
```

I dont think this is a blocker since the onetime script does not fail due to no `set -e`.

I do have another concern on whether adding `su` would have security concerns as it allow users to switch to another one. But since `opensearch` does not have the required sudo permission, this probably is just an oversight.

Let me know what you think about these.

Thanks.

**Comment by osddeitf** [comment]
That's so dumb of me, instead of using `su`, we just need to move the command like this:
```
# Change user
USER $UID

# Setup OpenSearch
RUN ./opensearch-onetime-setup.sh
```

**Comment by peterzhuamazon** [comment]
> That's so dumb of me, instead of using `su`, we just need to move the command like this:
> 
> ```
> # Change user
> USER $UID
> 
> # Setup OpenSearch
> RUN ./opensearch-onetime-setup.sh
> ```

I am not sure why I also forgot about that......Nice catch.
This change apparently should also resolve another issue with docker namespace. #89 
Let me check on it and see if we can approve this.

Thanks.

**Comment by peterzhuamazon** [comment]
Building test, a lot faster at this point:
```
[+] Building 20.5s (19/19) FINISHED
 => [internal] load build definition from opensearch.al2.dockerfile                                                                                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 4.35kB                                                                                                                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/amazonlinux:2                                                                                                                                                                                                                                                       0.0s
 => [linux_x64_stage_0 1/8] FROM docker.io/library/amazonlinux:2                                                                                                                                                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                      9.2s
 => => transferring context: 431.21MB                                                                                                                                                                                                                                                                                  9.2s
 => CACHED [linux_x64_stage_0 2/8] RUN yum update -y && yum install -y tar gzip shadow-utils && yum clean all                                                                                                                                                                                                          0.0s
 => [stage-1 3/8] RUN groupadd -g 1000 opensearch &&     adduser -u 1000 -g 1000 -d /usr/share/opensearch opensearch                                                                                                                                                                                                   1.6s
 => CACHED [linux_x64_stage_0 3/8] RUN groupadd -g 1000 opensearch &&     adduser -u 1000 -g 1000 -d /usr/share/opensearch opensearch &&     mkdir /tmp/opensearch                                                                                                                                                     0.0s
 => CACHED [linux_x64_stage_0 4/8] COPY opensearch.tgz /tmp/opensearch/opensearch.tgz                                                                                                                                                                                                                                  0.0s
 => CACHED [linux_x64_stage_0 5/8] RUN tar -xzf /tmp/opensearch/opensearch.tgz -C /usr/share/opensearch --strip-components=1 && rm -rf /tmp/opensearch                                                                                                                                                                 0.0s
 => CACHED [linux_x64_stage_0 6/8] COPY opensearch-docker-entrypoint.sh opensearch-onetime-setup.sh /usr/share/opensearch/                                                                                                                                                                                             0.0s
 => CACHED [linux_x64_stage_0 7/8] COPY log4j2.properties opensearch.yml /usr/share/opensearch/config/                                                                                                                                                                                                                 0.0s
 => CACHED [linux_x64_stage_0 8/8] COPY performance-analyzer.properties /usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/                                                                                                                                                                       0.0s
 => [stage-1 4/8] COPY --from=linux_x64_stage_0 --chown=1000:1000 /usr/share/opensearch /usr/share/opensearch                                                                                                                                                                                                          7.0s
 => [stage-1 5/8] WORKDIR /usr/share/opensearch                                                                                                                                                                                                                                                                        0.0s
 => [stage-1 6/8] RUN echo "export JAVA_HOME=/usr/share/opensearch/jdk" >> /etc/profile.d/java_home.sh                                                                                                                                                                                                                 0.2s
 => [stage-1 7/8] RUN cp -v plugins/opensearch-knn/knnlib/libKNNIndex*.so /usr/lib                                                                                                                                                                                                                                     0.5s
 => [stage-1 8/8] RUN ./opensearch-onetime-setup.sh                                                                                                                                                                                                                                                                    0.5s
 => exporting to image                                                                                                                                                                                                                                                                                                 2.8s
 => => exporting layers                                                                                                                                                                                                                                                                                                2.8s
 => => writing image sha256:8edea115a9563ee227e692438aa95d94d5d6f7ac8fe0838db8bca46fe951de34                                                                                                                                                                                                                           0.0s
 => => naming to docker.io/opensearchproject/opensearch:1.0.0
```

```
[+] Building 74.3s (17/17) FINISHED
 => [internal] load build definition from opensearch-dashboards.al2.dockerfile                                                                                                                                                                                                                                         0.0s
 => => transferring dockerfile: 4.48kB                                                                                                                                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/amazonlinux:2                                                                                                                                                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                      4.0s
 => => transferring context: 204.19MB                                                                                                                                                                                                                                                                                  4.0s
 => CACHED [linux_x64_stage_0 1/7] FROM docker.io/library/amazonlinux:2                                                                                                                                                                                                                                                0.0s
 => CACHED [stage-1 2/6] WORKDIR /usr/share/opensearch-dashboards                                                                                                                                                                                                                                                      0.0s
 => [stage-1 3/6] RUN yum update -y && yum install -y tar gzip shadow-utils && yum clean all                                                                                                                                                                                                                          27.4s
 => [linux_x64_stage_0 2/7] RUN yum update -y && yum install -y tar gzip shadow-utils && yum clean all                                                                                                                                                                                                                27.6s
 => [stage-1 4/6] RUN yum install -y libnss3.so xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc fontconfig freetype && yum clean all                                                                                                       25.1s
 => [linux_x64_stage_0 3/7] RUN groupadd -g 1000 opensearch-dashboards &&     adduser -u 1000 -g 1000 -d /usr/share/opensearch-dashboards opensearch-dashboards &&     mkdir /tmp/opensearch-dashboards                                                                                                                0.6s
 => [linux_x64_stage_0 4/7] COPY opensearch-dashboards.tgz /tmp/opensearch-dashboards/opensearch-dashboards.tgz                                                                                                                                                                                                        0.5s
 => [linux_x64_stage_0 5/7] RUN tar -xzf /tmp/opensearch-dashboards/opensearch-dashboards.tgz -C /usr/share/opensearch-dashboards --strip-components=1 && rm -rf /tmp/opensearch-dashboards                                                                                                                           11.2s
 => [linux_x64_stage_0 6/7] COPY opensearch-dashboards-docker-entrypoint.sh /usr/share/opensearch-dashboards/                                                                                                                                                                                                          0.0s
 => [linux_x64_stage_0 7/7] COPY opensearch_dashboards.yml opensearch.example.org.* /usr/share/opensearch-dashboards/config/                                                                                                                                                                                           0.0s
 => [stage-1 5/6] RUN groupadd -g 1000 opensearch-dashboards &&     adduser -u 1000 -g 1000 -d /usr/share/opensearch-dashboards opensearch-dashboards                                                                                                                                                                  0.4s
 => [stage-1 6/6] COPY --from=linux_x64_stage_0 --chown=1000:1000 /usr/share/opensearch-dashboards /usr/share/opensearch-dashboards                                                                                                                                                                                   11.7s
 => exporting to image                                                                                                                                                                                                                                                                                                 9.7s
 => => exporting layers                                                                                                                                                                                                                                                                                                9.7s
 => => writing image sha256:3da0e3e0ba5d5f19aea7a310611b2c0549a03dcd1058693b84462beeb5442730                                                                                                                                                                                                                           0.0s
 => => naming to docker.io/opensearchproject/opensearch-dashboards:1.0.0
```

**Comment by peterzhuamazon** [comment]
Curl calls:
```
$ curl https://localhost:9200/ -u admin:admin --insecure
{
  "name" : "opensearch-node1",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "FO0lhcU7Tzim-7SjhOdvUQ",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0",
    "build_type" : "tar",
    "build_hash" : "34550c5b17124ddc59458ef774f6b43a086522e3",
    "build_date" : "2021-07-02T23:22:21.383695Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

```
$ curl localhost:5601/api/status
{"name":"145a7296fbcd","uuid":"46342bb9-2844-419e-bebb-3de24016178a","version":{"number":"1.0.0","build_hash":"b15ad258e6960003e609a70889cda5fb39f90947","build_number":36473,"build_snapshot":false},"status":{"overall":{"since":"2021-07-23T16:42:46.005Z","state":"green","title":"Green","nickname":"Looking good","icon":"success","uiColor":"secondary"},"statuses":[{"id":"core:opensearch@1.0.0","message":"OpenSearch is available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"core:savedObjects@1.0.0","message":"SavedObjects service has completed migrations and is available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:advancedSettings@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:bfetch@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:charts@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:devTools@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:discover@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:embeddable@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:expressions@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:indexPatternManagement@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:inspector@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:legacyExport@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:management@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:navigation@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:opensearchDashboardsOverview@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:opensearchDashboardsReact@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:opensearchDashboardsUsageCollection@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:opensearchDashboardsUtils@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:opensearchUiShared@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:savedObjects@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:savedObjectsManagement@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:share@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:uiActions@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:urlForwarding@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visDefaultEditor@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visualizations@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visualize@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:ganttChartDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:notebooksDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:queryWorkbenchDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:reportsDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:traceAnalyticsDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:apmOss@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:console@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:dashboard@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:data@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:home@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:inputControlVis@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:mapsLegacy@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:opensearchDashboardsLegacy@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:regionMap@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:tileMap@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:timeline@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:usageCollection@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeMarkdown@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeMetric@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeTable@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeTagcloud@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeTimeline@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeTimeseries@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeVega@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:visTypeVislib@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:alertingDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:anomalyDetectionDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:indexManagementDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"},{"id":"plugin:securityDashboards@1.0.0","message":"All dependencies are available","since":"2021-07-23T16:42:46.005Z","state":"green","icon":"success","uiColor":"secondary"}]},"metrics":{"last_updated":"2021-07-23T16:42:42.270Z","collection_interval_in_millis":5000,"os":{"platform":"linux","platformRelease":"linux-5.10.25-linuxkit","load":{"1m":0.533203125,"5m":0.64404296875,"15m":0.3017578125},"memory":{"total_in_bytes":4127535104,"free_in_bytes":117293056,"used_in_bytes":4010242048},"uptime_in_millis":406000,"distro":"Amazon Linux","distroRelease":"Amazon Linux-2 (Karoo)","cpuacct":{"control_group":"/","usage_nanos":9276575030},"cpu":{"control_group":"/","cfs_period_micros":100000,"cfs_quota_micros":-1,"stat":{"number_of_elapsed_periods":0,"number_of_times_throttled":0,"time_throttled_nanos":0}}},"process":{"memory":{"heap":{"total_in_bytes":102047744,"used_in_bytes":90818456,"size_limit":1526909922},"resident_set_size_in_bytes":132190208},"pid":1,"event_loop_delay":0.5845749999862164,"uptime_in_millis":118154},"response_times":{"avg_in_millis":0,"max_in_millis":0},"concurrent_connections":0,"requests":{"disconnects":0,"total":0,"statusCodes":{},"status_codes":{}}}}
```

**Review by peterzhuamazon — APPROVED** [review]
This works great thanks @osddeitf for the help. Approve.

**Comment by osddeitf** [comment]
You're welcome. I'm glad that my work is helpful.

**Review by bbarani — APPROVED** [review]

**Pull request merged**
